/**
 * Puntos adicionales del Parco Archeologico di Pompei que no forman parte de las
 * veinticuatro paradas de la ruta clásica (src/content/route.ts). Sirven para un
 * "modo total" del recorrido, con el mismo orden caminable pero mucho más denso.
 * El campo `order` usa decimales para insertar cada punto entre las paradas
 * existentes sin renumerarlas. No incluyen `directionsToNext`: el enrutador
 * dinámico calcula el trayecto entre paradas consecutivas según `coords`.
 */
import type { Stop } from './types';

export const EXTRA_STOPS: Stop[] = [
  {
    id: 'terme-suburbane',
    order: 0.5,
    name: 'Termas Suburbanas',
    latinName: 'Terme Suburbane',
    category: 'termas',
    coords: [40.7486, 14.4828],
    minutes: 10,
    intro: 'Bajad por la rampa de la Porta Marina y fijaos en esa fachada de ladrillo a la izquierda, medio escondida bajo la terraza del Templo de Venus: ahí dentro está el vestuario más comentado de todo el yacimiento.',
    narration: [
      'Entrad y mirad hacia arriba, a las hornacinas donde los clientes dejaban la ropa mientras se bañaban. Sobre ocho de ellas se conservan todavía otras tantas escenas eróticas, de las dieciséis pintadas en origen, y entre ellas hay una escena entre dos mujeres que es la única de este tipo conocida en toda la pintura romana. Nadie se pone de acuerdo sobre su sentido. Pudo ser decoración picante, un modo jocoso de numerar las taquillas o publicidad de servicios adicionales del propio negocio.',
      'Lo que casi nadie busca aquí es la fuente de bronce con un sátiro que decoraba una de las salas, y el mosaico de cupidos armando a Marte junto a la entrada, dos piezas discretas que sobreviven a la sombra de las escenas del vestuario. Este era un balneario privado, de pago, no un servicio público como el que visitaréis luego junto al Foro, y esa diferencia dice mucho de quién podía permitirse aquí un baño caliente antes de entrar en la ciudad.',
    ],
    lookFor: [
      'Las pequeñas escenas eróticas pintadas sobre las antiguas hornacinas del vestuario.',
      'La fuente de bronce con un sátiro que decoraba una de las salas.',
      'El mosaico con cupidos armando a Marte, cerca de la entrada.',
    ],
    anecdote: 'Durante décadas estas pinturas estuvieron cerradas al público general por su contenido, y solo se mostraban con permiso especial: hoy son una parada habitual, aunque conviene avisar de su contenido si vais con menores.',
    tips: [
      'Quedan justo debajo de la terraza del Templo de Venus, en el lateral de la rampa de la Porta Marina; es fácil pasarlas por alto si no se busca la entrada expresamente.',
      'Contienen pintura erótica explícita: valorad si conviene con niños pequeños en el grupo.',
    ],
    illus: 'termas',
    accessibility: 'medio',
  },
  {
    id: 'antiquarium',
    order: 1.1,
    name: 'Antiquarium de Pompeya',
    latinName: 'Antiquarium di Pompei',
    category: 'servicio',
    coords: [40.74854, 14.48329],
    regio: 'VIII.1.4',
    minutes: 12,
    intro: 'Antes de perderos entre las ruinas, entrad aquí: este edificio guarda las caras y los objetos que le faltan a todo lo demás que vais a ver hoy.',
    narration: [
      'Mirad primero la sala dedicada a los calcos de yeso. Giuseppe Fiorelli, el arqueólogo que ideó esta técnica, abrió el primer Antiquarium en mil ochocientos setenta y tres justo en esta zona, para que los objetos hallados se quedaran junto al yacimiento en lugar de dispersarse por museos lejanos. Amedeo Maiuri lo amplió en mil novecientos veintiséis, pero un bombardeo aliado lo destruyó casi entero en septiembre de mil novecientos cuarenta y tres, con miles de piezas perdidas para siempre.',
      'El edificio que recorréis ahora reabrió en enero de dos mil veintiuno, con salas nuevas sobre el urbanismo, la vida doméstica y la erupción. Buscad el calco del caballo ensillado de la villa de Civita Giuliana, y junto a él el de un hombre y un posible esclavo hallados en el mismo lugar. El detalle que casi nadie se detiene a mirar es el Tesoro de Moregine, una vajilla de plata tan fina que parece imposible que sobreviviera diecinueve siglos bajo tierra.',
    ],
    lookFor: [
      'Los calcos de yeso de las víctimas, obtenidos vertiendo escayola en los huecos que dejaron los cuerpos en la ceniza endurecida.',
      'El caballo ensillado hallado en la villa de Civita Giuliana, en las afueras del yacimiento.',
      'El Tesoro de Moregine, un conjunto de vajilla de plata de gran calidad.',
    ],
    tips: [
      'Suele incluirse en la entrada general al yacimiento; conviene comprobar el horario, algo más corto que el del recinto arqueológico.',
      'Es un buen refugio con sombra y aire fresco para hacer una pausa a media visita.',
    ],
    image: { src: 'fiorelli-retrato', alt: 'Busto de Giuseppe Fiorelli, fundador del primer Antiquarium de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'yeso',
    accessibility: 'facil',
  },
  {
    id: 'comitium',
    order: 3.1,
    name: 'Comitium',
    latinName: 'Comitium',
    category: 'foro',
    coords: [40.749062, 14.485477],
    regio: 'VIII.3.1',
    minutes: 6,
    intro: 'Fijaos en este recinto abierto, sin techo, pegado a la Basílica: aquí es donde Pompeya decidía, una vez al año, quién la iba a gobernar.',
    narration: [
      'Poneos en el centro y mirad los pilares que dan a la Via dell\'Abbondanza. Todavía se leen ahí restos de carteles pintados, los programmata, con los que un vecino recomendaba a otro su candidato favorito para duunviro o para edil. Se excavó en mil ochocientos catorce y de nuevo en mil ochocientos veintiséis, y algunos investigadores fechan la fábrica en época republicana, con una reforma posterior ya bajo Augusto.',
      'Lo que nadie repara es que el suelo de mármol que tuvo originalmente casi ha desaparecido, arrancado por excavadores clandestinos durante siglos después de la erupción. Un estudio con georradar de la Universidad de Tubinga, entre dos mil diecisiete y dos mil diecinueve, ha ayudado a reconstruir sus fases. La Basílica, donde se litigaba, queda a un paso; aquí, en cambio, se votaba.',
    ],
    lookFor: [
      'Los pilares hacia la Via dell\'Abbondanza, donde se pintaban los carteles electorales de los candidatos.',
      'La planta abierta del recinto, sin cubrir, pensada para las asambleas de voto.',
      'La cercanía inmediata a la Basílica, sede de la justicia, y al propio Foro.',
    ],
    tips: [
      'Es una parada corta, ideal para explicar cómo funcionaba la vida electoral pompeyana antes de seguir hacia el Foro.',
    ],
    image: { src: 'comitium', alt: 'El Comitium, recinto de voto junto al Foro de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'foro',
    accessibility: 'facil',
  },
  {
    id: 'edificios-municipales',
    order: 3.2,
    name: 'Edificios municipales',
    latinName: 'Edifici della Pubblica Amministrazione',
    category: 'foro',
    coords: [40.748691, 14.485125],
    regio: 'VIII.2.6-10',
    minutes: 8,
    intro: 'Contad conmigo estas tres salas idénticas, alineadas en el lado sur del Foro: ahí dentro cabía la administración entera de una ciudad de once mil habitantes.',
    narration: [
      'Mirad la planta absidada, repetida tres veces como si el arquitecto no quisiera arriesgarse a elegir. Una sala era la curia, donde se reunían los decuriones del consejo municipal; otra, el tabularium, el archivo de la ciudad; la tercera, la oficina de los duunviros y ediles. Los especialistas discuten todavía qué sala era cuál, así que tomad estos nombres con cautela.',
      'El detalle que nadie busca es que las tres quedaron gravemente dañadas por el terremoto del año sesenta y dos, y seguían en obras cuando llegó la erupción diecisiete años después. Imaginad los censos, los registros de propiedad y las actas del consejo escritos en tablillas de cera, hoy perdidas para siempre. Entre la Basílica y el Edificio de Eumáquia, este era el corazón de papeleo de Pompeya.',
    ],
    lookFor: [
      'La planta absidada, casi idéntica, de las tres salas alineadas en el lado sur del Foro.',
      'Los restos de pavimento y de revestimiento de mármol, muy fragmentarios por los daños del terremoto anterior a la erupción.',
      'La posición central de este conjunto, entre la Basílica y el Edificio de Eumáquia, en pleno corazón administrativo de la ciudad.',
    ],
    tips: [
      'Forman parte del recorrido habitual del Foro, así que no exigen desvío alguno.',
    ],
    illus: 'foro',
    accessibility: 'facil',
  },
  {
    id: 'granai-foro',
    order: 4.1,
    name: 'Granai del Foro',
    latinName: 'Granai del Foro',
    category: 'comercio',
    coords: [40.74964, 14.48426],
    regio: 'VII.7.29',
    minutes: 8,
    intro: 'Acercaos a las rejas de este edificio y mirad dentro: cientos de ánforas alineadas en la penumbra, como si el mercado hubiera cerrado ayer.',
    narration: [
      'Fijaos en las columnas, todavía toscas, sin el enlucido final que les faltaba cuando llegó la erupción. Los Granai del Foro se reconstruyeron después del terremoto del año sesenta y dos como un gran mercado cubierto de grano y legumbres, con ocho entradas independientes desde la plaza. La obra nunca se terminó, y ese inacabado es justo lo que hoy lo vuelve tan revelador.',
      'Lo que pocos saben es que este mercado a medio hacer se convirtió después en almacén arqueológico, con más de nueve mil objetos catalogados: ánforas, fragmentos de mármol y varios calcos de víctimas, entre ellos uno especialmente conmovedor, el de un perro. El interior solo se abre en jornadas extraordinarias, pero desde las rejas, a un paso del Foro, ya se intuye la escala del hallazgo.',
    ],
    lookFor: [
      'Las hileras de ánforas y fragmentos de mármol almacenados, visibles a través de las rejas de las entradas.',
      'Alguno de los calcos de yeso conservados en el interior, entre ellos el de un perro.',
      'El aspecto inacabado de las columnas, sin el enlucido final que habría recibido el edificio.',
    ],
    tips: [
      'El interior no se visita en el recorrido habitual; solo se abre por completo en jornadas extraordinarias anunciadas por el parque arqueológico.',
    ],
    image: { src: 'anfora', alt: 'Ánforas romanas almacenadas entre las ruinas de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'anfora',
    accessibility: 'facil',
  },
  {
    id: 'templo-giove',
    order: 5.1,
    name: 'Templo de Júpiter',
    latinName: 'Tempio di Giove',
    category: 'templo',
    coords: [40.7499, 14.4845],
    regio: 'VII.8',
    minutes: 8,
    intro: 'Poneos en el centro de la plaza y mirad hacia el norte: el templo, el podio y el Vesubio se alinean como si alguien lo hubiera calculado a propósito.',
    narration: [
      'El templo original se levantó hacia mediados del siglo dos antes de nuestra era. Tras la conquista romana de la ciudad en el año ochenta antes de Cristo se reconvirtió en Capitolio, dedicado a la misma tríada, Júpiter, Juno y Minerva, que presidía el templo más importante de la propia Roma. No hacía falta ningún cartel para anunciar que Pompeya ya era ciudad romana.',
      'El terremoto del año sesenta y dos lo dañó gravemente, y seguía en obras cuando llegó la erupción. Aquí aparecieron una cabeza colosal de Júpiter y una máscara de Juno, hoy en Nápoles, junto a dos arcos honoríficos que todavía flanquean el templo. Fijaos en ese encuadre exacto con el volcán detrás: es la fotografía que nadie sabía, entonces, que sería una premonición.',
    ],
    lookFor: [
      'El podio elevado del templo, visible desde cualquier punto de la plaza del Foro.',
      'Los dos arcos honoríficos que flanquean el templo por los lados.',
      'El encuadre exacto del templo con el Vesubio detrás, desde el centro de la plaza.',
    ],
    tips: [
      'Se ve perfectamente desde el propio Foro sin necesidad de acercarse mucho: es buen momento para explicar el paso de Pompeya samnita a colonia romana.',
    ],
    image: { src: 'templo-jupiter', alt: 'El Templo de Júpiter en el extremo norte del Foro de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'templo-vespasiano',
    order: 5.2,
    name: 'Templo de Vespasiano',
    latinName: 'Tempio di Vespasiano',
    category: 'templo',
    coords: [40.74959, 14.48516],
    regio: 'VII.9.2',
    minutes: 6,
    intro: 'Acercaos al altar de mármol que hay frente a la escalinata: ahí está tallado, paso a paso, un sacrificio romano completo.',
    narration: [
      'Mirad el relieve despacio. Un sacerdote hace una libación sobre un trípode, hay una corona de encina y un toro conducido hacia el ritual, todo el atrezo de una ceremonia pública recogido en un único bloque de piedra. Es de las representaciones más completas que se conservan de cómo se sacrificaba de verdad en época romana.',
      'Lo que casi nadie nota es que al propio templo le faltan columnas y el revestimiento de mármol previsto: quedó sin terminar cuando llegó la erupción, diecisiete años después del terremoto que lo dejó en obras. Ni siquiera su dedicación es segura del todo, aunque la tradición lo llama de Vespasiano. Está a un paso del Edificio de Eumáquia, en pleno pórtico del Foro.',
    ],
    lookFor: [
      'El altar de mármol frente a la escalinata, con el relieve del sacrificio.',
      'La ausencia de columnas y de revestimiento de mármol, señal de una obra sin terminar.',
      'La posición del templo entre el Edificio de Eumáquia y el Santuario de los Lares Públicos.',
    ],
    tips: [
      'Se visita desde el pórtico del Foro; el interior suele estar acordonado, así que basta con observarlo desde una distancia corta.',
    ],
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'santuario-lares',
    order: 5.3,
    name: 'Santuario de los Lares Públicos',
    latinName: 'Santuario dei Lari Pubblici',
    category: 'templo',
    coords: [40.74975, 14.48502],
    regio: 'VII.9.3',
    minutes: 6,
    intro: 'Fijaos en el ábside del fondo, con sus tres nichos vacíos: este patio abierto era el santuario más grande de todo el Foro.',
    narration: [
      'Se levantó después del terremoto del año sesenta y dos para sustituir un santuario anterior, dedicado a los Lares Públicos, los dioses que protegían a la ciudad entera, igual que cada familia pompeyana veneraba a sus propios Lares en casa. Se descubrió en mil ochocientos diecisiete, y su patio, amplio como pocos en el Foro, terminaba en ese ábside con tres nichos para las estatuas de culto.',
      'Lo que nadie mira es que, igual que el vecino Templo de Vespasiano, se quedó sin terminar: sin el pórtico previsto, sin revestimiento de mármol y sin cubrirse del todo. Diecisiete años no bastaron para acabar la reconstrucción tras el terremoto. Queda entre el Macellum y el Templo de Vespasiano, buena señal de por dónde iba, muy despacio, la obra pública de Pompeya.',
    ],
    lookFor: [
      'El ábside al fondo del patio, con los tres nichos previstos para las estatuas de culto.',
      'La amplitud del patio abierto, mayor que la de cualquier otro santuario del Foro.',
      'Las señales de obra inacabada, sin pórtico ni revestimiento de mármol.',
    ],
    tips: [
      'Queda entre el Macellum y el Templo de Vespasiano; se ve bien desde el pórtico sin necesidad de entrar.',
    ],
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'arco-caligula',
    order: 7.1,
    name: 'Arco de Calígula',
    latinName: 'Arco di Caligola',
    category: 'calle',
    coords: [40.75075, 14.48418],
    minutes: 6,
    intro: 'Mirad ese único vano de ladrillo, desnudo de su mármol original: aquí empieza la Via di Mercurio, la calle que sube hacia las grandes casas de Pompeya.',
    narration: [
      'Bajo el arco apareció una estatua ecuestre de bronce, hoy muy fragmentada, y la tradición dice que representaba a Calígula a caballo, de ahí el nombre que le damos. Pero no todos están de acuerdo. La historiadora Katherine Welch propone que la estatua era en realidad de Marco Tulio, el mismo duunviro rico que pagó de su bolsillo el templo que tenéis justo enfrente.',
      'El detalle que nadie repara es que, fuera quien fuera el jinete, el arco no defendía nada: era una puerta simbólica, sin más función que separar el ruido comercial del Foro del barrio residencial más elegante de la ciudad. Un paso hacia el norte, y Pompeya cambia de registro por completo.',
    ],
    lookFor: [
      'El vano único de ladrillo, hoy desnudo del revestimiento de mármol que tuvo en origen.',
      'La posición exacta, marcando el inicio de la Via di Mercurio hacia el norte.',
      'La cercanía al Templo de la Fortuna Augusta, justo al otro lado del cruce.',
    ],
    tips: [
      'Es un buen punto de referencia para orientarse antes de subir hacia el barrio de las grandes domus de la Regio Sexta.',
    ],
    image: { src: 'arco-caligula', alt: 'El Arco de Calígula, junto al inicio de la Via di Mercurio', credit: 'Wikimedia Commons' },
    illus: 'calle',
    accessibility: 'facil',
  },
  {
    id: 'templo-fortuna-augusta',
    order: 7.2,
    name: 'Templo de la Fortuna Augusta',
    latinName: 'Tempio della Fortuna Augusta',
    category: 'templo',
    coords: [40.75068, 14.48435],
    regio: 'VII.4.1',
    minutes: 8,
    intro: 'Buscad la inscripción de la escalinata: en ella, un hombre llamado Marco Tulio presume, en piedra, de haber pagado este templo de su propio bolsillo.',
    narration: [
      'Poneos frente al podio y mirad el cruce que tenéis alrededor. La Via di Mercurio, la Via del Foro y la Via di Nola se juntan justo aquí, uno de los puntos con más tráfico de toda la ciudad, y el templo se levantó entre los años tres antes de nuestra era y dos después con el dinero de un solo duunviro, Marco Tulio, que lo dejó escrito sin ninguna modestia: lo construyó con dinero propio y en suelo propio.',
      'Lo que casi nadie busca es que, dentro, aparecieron estatuas de la diosa Fortuna, de la familia imperial y del propio Marco Tulio, hoy las tres en el museo de Nápoles: se aseguró de quedar retratado junto a los dioses y los emperadores que había honrado. Queda justo enfrente del Arco de Calígula, así que visitad los dos juntos.',
    ],
    lookFor: [
      'La posición del templo, exactamente en el cruce de tres calles principales.',
      'Los restos del podio y de la escalinata de acceso.',
      'La inscripción que recuerda que Marco Tulio pagó el templo de su propio bolsillo.',
    ],
    tips: [
      'Queda justo enfrente del Arco de Calígula: conviene visitarlos juntos, sin apenas desvío.',
    ],
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'casa-fontana-grande',
    order: 8.1,
    name: 'Casa de la Fuente Grande',
    latinName: 'Casa della Fontana Grande',
    category: 'domus',
    coords: [40.75114, 14.48363],
    regio: 'VI.8.22',
    minutes: 8,
    intro: 'Asomaos al jardín y buscad el pequeño templete cubierto de mosaico azul y verde: es la fuente que da nombre a toda la casa.',
    narration: [
      'Fijaos en las teselas diminutas de pasta vítrea y conchas, todavía vivas de color después de dos mil años bajo la ceniza. La casa se excavó en mil ochocientos veintiséis, y también se la conoce como Casa de Helvio Vestal, por un cartel electoral pintado en su fachada, hoy restaurada, sobre la propia Via di Mercurio.',
      'El detalle que casi nadie relaciona es que este tipo de fuente-ninfeo se puso de moda en las últimas décadas de Pompeya, sobre todo entre las casas de la Regio Sexta con dinero de sobra para el lujo decorativo. A pocos pasos, la Casa de la Fuente Pequeña presume de otra fuente casi igual de vistosa, aunque en formato más modesto.',
    ],
    lookFor: [
      'La fuente-templete cubierta de mosaico de pasta vítrea y conchas, pieza central del jardín.',
      'Los restos del cartel electoral pintado en la fachada que da nombre alternativo a la casa.',
      'La proximidad inmediata a la Casa de la Fuente Pequeña, con una fuente del mismo tipo.',
    ],
    tips: [
      'Su apertura no es constante; comprobad en la entrada del yacimiento si está incluida entre las domus visitables ese día.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-fontana-pequena',
    order: 8.2,
    name: 'Casa de la Fuente Pequeña',
    latinName: 'Casa della Fontana Piccola',
    category: 'domus',
    coords: [40.751391, 14.48365],
    regio: 'VI.8.23',
    minutes: 7,
    intro: 'Mirad la fuente de esta casa, más pequeña que la de su vecina, pero con un detalle que aquella no tiene: un niño de bronce abrazado a un ganso.',
    narration: [
      'La casa nació de la fusión de dos viviendas samnitas del siglo dos antes de nuestra era, reparadas tras el terremoto del año sesenta y dos, y se excavó en mil ochocientos veintisiete, pared con pared con la Casa de la Fuente Grande. Su fuente combina mosaico de vidrio coloreado con dos pequeñas esculturas, ese putto con el ganso y un pescador.',
      'Lo que nadie suele mirar es el techo protector que cubre los frescos de paisaje de una de las salas, instalado ya en el siglo diecinueve: fue una de las primeras medidas de conservación in situ de todo Pompeya. Tras una restauración de seis años, la casa reabrió en noviembre de dos mil veinticuatro, justo al lado de su hermana mayor.',
    ],
    lookFor: [
      'La fuente con el putto de bronce abrazado a un ganso y la figura del pescador.',
      'Los frescos de paisajes protegidos por una cubierta instalada ya en el siglo diecinueve.',
      'La diferencia de escala con la vecina Casa de la Fuente Grande.',
    ],
    tips: [
      'Reabrió a finales de dos mil veinticuatro tras una larga restauración; su horario de apertura puede variar, comprobadlo en taquilla.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-salustio',
    order: 8.3,
    name: 'Casa de Salustio',
    latinName: 'Casa di Sallustio',
    category: 'domus',
    coords: [40.7512, 14.48257],
    regio: 'VI.2.4',
    minutes: 8,
    intro: 'Mirad el atrio y fijaos en esos paneles que imitan mármol de colores: es estuco pintado, y de los más antiguos de toda Pompeya.',
    narration: [
      'El núcleo de la casa se remonta al siglo cuatro antes de nuestra era, con ampliaciones dos siglos después, y esa decoración de primer estilo es la fase más temprana de las cuatro que distinguimos en la pintura pompeyana. Un cartel electoral a favor de un tal Salustio, pintado en la fachada, le dio el nombre moderno, aunque otra inscripción la llama también Casa de Aulo Cosio Libano.',
      'Lo que casi nadie espera es que, con los siglos, parte de esta casa tan antigua acabó convertida en posada con panadería y termopolio propio: hasta las viviendas más venerables cambiaban de oficio en Pompeya. Un fresco con Diana y Acteón se perdió en el bombardeo aliado de mil novecientos cuarenta y tres y se restauró en mil novecientos setenta, casi como la propia casa.',
    ],
    lookFor: [
      'Los restos de decoración de primer estilo en el atrio, la fase más antigua de la pintura pompeyana.',
      'Los ambientes reconvertidos en posada y termopolio en época tardía.',
      'Los carteles electorales pintados en la fachada que dan nombre a la casa.',
    ],
    tips: [
      'Su apertura suele ser restringida; conviene preguntar en taquilla antes de desviarse hacia ella.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-cirujano',
    order: 8.4,
    name: 'Casa del Cirujano',
    latinName: 'Casa del Chirurgo',
    category: 'domus',
    coords: [40.7516, 14.4819],
    regio: 'VI.1.9',
    minutes: 8,
    intro: 'Tocad con la mirada esa fachada de sillares bien escuadrados, sobre la Via Consolare: es de las construcciones más antiguas que vais a ver hoy.',
    narration: [
      'Ese aparejo en opus quadratum, de piedra caliza del Sarno, se remonta a alrededor del año doscientos antes de nuestra era, y Francesco La Vega ya la excavó en mil setecientos setenta. Una moneda hallada bajo el pavimento del atrio en mil novecientos veintiséis, acuñada entre los años doscientos catorce y doscientos doce antes de Cristo, confirmó esa fecha tan temprana.',
      'El hallazgo que le da nombre llegó en mil setecientos setenta y uno: unos cuarenta instrumentos quirúrgicos de bronce, escalpelos, fórceps y sondas, hoy en Nápoles, uno de los conjuntos de instrumental médico romano más completos que existen. Se cree que aquí vivió o trabajó un médico, aunque nadie sabe todavía su nombre. La calle de fuera lleva directa hacia la Porta Ercolano.',
    ],
    lookFor: [
      'La fachada de sillares de piedra caliza en opus quadratum, de una de las fases constructivas más antiguas del yacimiento.',
      'La planta de atrio toscano típica de las casas pompeyanas más tempranas.',
      'La cercanía a la Via Consolare, la calle que llevaba directamente hacia la Porta Ercolano.',
    ],
    tips: [
      'Su interior no siempre está abierto; el exterior se puede apreciar bien desde la Via Consolare, en el recorrido habitual hacia la Porta Ercolano.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-pansa',
    order: 8.5,
    name: 'Casa de Pansa',
    latinName: 'Casa di Pansa',
    category: 'domus',
    coords: [40.75056, 14.48407],
    regio: 'VI.6.1',
    minutes: 9,
    intro: 'Rodead esta manzana entera con la mirada: toda ella, tiendas incluidas, era una sola casa.',
    narration: [
      'En el centro vivía la familia; alrededor, de cara a la calle, había tiendas y apartamentos de alquiler que sacaban rendimiento al resto del solar. Su origen es samnita, y la planta, con atrio toscano y un peristilo de dieciséis columnas, ha salido durante generaciones en los libros de arquitectura como el ejemplo perfecto de domus romana, el que dibujan los estudiantes cuando les piden imaginar una casa pompeyana.',
      'El detalle que casi nadie relaciona es el nombre: viene de un cartel de alquiler pintado en la fachada a nombre de Cneo Alleyo Nigidio Mayo, un personaje rico que también aparece en carteles electorales de otras zonas de la ciudad. La excavación no se dio por terminada hasta mil novecientos cuarenta y tres, casi ciento treinta años después de empezar. Estáis en pleno corazón de la Regio Sexta, a un paso de la Casa del Fauno.',
    ],
    lookFor: [
      'La distribución en torno a la insula completa, con tiendas y apartamentos alquilados alrededor de la vivienda principal.',
      'El atrio toscano y el gran peristilo de dieciséis columnas.',
      'El cartel de alquiler pintado que da nombre a la casa.',
    ],
    tips: [
      'Suele figurar entre las domus abiertas al público de forma habitual; es una buena parada para explicar la planta clásica de una domus romana.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-apolo',
    order: 8.6,
    name: 'Casa de Apolo',
    latinName: 'Casa di Apollo',
    category: 'domus',
    coords: [40.7511, 14.4832],
    regio: 'VI.7.23',
    minutes: 7,
    intro: 'Buscad, en el atrio, los restos fragmentarios de un fresco de Apolo: apenas queda nada, y aun así le dio nombre a toda la casa.',
    narration: [
      'La vivienda se excavó en la década de mil ochocientos treinta, y ese mismo mes de marzo apareció un sello de bronce con el nombre de Aulo Herennuleyo Comune, el propietario más probable en sus últimos años. Un objeto tan pequeño, y aun así basta para ponerle nombre y apellido a una casa entera.',
      'Lo que casi nadie mira es el nicho-fuente del jardín, con mosaico y estatuillas, muy parecido al de otras casas de esta misma manzana que competían por el rincón de agua más vistoso. La decoración combina tercer y cuarto estilo, señal de que la casa se remodeló al menos una vez antes del final. Estáis muy cerca de la Casa del Fauno, en el mismo barrio de las grandes domus.',
    ],
    lookFor: [
      'Los restos de los frescos de Apolo que dan nombre a la casa, en el área del atrio.',
      'El nicho-fuente decorado con mosaico y estatuillas en el jardín.',
      'La combinación de tercer y cuarto estilo en la decoración pictórica conservada.',
    ],
    tips: [
      'No suele estar entre las casas abiertas de forma regular; preguntad en taquilla si hay visita puntual programada.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-dioscuros',
    order: 9.1,
    name: 'Casa de los Dioscuros',
    latinName: 'Casa dei Dioscuri',
    category: 'domus',
    coords: [40.751781, 14.483828],
    regio: 'VI.9.6',
    minutes: 9,
    intro: 'Contad los atrios de esta casa: son dos, uno de ellos con columnas corintias, algo que solo existe en cuatro viviendas de toda Pompeya.',
    narration: [
      'Descubierta entre mil ochocientos veintiocho y mil ochocientos veintinueve, la casa conecta esos dos atrios con un peristilo de tipo rodio, con columnas más altas en un lado para dejar entrar más luz sobre un estanque central. Los frescos de cuarto estilo, con Adonis, Escila y Apolo persiguiendo a Dafne, salieron del mismo taller de pintores que trabajaría poco después en la Casa de los Vettii, y se nota en el color y en el trazo de las figuras.',
      'El detalle que casi nadie relaciona es que el cuadro que da nombre a la casa, con los Dioscuros Cástor y Pólux a la entrada, hace tiempo que vive en el museo de Nápoles: solo queda aquí el hueco donde colgaba. La Casa de los Vettii, con la firma del mismo pintor, os espera un poco más adelante en la ruta.',
    ],
    lookFor: [
      'El doble atrio, uno de ellos de orden corintio, una rareza entre las casas pompeyanas.',
      'El peristilo de tipo rodio, con columnas de distinta altura para regular la luz.',
      'Las escenas de cuarto estilo con Adonis, Escila y Apolo y Dafne.',
    ],
    tips: [
      'Reabrió al público en noviembre de dos mil veintidós tras una restauración; su horario puede seguir siendo rotativo.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-meleagro',
    order: 9.2,
    name: 'Casa de Meleagro',
    latinName: 'Casa di Meleagro',
    category: 'domus',
    coords: [40.7515, 14.4835],
    regio: 'VI.9.2',
    minutes: 8,
    intro: 'Caminad hasta el fondo de la casa y mirad el peristilo: ese jardín con estanque es mucho más grande de lo que suele caber en una domus pompeyana.',
    narration: [
      'Se pensó así a propósito, para impresionar a las visitas antes de que se sentaran a cenar. La casa se descubrió en mil ochocientos veintinueve, se reexcavó en mil ochocientos treinta y seis y de nuevo en mil novecientos sesenta y seis, y conserva decoración de primero, tercero y cuarto estilo, señal de que se habitó y se remodeló durante varios siglos.',
      'El fresco que le da nombre, con Meleagro y Atalanta cazando el jabalí de Calidón, ya no está aquí, sino en el museo de Nápoles, junto con buena parte de su mejor decoración. Lo que queda, ese peristilo desmesurado, es igual de elocuente. Comparte manzana con la Casa de los Dioscuros, apenas unos pasos más allá.',
    ],
    lookFor: [
      'El amplio peristilo columnado con estanque, uno de los más generosos de la Regio Sexta.',
      'Los restos de decoración de distintos estilos pictóricos, señal de sucesivas reformas.',
      'La cercanía inmediata a la Casa de los Dioscuros, con la que comparte manzana.',
    ],
    tips: [
      'Suele estar cerrada al público de forma habitual; comprobad en taquilla si hay apertura puntual.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-laberinto',
    order: 9.3,
    name: 'Casa del Laberinto',
    latinName: 'Casa del Labirinto',
    category: 'domus',
    coords: [40.75183, 14.48436],
    regio: 'VI.11.9',
    minutes: 9,
    intro: 'Buscad en el suelo del oecus norte un mosaico diminuto: Teseo enfrentándose al Minotauro dentro de un laberinto de líneas geométricas.',
    narration: [
      'Es la representación más antigua conocida de ese motivo en todo el mundo romano, y está aquí, bajo vuestros pies, sin ningún cartel que le haga justicia. La casa, de origen samnita, se reconstruyó después del asedio de Sila del año ochenta y nueve antes de nuestra era, cuando este sector de la muralla sufrió graves daños; perteneció a la familia de los Sextilios y se excavó en mil ochocientos treinta y cuatro.',
      'Lo que casi nadie busca es el segundo atrio, tetrástilo, con cuatro columnas sosteniendo la cubierta abierta al cielo, y unas termas privadas, un lujo que solo podían pagarse las familias más acomodadas. Las pinturas de segundo estilo que quedan en el resto de la casa son mucho más discretas que ese pequeño laberinto del suelo.',
    ],
    lookFor: [
      'El mosaico de Teseo y el Minotauro en el laberinto, en el oecus norte de la casa.',
      'El doble atrio, uno de ellos tetrástilo con cuatro columnas.',
      'Los restos de las termas privadas de la vivienda.',
    ],
    tips: [
      'Su apertura es ocasional; preguntad en taquilla antes de desviaros hacia ella.',
    ],
    illus: 'mosaico',
    accessibility: 'medio',
  },
  {
    id: 'casa-amorini-dorados',
    order: 9.4,
    name: 'Casa de los Amorcillos Dorados',
    latinName: 'Casa degli Amorini Dorati',
    category: 'domus',
    coords: [40.75228, 14.48503],
    regio: 'VI.16.7',
    minutes: 9,
    intro: 'Mirad hacia el peristilo, entre las columnas: esas máscaras de mármol colgadas se llaman oscilla, y se mecían con el viento como adorno de buena suerte.',
    narration: [
      'La casa perteneció, según la tradición, a la familia de los Popeos, quizá emparentada con la propia Popea Sabina, segunda esposa del emperador Nerón. Se excavó entre mil novecientos tres y mil novecientos cinco, y se restauró de nuevo entre dos mil quince y dos mil dieciséis, recuperando buena parte de su color original.',
      'El detalle que le da nombre son unos discos diminutos de vidrio con amorcillos recubiertos de pan de oro, hallados en un cubículo, junto a frescos de Paris y Helena y de Aquiles y Patroclo. El larario está dedicado a Isis, Serapis, Anubis y Harpócrates, prueba del gusto por lo egipcio que cundió entre las familias más ricas en las últimas décadas de la ciudad, el mismo gusto que veremos también junto al Templo de Isis.',
    ],
    lookFor: [
      'Los discos de vidrio con amorcillos dorados que dan nombre a la casa.',
      'El larario dedicado a Isis, Serapis, Anubis y Harpócrates.',
      'Las máscaras de mármol y los oscilla colgados entre las columnas del peristilo.',
    ],
    tips: [
      'Ha sido restaurada recientemente; su apertura puede seguir siendo rotativa, conviene comprobarlo en taquilla.',
    ],
    illus: 'fresco',
    accessibility: 'medio',
  },
  {
    id: 'casa-ancla',
    order: 9.5,
    name: 'Casa del Ancla',
    latinName: "Casa dell'Ancora Nera",
    category: 'domus',
    coords: [40.7517, 14.4839],
    regio: 'VI.10.7',
    minutes: 7,
    intro: 'Mirad al suelo nada más entrar: un ancla negra en mosaico, un motivo que casi ningún vestíbulo pompeyano se atrevió a usar.',
    narration: [
      'De ahí el nombre moderno de la casa, excavada entre mil ochocientos veintiséis y mil ochocientos veintisiete, con fases decorativas que van del primer estilo, del siglo dos antes de nuestra era, hasta el cuarto estilo posterior al terremoto del año sesenta y dos. Bajad unos escalones y encontraréis lo más singular de la vivienda, un jardín hundido con criptopórtico y nichos decorativos, una solución que apenas se repite en el resto de la ciudad.',
      'El detalle que nadie mira es la base de lava volcánica del atrio, donde se asentaba un arca fuerte: el mueble donde una familia pompeyana guardaba su dinero a la vista de cualquier visita, como quien no tiene nada que ocultar de su propia riqueza.',
    ],
    lookFor: [
      'El mosaico del ancla negra en el vestíbulo de entrada.',
      'El jardín hundido con criptopórtico, una solución poco frecuente en Pompeya.',
      'La base de lava del arca fuerte conservada en el atrio.',
    ],
    tips: [
      'No suele estar abierta de forma regular; es una parada opcional si el yacimiento anuncia visita puntual.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-leda',
    order: 10.1,
    name: 'Casa de Leda',
    latinName: 'Casa di Leda e il Cigno',
    category: 'domus',
    coords: [40.75294, 14.48473],
    regio: 'V.6.12',
    minutes: 7,
    intro: 'Fijaos en los andamios y las protecciones que todavía rodean esta zona: la casa de Leda lleva excavada solo unos años.',
    narration: [
      'Salió a la luz en noviembre de dos mil dieciocho, durante los trabajos de contención de taludes del Gran Proyecto Pompeya en la Regio Quinta, uno de los sectores del yacimiento explorados más recientemente. Las campañas siguientes, entre dos mil diecinueve y dos mil veinticuatro, fueron sacando a la luz estancias contiguas y casas vecinas en el mismo bloque.',
      'Junto a las fauces de entrada, en un cubículo pequeño, apareció un fresco de cuarto estilo con Leda y el cisne, el mito de Zeus convertido en ave para seducir a la reina de Esparta, en un estado de conservación que sorprende para un hallazgo tan reciente. Buena parte de esta regio seguía bajo tierra hace apenas unos años, así que preguntad si aún hay novedades cuando lleguéis a las Termas Estabianas.',
    ],
    lookFor: [
      'El fresco de Leda y el cisne, en el cubículo junto a la entrada.',
      'El aspecto todavía muy reciente de la excavación, con andamios y protecciones visibles en la zona.',
      'Las viviendas vecinas descubiertas en las mismas campañas de los Nuovi Scavi.',
    ],
    tips: [
      'Pertenece a los Nuovi Scavi de la Regio Quinta, un área de excavación en curso: no es visitable de forma estándar y solo se abre en visitas guiadas o jornadas especiales.',
    ],
    illus: 'fresco',
    accessibility: 'medio',
  },
  {
    id: 'termopolio-regio-v',
    order: 10.2,
    name: 'Termopolio de la Regio Quinta',
    latinName: 'Termopolio della Regio V',
    category: 'comercio',
    coords: [40.752136, 14.486357],
    regio: 'V.2.B',
    minutes: 8,
    intro: 'Mirad el mostrador, con su pintura casi intacta: una nereida sobre un caballo marino, patos, un gallo y un perro atado con correa.',
    narration: [
      'Es probable que anunciaran, sin necesidad de palabras, parte de lo que se servía dentro. El termopolio se excavó por completo entre dos mil diecinueve y dos mil veinte, y el anuncio oficial del hallazgo, a finales de diciembre de dos mil veinte, fue una de las noticias arqueológicas más comentadas de aquel año. Dentro de los dolia empotrados en el mostrador aparecieron restos de pescado, caracoles y carne de cerdo.',
      'El detalle que se os puede escapar es que junto al mostrador se halló también el esqueleto completo de un perro pequeño, seguramente el guardián o la mascota del local en el momento de la erupción. Un puesto de comida rápida así, con su fogón y sus dolia, es justo lo que necesitáis para imaginar lo que fueron los termopolios que ya habéis visto en la Via dell\'Abbondanza.',
    ],
    lookFor: [
      'La pintura original del mostrador, con la nereida, los patos, el gallo y el perro.',
      'Los dolia empotrados donde se guardaba y se servía la comida.',
      'El lugar donde apareció el esqueleto del pequeño perro guardián del local.',
    ],
    tips: [
      'En el recorrido habitual solo se ve desde el exterior; el interior se ha abierto por completo únicamente en jornadas extraordinarias, como en agosto de dos mil veintiuno.',
    ],
    image: { src: 'termopolio-regio-v', alt: 'Mostrador pintado del termopolio excavado en la Regio Quinta de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'termopolio',
    accessibility: 'medio',
  },
  {
    id: 'casa-bodas-plata',
    order: 10.3,
    name: 'Casa de las Bodas de Plata',
    latinName: "Casa delle Nozze d'Argento",
    category: 'domus',
    coords: [40.752513, 14.486548],
    regio: 'V.2.i',
    minutes: 8,
    intro: 'Contad las columnas de este atrio tetrástilo: son de toba, y sostienen uno de los espacios más grandes que se conservan en toda Pompeya.',
    narration: [
      'La casa se construyó a finales del siglo dos antes de nuestra era, en plena época samnita, y se remodeló ya bajo Augusto, con un peristilo de estilo rodio completando el conjunto. Su propietario sigue sin conocerse con seguridad, aunque algunas atribuciones apuntan a un tal Lucio Albucio Celso, sin que haya prueba definitiva.',
      'Lo que casi nadie relaciona es el propio nombre de la casa: se excavó en mil ochocientos noventa y tres, justo el año en que Umberto primero de Italia y Margarita de Saboya celebraban sus bodas de plata, y los arqueólogos decidieron honrarlos así, una costumbre habitual en la Pompeya decimonónica de dedicar los hallazgos a la actualidad de la corte.',
    ],
    lookFor: [
      'El atrio tetrástilo corintio, uno de los mayores conservados en Pompeya.',
      'El peristilo de estilo rodio, con columnas de distinta altura.',
      'El curioso origen de su nombre, ligado a un aniversario real de mil ochocientos noventa y tres.',
    ],
    tips: [
      'Reabrió tras una restauración en julio de dos mil veintitrés; suele estar entre las domus visitables de la zona.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-marco-lucrecio-fronton',
    order: 10.4,
    name: 'Casa de Marco Lucrecio Fronto',
    latinName: 'Casa di Marco Lucrezio Frontone',
    category: 'domus',
    coords: [40.752882, 14.487941],
    regio: 'V.4.a',
    minutes: 9,
    intro: 'Leed, si podéis, los restos de los carteles electorales de la fachada: ahí está escrito, con una seguridad poco frecuente, el nombre del dueño de esta casa.',
    narration: [
      'Se llamaba Marco Lucrecio Fronto, un magistrado local, y su tablino conserva frescos de tercer y cuarto estilo con Marte y Venus, con Narciso y con una escena menos conocida, Pero amamantando en la cárcel a su padre Micón, un episodio clásico de piedad filial que la pintura romana repitió muchas veces. La casa, construida en el siglo dos antes de nuestra era y ampliada bajo Augusto, seguía en obras de reconstrucción cuando llegó la erupción.',
      'En una de las estancias se hallaron los restos de ocho víctimas, cinco adultos y tres niños, que buscaron refugio sin conseguirlo. Reabierta tras una restauración entre dos mil doce y dos mil catorce, esta casa está muy cerca de donde la ruta clásica cruza la Via Stabiana hacia las Termas Estabianas.',
    ],
    lookFor: [
      'Los carteles electorales de la fachada que identifican al propietario de la casa.',
      'Los frescos del tablino, con Marte y Venus, Narciso, y Pero y Micón.',
      'La sala donde se hallaron los restos de ocho víctimas de la erupción.',
    ],
    tips: [
      'Reabierta tras una restauración entre dos mil doce y dos mil catorce, suele estar entre las casas abiertas de forma habitual de esta manzana.',
    ],
    illus: 'fresco',
    accessibility: 'medio',
  },
  {
    id: 'casa-caza-antigua',
    order: 10.5,
    name: 'Casa de la Caza Antigua',
    latinName: 'Casa della Caccia Antica',
    category: 'domus',
    coords: [40.75105, 14.486],
    regio: 'VII.4.48',
    minutes: 7,
    intro: 'Al fondo del peristilo, mirad ese fresco de caza: leones, jabalíes y osos persiguiéndose entre la vegetación pintada.',
    narration: [
      'Es un tema que gustaba mucho en las casas pompeyanas de gusto refinado, y de ahí el nombre de esta vivienda, la Caza Antigua, para distinguirla de otra casa de la ciudad con un motivo parecido pero más tardío, la Caza Nueva. Se excavó entre mil ochocientos treinta y cuatro y mil ochocientos treinta y cinco, y sigue el esquema clásico de atrio y peristilo de cualquier domus pompeyana de tamaño medio.',
      'Lo que casi nadie relaciona son las pinturas de cuarto estilo del resto de las salas, con Leda, Dánae y Diana, todas protagonistas de episodios de seducción divina que la pintura de la época repitió sin cansarse. Está a un paso de donde la ruta clásica pasa junto al Templo de Isis.',
    ],
    lookFor: [
      'El fresco de caza con leones, jabalíes y osos en el fondo del peristilo.',
      'Las escenas mitológicas de cuarto estilo con Leda, Dánae y Diana.',
      'La planta de atrio y peristilo, representativa de una domus pompeyana de tamaño medio.',
    ],
    tips: [
      'Su apertura no está garantizada todos los días; conviene confirmarlo en taquilla.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'torre-mercurio',
    order: 10.6,
    name: 'Torre de Mercurio',
    latinName: 'Torre di Mercurio',
    category: 'servicio',
    coords: [40.75276, 14.48286],
    minutes: 8,
    intro: 'Subid la mirada hacia esta torre y luego girad hacia el sur: toda la Via di Mercurio se alinea, recta, hasta el Foro.',
    narration: [
      'Es la torre número once de las que jalonaban la muralla, construida entre los siglos dos y uno antes de nuestra era, justo donde arranca la calle que le da nombre moderno. Junto con el tramo vecino, ha sido restaurada recientemente con fondos europeos, que han consolidado la toba original y recuperado buena parte de la fábrica de piedra.',
      'El detalle que casi nadie sube a comprobar es la vista desde lo alto: el Vesubio, el mar y el valle del Sarno como telón de fondo de toda la calle. El acceso al paso de ronda suele reservarse a grupos reducidos por conservación, así que preguntad antes de subir. Desde aquí hasta el Arco de Calígula, ya no hay más que bajar.',
    ],
    lookFor: [
      'La vista axial sobre toda la Via di Mercurio, con el Foro al fondo.',
      'La fábrica de piedra toba, recientemente consolidada en una restauración con fondos europeos.',
      'El tramo de muralla adyacente, con otras torres defensivas visibles a ambos lados.',
    ],
    tips: [
      'El acceso al paso de ronda superior suele limitarse a grupos reducidos por conservación; comprobad su disponibilidad el día de la visita.',
    ],
    illus: 'calle',
    accessibility: 'dificil',
  },
  {
    id: 'castellum-aquae',
    order: 10.7,
    name: 'Castellum Aquae',
    latinName: 'Castellum Aquae',
    category: 'servicio',
    coords: [40.75322, 14.484164],
    minutes: 7,
    intro: 'Mirad esta cuenca circular de piedra: por aquí entraba toda el agua que bebía Pompeya, antes de repartirse calle a calle.',
    narration: [
      'El edificio se construyó bajo Augusto, a finales del siglo primero antes de nuestra era, como punto final del ramal del acueducto del Serino, situado a propósito en el lugar más alto de la ciudad, a unos cuarenta y dos metros sobre el mar, para que el agua bajara después por gravedad. Se excavó en mil novecientos dos, y la cuenca, en opus reticulatum, todavía conserva la rejilla y los tres conductos de salida.',
      'Lo que casi nadie sabe es que el reparto no era igual para todos: las fuentes públicas tenían prioridad absoluta, y si escaseaba el agua, se cerraba antes el grifo a las termas y a las casas ricas que a cualquier vecino con un cántaro. Tras el terremoto del año sesenta y dos, no está claro si volvió a funcionar del todo antes de la erupción. Queda junto a la Porta Vesuvio, en el punto más alto de todo el recorrido.',
    ],
    lookFor: [
      'La cuenca circular de distribución, construida en opus reticulatum.',
      'Los tres conductos de salida que repartían el agua hacia distintos puntos de la ciudad.',
      'La posición en el punto más alto de Pompeya, junto a la Porta Vesuvio.',
    ],
    tips: [
      'Su visita suele depender de la disponibilidad de personal del parque; preguntad en taquilla si es accesible ese día.',
    ],
    illus: 'calle',
    accessibility: 'medio',
  },
  {
    id: 'porta-vesuvio',
    order: 10.8,
    name: 'Porta Vesuvio',
    latinName: 'Porta Vesuvio',
    category: 'puerta',
    coords: [40.75338, 14.484099],
    minutes: 6,
    intro: 'Fijaos en los muros de esta puerta, la que miraba de frente al volcán: todavía se distinguen ahí los golpes de un asedio anterior a la propia erupción.',
    narration: [
      'Son impactos de proyectiles del asedio de Sila, del año ochenta y nueve antes de Cristo, cuando Pompeya, aliada de otros pueblos itálicos, resistió aquí el ataque de las legiones romanas durante la guerra social. La puerta se construyó por fases desde finales del siglo tres antes de nuestra era, con una última reconstrucción que seguía en marcha cuando llegó la erupción, y se excavó en mil ochocientos once y de nuevo en mil novecientos cinco.',
      'Lo que casi nadie mira es el pequeño larario de al lado, con dos altares y frescos dedicados a los Lares. Un poco más allá arranca la necrópolis, con la tumba del edil Vestorio Prisco, muerto hacia los años setenta y cinco o setenta y seis, pocos años antes de que el volcán que miraba de frente sepultara la ciudad entera.',
    ],
    lookFor: [
      'Las marcas de impactos de proyectiles del asedio de Sila, visibles en algunos tramos de muro.',
      'El pequeño larario con frescos junto a la puerta.',
      'El inicio de la necrópolis exterior, con la tumba del edil Vestorio Prisco.',
    ],
    tips: [
      'No funciona como acceso habitual de visitantes; se contempla desde dentro de la muralla, como parte del paseo hacia la zona norte del yacimiento.',
    ],
    illus: 'calle',
    accessibility: 'medio',
  },
  {
    id: 'panaderia-popidio-prisco',
    order: 11.1,
    name: 'Panadería de Popidio Prisco',
    latinName: 'Panificio di N. Popidio Prisco',
    category: 'comercio',
    coords: [40.750881, 14.485712],
    regio: 'VII.2.22',
    minutes: 7,
    intro: 'Contad los molinos de piedra alineados en este patio: son cinco, y cada uno tenía que girarlo un burro o un esclavo, sin descanso, para moler el grano de toda una calle.',
    narration: [
      'Esta panadería del Vicolo Storto perteneció a Numerio Popidio Prisco, cuyo nombre aparece en las inscripciones del local, y conserva un horno de ladrillo en muy buen estado además de esos cinco molinos, cada uno formado por dos piezas superpuestas, la meta fija abajo y el catillus giratorio encima. Pompeya llegó a tener unas treinta y cinco panaderías documentadas, y esta es de las que mejor conservan el conjunto completo de su producción.',
      'Lo que casi nadie relaciona es que, a diferencia de otras panaderías de la ciudad, esta no tiene mostrador a la calle: repartía pan al por mayor, a otros comercios y a domus particulares, en lugar de vender de puerta en puerta. Es una parada corta y muy visual antes de seguir hacia la Porta Stabia.',
    ],
    lookFor: [
      'El horno de ladrillo, muy bien conservado, en el fondo del local.',
      'Los cinco molinos de piedra volcánica, con sus piezas meta y catillus superpuestas.',
      'La ausencia de mostrador, indicio de que la panadería vendía sobre todo al por mayor.',
    ],
    tips: [
      'Suele estar abierta en horario amplio, de nueve de la mañana a siete de la tarde; es una parada corta y muy visual para explicar la alimentación cotidiana en Pompeya.',
    ],
    image: { src: 'panaderia-horno', alt: 'Horno de ladrillo y molinos de una panadería romana en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'pan',
    accessibility: 'medio',
  },
  {
    id: 'porta-stabia',
    order: 11.2,
    name: 'Porta Stabia',
    latinName: 'Porta di Stabia',
    category: 'puerta',
    coords: [40.748328, 14.489955],
    minutes: 6,
    intro: 'Poneos bajo el arco y mirad hacia el norte: toda la Via Stabiana, la arteria que cruza Pompeya de punta a punta, arranca justo aquí.',
    narration: [
      'Es la puerta más antigua que se conserva en pie, descubierta en mil ochocientos cincuenta y uno y acondicionada para la visita en mil novecientos siete y mil novecientos ocho. Está construida en opus incertum de toba, con un enlucido de primer estilo todavía visible en algunos tramos, y conserva una inscripción en lengua osca sobre obras viales anteriores a la romanización de la ciudad.',
      'Junto a ella hay una fuente pública con un relieve decorativo, uno de tantos surtidores que jalonaban las calles pompeyanas, y fuera de la muralla se extiende una necrópolis todavía en estudio, investigada junto con la Universidad de Cincinnati. Si hacéis el recorrido en sentido inverso, esta es vuestra puerta de entrada hacia las Termas Estabianas.',
    ],
    lookFor: [
      'El aparejo de opus incertum de toba, con restos de enlucido de primer estilo.',
      'La inscripción en lengua osca relativa a obras viales anteriores a la colonia romana.',
      'La fuente pública junto a la puerta, con su relieve decorativo.',
    ],
    tips: [
      'Marca el arranque sur de la Via Stabiana; es un buen punto de referencia si el recorrido se hace también en sentido inverso, de sur a norte.',
    ],
    image: { src: 'via-stabiana-adoquines', alt: 'La Via Stabiana con la Porta di Stabia al fondo', credit: 'Wikimedia Commons' },
    illus: 'calle',
    accessibility: 'medio',
  },
  {
    id: 'casa-sirico',
    order: 11.3,
    name: 'Casa de Sirico',
    latinName: 'Casa di Sirico',
    category: 'domus',
    coords: [40.75054, 14.487356],
    regio: 'VII.1.47',
    minutes: 8,
    intro: 'Leed el mosaico del umbral antes de entrar: salve lucru, bienvenido, beneficio, la frase que mejor resume cómo pensaba esta ciudad de comerciantes.',
    narration: [
      'La casa perteneció a Publio Vedio Siricio, cuyo nombre aparece en un sello de bronce hallado en la excavación, en sociedad con otro personaje llamado Vedio Numiano. Nació de la fusión de dos viviendas anteriores, se excavó entre mil ochocientos cincuenta y uno y mil ochocientos setenta y tres, y es una de las mansiones más completas de toda la Regio Séptima.',
      'Lo que casi nadie relaciona es la calidad de los frescos de una de sus exedras: Eneas curado por el médico Yapix, Hércules ebrio y Tetis en la fragua de Vulcano, escenas mitológicas de un taller que sabía lo que hacía. Salve lucru resume al propietario mejor que cualquier inscripción funeraria.',
    ],
    lookFor: [
      'El mosaico del umbral con la inscripción salve lucru.',
      'Los frescos de la exedra, con Eneas, Hércules y Tetis en la fragua de Vulcano.',
      'Las huellas de la fusión de dos viviendas anteriores en una sola casa mayor.',
    ],
    tips: [
      'Su apertura no está garantizada todos los días; conviene confirmarlo en taquilla antes de acercarse.',
    ],
    illus: 'fresco',
    accessibility: 'medio',
  },
  {
    id: 'termas-centrales',
    order: 12.1,
    name: 'Termas Centrales',
    latinName: 'Terme Centrali',
    category: 'termas',
    coords: [40.75156, 14.48677],
    regio: 'IX.4',
    minutes: 10,
    intro: 'Mirad esos capiteles a medio tallar: es la mejor fotografía que existe de una obra pública interrumpida en seco por la erupción.',
    narration: [
      'Estas termas se empezaron a construir después del terremoto del año sesenta y dos, ocupando una insula entera de la Regio Novena, casi tres mil setecientos metros cuadrados que las convierten en el complejo termal más grande y más moderno de la ciudad. Grandes ventanales orientados al sur, una novedad frente a las termas más antiguas y oscuras, anunciaban un concepto de baño mucho más luminoso.',
      'El detalle que casi nadie nota es que, a diferencia de las Termas del Foro o las Estabianas que ya conocéis, aquí no hay sección separada para mujeres, quizá porque el proyecto preveía turnos distintos según la hora del día. Diecisiete años no bastaron para acabar la obra: comparad esta ambición inacabada con la solidez ya vieja de las Termas del Foro.',
    ],
    lookFor: [
      'Los capiteles de columnas dejados a medio tallar, prueba de la obra interrumpida.',
      'Los grandes ventanales orientados al sur, novedad frente a las termas más antiguas.',
      'La escala del conjunto, que ocupa una insula entera de la Regio Novena.',
    ],
    tips: [
      'Es un buen contraste con las Termas del Foro y las Estabianas, ya visitadas, para explicar cómo evolucionaba la arquitectura termal pompeyana.',
    ],
    illus: 'termas',
    accessibility: 'medio',
  },
  {
    id: 'casa-citarista',
    order: 12.2,
    name: 'Casa del Citarista',
    latinName: 'Casa del Citarista',
    category: 'domus',
    coords: [40.749891, 14.488763],
    regio: 'I.4.5',
    minutes: 10,
    intro: 'Imaginad, en el peristilo que pisáis, una estatua de bronce de Apolo tocando la cítara: de ahí sale el nombre de esta casa inmensa.',
    narration: [
      'De origen samnita, en el siglo tres antes de nuestra era, la vivienda llegó a fusionar al menos dos casas distintas después del terremoto del año sesenta y dos, hasta unos dos mil setecientos metros cuadrados, una de las mayores superficies habitadas de toda la ciudad. Se excavó entre mil ochocientos cincuenta y tres y mil ochocientos sesenta y uno, con ampliaciones posteriores en mil ochocientos sesenta y ocho, mil ochocientos setenta y dos y mil novecientos veintinueve.',
      'Lo que casi nadie sabe es que junto al Apolo Citaredo, hoy en Nápoles, apareció también un curioso grupo escultórico de serpiente, perros, jabalí, león y ciervo, y frescos de Marte y Venus atribuidos tentativamente a la familia de los Popidios. Reabierta en junio de dos mil veintiséis, con visitas guiadas los miércoles dentro del proyecto Parvula Domus.',
    ],
    lookFor: [
      'El peristilo donde apareció la estatua de bronce de Apolo Citaredo.',
      'La escala del conjunto, resultado de fusionar al menos dos casas distintas.',
      'Los restos de las sucesivas campañas de excavación, visibles en las distintas zonas de la vivienda.',
    ],
    tips: [
      'Reabierta en dos mil veintiséis tras una restauración, con visitas guiadas adicionales los miércoles; comprobad el horario concreto del día.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-centenario',
    order: 12.3,
    name: 'Casa del Centenario',
    latinName: 'Casa del Centenario',
    category: 'domus',
    coords: [40.751843, 14.488034],
    regio: 'IX.8.3',
    minutes: 9,
    intro: 'Buscad en el larario un fresco con Baco cubierto de racimos junto a una montaña de un solo pico: es el Vesubio más antiguo que conocemos, pintado por alguien que no sabía que era un volcán.',
    narration: [
      'La montaña aparece cubierta de viñedos, verde y tranquila, sin ningún indicio de la furia que llegaría después. La casa se excavó en mil ochocientos setenta y nueve, coincidiendo con el decimoctavo centenario de la erupción, de ahí su nombre moderno, y se construyó hacia mediados del siglo dos antes de nuestra era; su propietario en el momento final sigue sin identificarse con seguridad.',
      'El detalle que casi nadie busca es la panadería integrada en la propia vivienda, junto a un ninfeo decorado y un fresco erótico en una de las estancias privadas. Pocas imágenes explican mejor por qué nadie en Pompeya temía a su montaña como cuando veis este fresco antes de subir hacia la Via Stabiana.',
    ],
    lookFor: [
      'El fresco del larario con Baco y el Vesubio de un solo pico, la representación más antigua conocida del volcán.',
      'Los restos del ninfeo decorado de la vivienda.',
      'La panadería integrada dentro de la propia casa.',
    ],
    tips: [
      'Suele estar entre las domus abiertas de forma habitual; es una parada muy recomendable para explicar cómo veían los pompeyanos el Vesubio antes de la erupción.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-marco-lucrecio',
    order: 12.4,
    name: 'Casa de Marco Lucrecio',
    latinName: 'Casa di Marco Lucrezio',
    category: 'domus',
    coords: [40.751, 14.4869],
    regio: 'IX.3.5',
    minutes: 8,
    intro: 'Buscad en el jardín la fuente de mármol con la figura de Sileno: un pequeño lujo doméstico junto a la Via Stabiana.',
    narration: [
      'La casa, de unos seiscientos veinticinco metros cuadrados, se excavó entre mil ochocientos cuarenta y seis y mil ochocientos cuarenta y siete, y conserva frescos de cuarto estilo con un sátiro y una ménade, con Narciso contemplando su reflejo y con Venus pescadora. Una inscripción permite atribuirla a Marco Lucrecio, decurión del consejo municipal y también sacerdote de Marte, un cargo de cierto prestigio en la vida pública pompeyana.',
      'Lo que casi nadie sabe es que la planta alta conservaba en origen otra decoración, hoy perdida casi por completo. Reabierta en octubre de dos mil veinticinco tras una restauración, esta casa forma parte del recorrido habitual de la Regio Novena, muy cerca de las Termas Estabianas.',
    ],
    lookFor: [
      'Los frescos de cuarto estilo con el sátiro y la ménade, y con Narciso.',
      'La fuente de mármol con la figura de Sileno, en el jardín de la casa.',
      'La inscripción que identifica a Marco Lucrecio como decurión y sacerdote de Marte.',
    ],
    tips: [
      'Reabierta en octubre de dos mil veinticinco; horario habitual de mañana a tarde, comprobad el cierre exacto del día.',
    ],
    illus: 'fresco',
    accessibility: 'medio',
  },
  {
    id: 'casa-obellio-firmo',
    order: 12.5,
    name: 'Casa de Obelio Firmo',
    latinName: 'Casa di Obellio Firmo',
    category: 'domus',
    coords: [40.7527, 14.4891],
    regio: 'IX.14.4',
    minutes: 6,
    intro: 'Miradla desde fuera, porque hoy es zona de excavación activa: esta casa pertenece a un hombre cuya tumba veréis más tarde en la Porta Nola.',
    narration: [
      'Se llamaba Marco Obelio Firmo, duunviro pompeyano, y su monumento funerario junto a la Porta Nola es lo que ha permitido relacionar con bastante seguridad su nombre con esta vivienda de origen samnita. En el momento de la erupción, la casa estaba en obras de reforma, otra muestra de la reconstrucción todavía inacabada tras el terremoto del año sesenta y dos.',
      'El detalle que casi nadie ve, porque el acceso no es libre, es la caja fuerte de bronce y hierro hallada en el atrio, el mueble que una familia acomodada exhibía como prueba de solvencia. Un equipo de la Universidad de Bolonia investiga aquí desde hace años, así que su estado puede cambiar según avance la excavación.',
    ],
    lookFor: [
      'El lugar donde apareció la caja fuerte de bronce y hierro, junto al atrio.',
      'Las señales de obras de reforma inacabadas en el momento de la erupción.',
      'La relación con la tumba de Marco Obelio Firmo, en la necrópolis de la Porta Nola.',
    ],
    tips: [
      'Es zona de excavación activa de la Universidad de Bolonia, no incluida en los itinerarios oficiales de visita; considerad esta parada como un punto de paso exterior, no como una casa visitable por dentro.',
    ],
    illus: 'domus',
    accessibility: 'dificil',
  },
  {
    id: 'casa-casti-amanti',
    order: 14.1,
    name: 'Casa de los Castos Amantes',
    latinName: 'Casa dei Casti Amanti',
    category: 'domus',
    coords: [40.750911, 14.490068],
    regio: 'IX.12.6',
    minutes: 10,
    intro: 'Mirad ese fresco del triclinio, un hombre y una mujer a punto de besarse: es la escena más tierna de todo el repertorio pictórico pompeyano.',
    narration: [
      'Ahí, entre otras parejas recostadas en un banquete, está el gesto que da nombre a la casa, más cercano a la ternura que al sexo explícito que domina tantas otras pinturas de la ciudad. Esta vivienda combinaba casa y panadería bajo el mismo techo, con horno propio, cinco molinos y un establo donde se hallaron los restos de cinco animales de carga. Se excavó por primera vez en mil novecientos doce, bajo Vittorio Spinazzola, y se completó ya en el siglo veintiuno.',
      'Lo que casi nadie nota es que la decoración estaba sin terminar cuando llegó la erupción, con dibujos preparatorios y recipientes de pigmento todavía a mano. Tras siete años de restauración, reabrió en mayo de dos mil veinticuatro con una pasarela nueva, a un paso de la Fullonica de Stephanus.',
    ],
    lookFor: [
      'El fresco de banquete del triclinio, con la escena de los castos amantes que da nombre a la casa.',
      'El horno y los molinos de la panadería integrada en la vivienda.',
      'Los dibujos preparatorios sin terminar, señal de una decoración interrumpida por la erupción.',
    ],
    anecdote: 'La escena que da nombre a la casa es, según muchos especialistas, una de las representaciones de afecto de pareja más delicadas de todo el repertorio pictórico pompeyano, frente a la abundancia de escenas más explícitas en otras casas de la ciudad.',
    tips: [
      'Reabierta en mayo de dos mil veinticuatro tras una larga restauración; es una de las incorporaciones más recientes y comentadas del recorrido.',
    ],
    illus: 'pan',
    accessibility: 'medio',
  },
  {
    id: 'casa-fabio-amandio',
    order: 14.2,
    name: 'Casa de Fabio Amandio',
    latinName: 'Casa di Fabio Amandio',
    category: 'domus',
    coords: [40.750579, 14.489538],
    regio: 'I.7.2',
    minutes: 6,
    intro: 'Mirad hacia arriba, al balcón que sobresale sobre la Via dell\'Abbondanza: esta casa modesta, de dos plantas, es la vivienda que de verdad habitaba la mayoría de Pompeya.',
    narration: [
      'De planta estrecha y alargada, resolvía la falta de espacio en la calle sacando un balcón hacia fuera, una solución habitual entre la clase media pompeyana. Nada que ver con las grandes domus de la Regio Sexta que hemos visitado antes. En el atrio se conservan frescos de cuarto estilo, un pozo de hierro y un pavimento de mosaico blanco y negro junto al impluvium.',
      'Lo que casi nadie repara es que hay menos información publicada sobre esta casa que sobre sus vecinas más ilustres, así que conviene tomar cualquier dato con prudencia. Es precisamente esa modestia, frente al lujo de otras paradas, lo que la vuelve interesante.',
    ],
    lookFor: [
      'El balcón sobre la Via dell\'Abbondanza, ejemplo de vivienda de dos plantas con planta baja reducida.',
      'El pavimento de mosaico blanco y negro junto al impluvium del atrio.',
      'Los restos de frescos de cuarto estilo conservados en el atrio.',
    ],
    tips: [
      'La información disponible sobre esta casa es limitada y su apertura al público no está confirmada de forma constante; comprobad en taquilla si es visitable el día de la visita.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-criptoportico',
    order: 14.3,
    name: 'Casa del Criptopórtico',
    latinName: 'Casa del Criptoportico',
    category: 'domus',
    coords: [40.750131, 14.489672],
    regio: 'I.6.2',
    minutes: 9,
    intro: 'Bajad con cuidado hacia esta galería abovedada: aquí se refugiaron, sin conseguirlo, varios habitantes de la casa en las últimas horas de la erupción.',
    narration: [
      'Mirad el friso pintado de tema homérico que recorre las paredes a media altura. El criptopórtico se pensó en origen como un espacio fresco para pasear y descansar en las horas de más calor, no como refugio, y la casa se excavó en varias campañas dirigidas por Vittorio Spinazzola entre mil novecientos once y mil novecientos veintinueve.',
      'El detalle que casi nadie olvida, una vez que lo sabe, es que aquí abajo se hallaron calcos de yeso de las víctimas que buscaron protección bajo tierra sin escapar de la nube ardiente. La casa conserva también una pequeña sala termal privada, un lujo poco frecuente fuera de las grandes domus. Seguid hacia la Casa de los Ceii, un poco más adelante en la misma manzana.',
    ],
    lookFor: [
      'El friso pintado de tema homérico que recorre las paredes del criptopórtico.',
      'El lugar donde se hallaron los calcos de yeso de las víctimas refugiadas en la galería.',
      'Los restos de la pequeña sala termal privada de la vivienda.',
    ],
    tips: [
      'Su acceso es estrecho y en pendiente hacia la galería subterránea; comprobad en taquilla su apertura del día antes de desviaros hacia ella.',
    ],
    illus: 'fresco',
    accessibility: 'dificil',
  },
  {
    id: 'casa-ceii',
    order: 14.4,
    name: 'Casa de los Ceios',
    latinName: 'Casa dei Ceii',
    category: 'domus',
    coords: [40.750033, 14.489397],
    regio: 'I.6.15',
    minutes: 8,
    intro: 'Fijaos bien en esa fachada, de estuco pintado para imitar grandes sillares de piedra: es un engaño tan bien hecho que sigue engañando dos mil años después.',
    narration: [
      'De origen samnita, hacia finales del siglo dos antes de nuestra era, la casa se remodeló ya a comienzos del siglo primero de nuestra era, y se atribuye de forma bastante probable a Lucio Ceyo Segundo, un edil documentado en el año setenta y seis, tres años antes de la erupción. Se excavó entre mil novecientos trece y mil novecientos catorce, con nuevos trabajos en mil novecientos ochenta y dos.',
      'Dentro, un gran fresco de jardín representa una escena de caza de fieras junto a paisajes de tipo nilótico, con animales exóticos y motivos egipcios, la misma moda oriental que ya habréis visto en otras casas de este barrio. Está muy cerca de la Casa del Criptopórtico y de la Casa del Larario de Aquiles.',
    ],
    lookFor: [
      'La fachada con estuco que imita grandes sillares de piedra.',
      'El fresco de jardín con la escena de caza de fieras y paisajes nilóticos.',
      'La probable identificación del propietario con el edil Lucio Ceyo Segundo.',
    ],
    tips: [
      'Suele figurar entre las casas abiertas de forma habitual de este sector de la Regio Primera.',
    ],
    illus: 'fresco',
    accessibility: 'medio',
  },
  {
    id: 'casa-larario-aquiles',
    order: 14.5,
    name: 'Casa del Larario de Aquiles',
    latinName: 'Casa del Larario di Achille',
    category: 'domus',
    coords: [40.7501, 14.48985],
    regio: 'I.6.4',
    minutes: 6,
    intro: 'Acercaos al pequeño larario de esta casa y buscad, en sus frisos, el momento en que Príamo suplica a Aquiles por el cuerpo de su hijo Héctor.',
    narration: [
      'Es un episodio de la Ilíada llevado al rincón más íntimo de una vivienda pompeyana de tamaño medio, el pequeño altar donde la familia rendía culto a sus dioses. La casa, de origen samnita hacia el siglo tres antes de nuestra era, se excavó entre mil novecientos doce y mil novecientos trece, y se despejó del todo en mil novecientos veintinueve.',
      'Lo que casi nadie relaciona es que su propietario en el momento de la erupción sigue sin identificarse, algo poco frecuente en este barrio donde tantas casas llevan nombre y apellido. Combina bien esta parada con la vecina Casa del Criptopórtico y la Casa de los Ceios, todas a un paso.',
    ],
    lookFor: [
      'Los frisos del larario con escenas de la Ilíada, entre ellas Aquiles y Héctor.',
      'La escena del rescate del cuerpo de Héctor por su padre Príamo.',
      'Las dimensiones modestas de la vivienda, representativas de una casa pompeyana media.',
    ],
    tips: [
      'Es una parada corta y sencilla de combinar con la vecina Casa del Criptopórtico y la Casa de los Ceios.',
    ],
    illus: 'lararium',
    accessibility: 'medio',
  },
  {
    id: 'casa-paquio-proculo',
    order: 14.6,
    name: 'Casa de Paquio Próculo',
    latinName: 'Casa di Paquius Proculus',
    category: 'domus',
    coords: [40.750424, 14.489664],
    regio: 'I.7.1',
    minutes: 8,
    intro: 'Otro perro atado vigila este umbral, para que comparéis de memoria con el que ya visteis en la Casa del Poeta Trágico.',
    narration: [
      'Mirad primero el mosaico de las fauces de entrada: un perro sujeto a una cadena y la inscripción cave canem, cuidado con el perro, resuelta aquí con un trazo algo distinto al que recordáis de aquella otra casa. Publio Paquio Próculo y Cayo Cuspio Pansa aparecen los dos en los carteles electorales de la fachada, sin que se sepa con certeza a cuál de los dos perteneció realmente la vivienda.',
      'El pavimento del atrio guarda un mosaico de animales que casi nadie se para a mirar del todo, y en una de las estancias interiores hay una escena nilótica con pigmeos navegando entre cocodrilos e hipopótamos, el mismo gusto egiptizante que veréis repetido en otras casas de Pompeya.',
      'Volved un momento a la Casa del Poeta Trágico con la memoria: dos perros de mosaico, dos casas distintas, la misma advertencia para el visitante que llega.',
    ],
    lookFor: [
      'El mosaico cave canem de las fauces de entrada, distinto al de la Casa del Poeta Trágico.',
      'El mosaico de animales del pavimento del atrio.',
      'La escena nilótica con pigmeos, cocodrilos e hipopótamos.',
    ],
    tips: [
      'Su apertura no es constante; comprobad en taquilla si está entre las casas visitables el día de la visita.',
    ],
    image: { src: 'perro-mosaico', alt: 'Mosaico de un perro guardián en el umbral de una domus de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'mosaico',
    accessibility: 'medio',
  },
  {
    id: 'casa-efebo',
    order: 14.7,
    name: 'Casa del Efebo',
    latinName: "Casa dell'Efebo",
    category: 'domus',
    coords: [40.750456, 14.490009],
    regio: 'I.7.10',
    minutes: 8,
    intro: 'Fijaos en la lámpara con forma de joven griego que da nombre a esta casa de un comerciante enriquecido.',
    narration: [
      'Mirad la réplica de la estatua del efebo, un muchacho de bronce convertido en pie de lámparas, copia de un original griego del siglo cinco antes de nuestra era. La pieza original, hoy en el Museo Arqueológico de Nápoles, decoraba una vivienda nacida de la unión de varias casas más pequeñas, atribuida de forma probable a Publio Cornelio Tegeto, un comerciante que prosperó lo suficiente para permitirse este lujo.',
      'Pocos se fijan en el triclinio de verano, al aire libre, con frescos de motivos nilóticos que delatan el mismo gusto por lo egipcio que encontraréis en otras casas del barrio. Reabrió al público en diciembre de dos mil quince tras una restauración.',
      'A un paso, en la misma manzana, la Casa de Paquio Próculo y la Casa de los Ceios completan este pequeño recorrido de la Regio Primera.',
    ],
    lookFor: [
      'La réplica de la estatua del efebo reconvertida en lámpara, que da nombre a la casa.',
      'El triclinio de verano al aire libre, con frescos de motivos nilóticos.',
      'Los indicios de la fusión de varias viviendas anteriores en una sola casa mayor.',
    ],
    tips: [
      'Suele figurar entre las domus abiertas de forma habitual; combina bien con la visita a la Casa de Paquio Próculo y la Casa de los Ceios, en la misma manzana.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'foro-triangular',
    order: 15.1,
    name: 'Foro Triangular',
    latinName: 'Foro Triangolare',
    category: 'foro',
    coords: [40.748914, 14.4877],
    regio: 'VIII.7.30',
    minutes: 10,
    intro: 'Poneos junto al borde del acantilado: delante tenéis el templo más antiguo de toda Pompeya.',
    narration: [
      'Mirad los restos del llamado Templo Dórico, dedicado probablemente a Atenea y a Hércules, construido ya en el siglo seis antes de nuestra era, más viejo incluso que el Templo de Apolo. La plaza que lo rodea se monumentalizó en el siglo dos antes de Cristo con un pórtico de nada menos que noventa y cinco columnas, aprovechando esta posición elevada sobre el golfo de Nápoles.',
      'Fijaos en el pequeño edificio circular del patio, con un pozo sagrado, varios altares de toba y un reloj de sol: casi nadie se detiene ahí, pero sondeos de dos mil dieciséis sacaron a la luz depósitos votivos del siglo tres antes de nuestra era, prueba de que aquí se rezaba mucho antes de que llegaran los romanos.',
      'A un paso, hacia el Teatro Grande, veréis cómo esa misma ciudad supo también divertirse.',
    ],
    lookFor: [
      'Los restos del Templo Dórico, el edificio religioso más antiguo conservado en Pompeya.',
      'Las columnas del gran pórtico que rodeaba la plaza triangular.',
      'La vista sobre el golfo de Nápoles desde el borde del acantilado.',
    ],
    tips: [
      'Es una de las zonas con mejor sombra y mejores vistas de toda la visita: buen sitio para una pausa junto al Teatro Grande.',
    ],
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'palestra-samnita',
    order: 15.2,
    name: 'Palestra Samnita',
    latinName: 'Palestra Sannitica',
    category: 'servicio',
    coords: [40.74904, 14.487956],
    regio: 'VIII.7.29',
    minutes: 7,
    intro: 'Antes de que existiera la Palestra Grande, los jóvenes pompeyanos venían a entrenarse aquí, junto al Foro Triangular.',
    narration: [
      'Fijaos en el pórtico dórico de columnas de toba que rodea el patio: una inscripción en lengua osca recuerda a Vibio Adirano como responsable de la obra, levantada en el siglo dos antes de nuestra era, mucho antes que su hermana mayor.',
      'Aquí se halló una copia del Doríforo de Policleto, hoy en el Museo Arqueológico de Nápoles, una de las esculturas más influyentes de todo el arte clásico, prueba de que el modelo griego de educación física y formación llegó también hasta Pompeya.',
      'El detalle que pocos notan es el recorte del recinto original: cuando se amplió el vecino Templo de Isis tras el terremoto del año sesenta y dos, la palestra perdió parte de su espacio. Seguid unos pasos hacia el Teatro Grande, Odeón y Cuadripórtico, el otro gran centro de ocio de este barrio.',
    ],
    lookFor: [
      'El pórtico dórico de columnas de toba que rodea el patio.',
      'La inscripción en lengua osca sobre la construcción del edificio.',
      'La proximidad al Templo de Isis, que recortó parte del recinto original tras el terremoto.',
    ],
    tips: [
      'Es una parada corta, fácil de combinar con el Foro Triangular y el Teatro Grande.',
    ],
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'templo-jupiter-meilichio',
    order: 16.1,
    name: 'Templo de Júpiter Meilichio',
    latinName: 'Tempio di Giove Meilichio',
    category: 'templo',
    coords: [40.7489, 14.4885],
    regio: 'VIII.7.25',
    minutes: 6,
    intro: 'Ni siquiera los arqueólogos se ponen de acuerdo sobre a qué dios pertenecía en realidad este pequeño santuario.',
    narration: [
      'Mirad el altar de toba y la cella elevada sobre su podio, cerca del cruce entre la Via Stabiana y la Via del Templo de Isis. Durante mucho tiempo se le atribuyó erróneamente a Esculapio, el dios de la medicina, un error que duró décadas en su nombre popular.',
      'Dentro aparecieron estatuas de terracota de Júpiter y Juno junto con un busto de Minerva, lo que ha llevado a algunos investigadores a pensar que sirvió de sede provisional para el culto a la tríada capitolina mientras se reparaban los daños del terremoto del año sesenta y dos en el templo del Foro.',
      'Es una parada breve, de paso hacia el Teatro Grande y el Templo de Isis, los dos grandes vecinos de este pequeño santuario sin nombre seguro.',
    ],
    lookFor: [
      'El altar de toba y la cella elevada sobre su podio.',
      'Las estatuas de terracota de Júpiter y Juno halladas en el interior.',
      'La posición del templo, en el cruce con la Via del Templo de Isis.',
    ],
    tips: [
      'Es una parada breve, fácil de combinar con la visita al Teatro Grande y al Templo de Isis.',
    ],
    illus: 'columna',
    accessibility: 'facil',
  },
  {
    id: 'casa-trebio-valente',
    order: 17.1,
    name: 'Casa de Trebio Valente',
    latinName: 'Casa di Trebio Valente',
    category: 'domus',
    coords: [40.751472, 14.490989],
    regio: 'III.2.1',
    minutes: 8,
    intro: 'La fachada de esta casa estuvo cubierta, de arriba abajo, de propaganda electoral pintada.',
    narration: [
      'Fijaos en el fragmento que sobrevive en el lado este de la fachada: es lo poco que queda de uno de los mayores conjuntos de carteles electorales conocidos de todo el mundo antiguo, la mayor parte perdida en un bombardeo aliado de mil novecientos cuarenta y tres. Perteneció a la familia de los Trebios, y su último dueño documentado fue Aulo Trebio Valente.',
      'Entrad en el jardín y buscad el triclinio de verano, bajo una pérgola sostenida por cuatro columnas y decorado con pinturas de colores vivos, pensado para cenar al fresco en las noches más calurosas del año.',
      'Esta parte de la Regio Tercera queda algo apartada de las grandes rutas, pero comparte barrio con el Anfiteatro, adonde nos dirigimos ahora.',
    ],
    lookFor: [
      'El fragmento superviviente de los carteles electorales, en el lado este de la fachada.',
      'El triclinio de verano bajo la pérgola de cuatro columnas, en el jardín.',
      'Las pinturas policromas que decoran el espacio del triclinio.',
    ],
    tips: [
      'Suele estar abierta en horario habitual, de nueve y cuarto de la mañana a seis y veinte de la tarde.',
    ],
    image: { src: 'graffiti', alt: 'Grafitos y carteles electorales conservados en los muros de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'porta-nola',
    order: 19.1,
    name: 'Porta Nola',
    latinName: 'Porta di Nola',
    category: 'puerta',
    coords: [40.75372, 14.4908],
    minutes: 6,
    intro: 'Mirad hacia arriba, a la clave del arco: ahí sigue, muy desgastada, la cabeza de Minerva.',
    narration: [
      'Esta puerta samnita se identificó en mil setecientos noventa y nueve y se excavó por completo en mil ochocientos trece. Por aquí salía el camino hacia Nola, otra ciudad campana con la que Pompeya mantenía un tráfico comercial constante.',
      'Fijaos en la inscripción en lengua osca con el nombre de Vibio Popidio, que ejerció como meddix tuticus, la máxima magistratura samnita anterior a la romanización de la ciudad; el original se conserva hoy en el Museo Británico de Londres. Junto a la puerta se extiende una necrópolis con la tumba de Marco Obelio Firmo, el mismo duunviro cuya casa visitamos antes en la Regio Novena.',
      'Queda algo apartada del recorrido principal, en el extremo noreste, camino ya del Anfiteatro.',
    ],
    lookFor: [
      'La cabeza de Minerva, muy erosionada, en la clave del arco de la puerta.',
      'Los restos de la necrópolis adyacente, con la tumba de Marco Obelio Firmo.',
      'El aparejo de piedra de la puerta, de origen samnita anterior a la colonia romana.',
    ],
    tips: [
      'Queda algo apartada del recorrido principal, en el extremo noreste del yacimiento; conviene planificar el desvío si se quiere visitar con calma.',
    ],
    illus: 'calle',
    accessibility: 'medio',
  },
  {
    id: 'porta-sarno',
    order: 21.1,
    name: 'Porta Sarno',
    latinName: 'Porta di Sarno',
    category: 'puerta',
    coords: [40.75281, 14.49442],
    minutes: 6,
    intro: 'Por esta puerta, al final de la Via dell\'Abbondanza, huyeron muchos pompeyanos hacia Nocera.',
    narration: [
      'Fijaos en la perspectiva: la misma calle larga que habéis recorrido desde el Foro termina justo aquí, en una de las siete puertas de la ciudad. Junto a ella se halló el cuerpo de una víctima que llevaba consigo cuarenta y nueve denarios de plata, sesenta y un áureos de oro y varias joyas, hoy en el Museo Arqueológico de Nápoles.',
      'En dos mil veintiuno se descubrió aquí la tumba pintada del liberto Marco Venerio Segundo, con restos que conservan parcialmente signos de momificación natural. Investigadores de la Universidad de Valencia excavan la necrópolis exterior desde dos mil veinticuatro, y en dos mil veinticinco presentaron un nuevo relieve funerario con una pareja de cuerpo entero.',
      'La necrópolis sigue cerrada al público, zona de excavación activa; la puerta y su cara interior sí podéis recorrerlas, camino ya del Anfiteatro.',
    ],
    lookFor: [
      'La puerta en sí, al final de la Via dell\'Abbondanza, marcando la salida este de la ciudad.',
      'La zona donde se investiga la necrópolis exterior, con hallazgos recientes todavía en estudio.',
      'La perspectiva de la calle principal que atraviesa Pompeya de un extremo a otro.',
    ],
    tips: [
      'La necrópolis exterior es una zona de excavación activa y normalmente cerrada al público; la puerta y su cara interior sí se pueden visitar.',
    ],
    illus: 'calle',
    accessibility: 'medio',
  },
  {
    id: 'casa-julia-felix',
    order: 22.1,
    name: 'Casa de Julia Félix',
    latinName: 'Praedia di Giulia Felice',
    category: 'domus',
    coords: [40.7516, 14.4934],
    regio: 'II.4.3',
    minutes: 9,
    intro: 'Una mujer libre convirtió su propia casa en un negocio de alquiler, y lo anunció en un cartel pintado.',
    narration: [
      'Mirad la extensión del huerto y el jardín, casi dos tercios de toda la propiedad: Julia Félix, con plenos derechos de propiedad, decidió tras el terremoto del año sesenta y dos alquilar buena parte de su casa a quien pudiera pagarlo, un balneario elegante, tabernas y pisos superiores.',
      'Fijaos en el euripo, el largo estanque rodeado de pórtico con pilares de mármol, y pensad que un friso hoy conservado en Nápoles retrataba escenas de la vida cotidiana en el propio Foro que ya conocéis. Se excavó primero entre mil setecientos cincuenta y cuatro y mil setecientos cincuenta y siete, y se volvió a enterrar después.',
      'Queda a un paso del Anfiteatro y de la Palestra Grande, en el extremo de la ciudad donde también se ganaba dinero fuera del comercio.',
    ],
    lookFor: [
      'La extensión del huerto y jardín, casi dos tercios de toda la propiedad.',
      'El euripo, el largo estanque rodeado de pórtico con pilares de mármol.',
      'El testimonio del cartel de alquiler, que revela la iniciativa comercial de Julia Félix tras el terremoto.',
    ],
    tips: [
      'Forma parte de un proyecto de investigación en curso y su acceso puede variar según el día; comprobad su disponibilidad en taquilla.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'casa-moralista',
    order: 22.2,
    name: 'Casa del Moralista',
    latinName: 'Casa del Moralista',
    category: 'domus',
    coords: [40.75194, 14.49194],
    regio: 'III.4.2',
    minutes: 7,
    intro: 'Tres normas de buena conducta, pintadas en el triclinio, convierten esta casa en un pequeño manual de urbanidad romana.',
    narration: [
      'Fijaos en las letras blancas sobre fondo negro del triclinio de verano: tres dísticos en latín que piden no decir palabrotas, mantener las manos lejos de las mujeres ajenas y controlar el mal humor durante la cena. La casa nació de la unión de dos viviendas, propiedad de Cayo Arrio Crescente y de Marco Epidio Himeneo.',
      'En el jardín hubo también una estatua de Isis, hoy en el museo de Nápoles, y pocos reparan en que la casa sufrió daños adicionales en los bombardeos de mil novecientos cuarenta y tres y mil novecientos cuarenta y cuatro, las mismas bombas que arrasaron otras viviendas de este barrio.',
      'Está cerca del Anfiteatro, en un sector menos frecuentado por los grandes grupos, camino ya del final de la visita.',
    ],
    lookFor: [
      'Los tres dísticos latinos con normas de buena conducta, pintados en el triclinio de verano.',
      'Los restos que delatan la unión de dos viviendas distintas en una sola casa.',
      'Las huellas de los daños sufridos en los bombardeos de la Segunda Guerra Mundial.',
    ],
    tips: [
      'Su apertura no es constante; comprobad en taquilla si está entre las casas visitables el día de la visita.',
    ],
    illus: 'domus',
    accessibility: 'medio',
  },
  {
    id: 'villa-diomede',
    order: 24.1,
    name: 'Villa de Diomedes',
    latinName: 'Villa di Diomede',
    category: 'villa',
    coords: [40.75239, 14.47871],
    minutes: 12,
    intro: 'Frente a la tumba que le da nombre, esta gran villa suburbana esconde una galería donde murieron treinta y seis personas.',
    narration: [
      'Bajad hacia el criptopórtico subterráneo, la larga galería abovedada donde varios habitantes de la villa se refugiaron sin escapar de la nube ardiente. Francesco La Vega excavó la villa entre mil setecientos setenta y uno y mil setecientos setenta y cuatro, organizada en torno a un peristilo inferior de diecisiete columnas.',
      'Con los cuerpos apareció una bolsa con mil trescientas cincuenta y seis sestercios en monedas, el dinero que sus dueños no llegaron a gastar nunca. La decoración de cuarto estilo se conserva hoy bastante deteriorada, pero la planta completa, con su terraza y su jardín, sigue contando la historia entera de una casa de recreo fuera de las murallas.',
      'Su nombre viene de la tumba de Marco Arrio Diomedes, justo enfrente, aunque nada prueba que él fuera realmente el dueño. Seguid la Via dei Sepolcri y llegaréis pronto a la Villa de los Misterios.',
    ],
    lookFor: [
      'El peristilo inferior de diecisiete columnas, en la parte más baja de la villa.',
      'El largo criptopórtico subterráneo donde se refugiaron sin éxito buena parte de sus habitantes.',
      'La tumba de Marco Arrio Diomedes, justo enfrente, que da nombre a la villa.',
    ],
    tips: [
      'Reabierta al público en dos mil veintidós tras una restauración; horario habitual de nueve y cuarto de la mañana a seis y media de la tarde.',
    ],
    illus: 'domus',
    accessibility: 'dificil',
  },
  {
    id: 'porta-ercolano',
    order: 24.2,
    name: 'Porta Ercolano',
    latinName: 'Porta di Ercolano',
    category: 'puerta',
    coords: [40.751827, 14.48111],
    minutes: 8,
    intro: 'Por esta puerta salían los pompeyanos hacia Herculano, y sus muros todavía guardan las cicatrices de un asedio anterior a la erupción.',
    narration: [
      'Fijaos en los tres vanos: uno central, más ancho, para el paso de carros, y dos laterales para peatones, el mismo esquema que recordaréis de la Porta Marina por donde entramos. Los muros, de origen samnita entre los siglos cuatro y tres antes de nuestra era, sufrieron el asedio de Sila del año ochenta y nueve antes de Cristo.',
      'Buscad, en algunos bloques, las marcas de los proyectiles de catapulta de aquel ataque, mucho antes de que la ciudad muriera de otra manera. La puerta se reconstruyó hacia el año ochenta antes de nuestra era y se monumentalizó de nuevo ya en época flavia.',
      'Al cruzarla arranca la Via dei Sepolcri, con las tumbas de los Mamios y los Istacidios, camino de la Villa de Diomedes y de la Villa de los Misterios.',
    ],
    lookFor: [
      'Los tres vanos de la puerta, uno central para carros y dos laterales para peatones.',
      'Las marcas de proyectiles de catapulta del asedio de Sila, visibles en algunos bloques de piedra.',
      'El arranque de la Via dei Sepolcri, con sus primeros monumentos funerarios.',
    ],
    tips: [
      'Es la puerta de acceso principal para quien llegue en coche o autobús turístico; buen punto de referencia si la visita termina por aquí en lugar de por la Porta Marina.',
    ],
    illus: 'calle',
    accessibility: 'medio',
  },
  {
    id: 'casa-marco-fabio-rufo',
    order: 24.3,
    name: 'Casa de Marco Fabio Rufo',
    latinName: 'Casa di Marco Fabio Rufo',
    category: 'domus',
    coords: [40.75035, 14.4832],
    regio: 'VII.16.22',
    minutes: 10,
    intro: 'Una vivienda escalonada en cuatro niveles se asoma al mar desde lo alto de la muralla oeste.',
    narration: [
      'Mirad cómo la casa gana altura aprovechando el propio desnivel de la muralla, en lo que fue el barrio más exclusivo de Pompeya en sus últimos años, la llamada Insula Occidentalis. Se excavó en distintas campañas del siglo veinte, con un primer sondeo ya en mil setecientos cincuenta y nueve.',
      'Fijaos en los suelos de opus sectile, con mármoles de colores encajados como un rompecabezas, y en una sala que guardaba una copia de una pintura griega del siglo cuatro antes de nuestra era. El nombre del propietario viene de grafitos hallados en la propia casa.',
      'Forma parte del itinerario especial de la Insula Occidentalis, de apertura rotativa, muy cerca ya del Templo de Venus con el que abrimos la visita.',
    ],
    lookFor: [
      'Los cuatro niveles escalonados de la vivienda sobre la muralla oeste.',
      'Los suelos de opus sectile con mármoles de distintos colores.',
      'Las vistas hacia el golfo de Nápoles desde las terrazas superiores.',
    ],
    tips: [
      'Forma parte del itinerario especial de la Insula Occidentalis, de apertura rotativa; comprobad en taquilla si está disponible ese día.',
    ],
    illus: 'fresco',
    accessibility: 'dificil',
  },
  {
    id: 'casa-brazalete-oro',
    order: 24.4,
    name: 'Casa del Brazalete de Oro',
    latinName: "Casa del Bracciale d'Oro",
    category: 'domus',
    coords: [40.750155, 14.48311],
    regio: 'VI.17.42',
    minutes: 10,
    intro: 'Cuatro personas murieron abrazadas al pie de una escalera; una de ellas llevaba un brazalete de oro de más de medio kilo.',
    narration: [
      'Mirad los frescos de jardín, con aves y fuentes pintadas con un naturalismo que se cuenta entre lo mejor conservado de toda Pompeya, en esta casa asomada también a la muralla oeste, escalonada en tres niveles con terrazas hacia el mar.',
      'En mil novecientos setenta y cuatro se hallaron bajo la escalera del jardín los restos de dos adultos y dos niños, refugiados juntos sin conseguir escapar; una de las mujeres llevaba puesto un brazalete de oro en forma de serpiente de unos seiscientos diez gramos, hoy en Nápoles junto a un mosaico con la boda de Alejandro Magno y Roxana.',
      'Conviene visitarla junto a la vecina Casa de Marco Fabio Rufo, en el mismo tramo de la Insula Occidentalis, cerca ya del Templo de Venus.',
    ],
    lookFor: [
      'Los frescos de jardín con aves y fuentes, entre los mejor conservados de la ciudad.',
      'El lugar bajo la escalera donde se hallaron los restos de las cuatro víctimas.',
      'Las terrazas escalonadas de la casa, asomadas hacia el golfo de Nápoles.',
    ],
    tips: [
      'Forma parte del itinerario especial de la Insula Occidentalis, de apertura rotativa; conviene combinarla con la vecina Casa de Marco Fabio Rufo si ambas están abiertas el mismo día.',
    ],
    illus: 'fresco',
    accessibility: 'dificil',
  },
];
