export const GLOSSARY: { term: string; def: string }[] = [
  { term: 'Ánfora', def: 'Recipiente cerámico alargado, de cuerpo ovoide y dos asas, usado para transportar y almacenar vino, aceite o garum. Su base puntiaguda facilitaba apilarlas en bodegas y en las bodegas de los barcos.' },
  { term: 'Apodyterium', def: 'Sala de vestuario de unas termas romanas, con nichos o bancos donde dejar la ropa antes de pasar a las salas de baño.' },
  { term: 'Atrio', def: 'Patio central de una domus romana, cubierto en parte y abierto por el compluvium, en torno al cual se organizaban las habitaciones principales de la casa.' },
  { term: 'Augustales', def: 'Sacerdotes municipales, a menudo libertos enriquecidos, dedicados al culto del emperador y de la familia imperial; el cargo daba prestigio social a quienes no podían acceder a la magistratura por su origen esclavo.' },
  { term: 'Basílica', def: 'Gran edificio civil, normalmente junto al foro, donde se administraba justicia y se hacían negocios; su planta de naves con columnas influyó siglos después en la arquitectura de las iglesias cristianas.' },
  { term: 'Calco', def: 'Vaciado en yeso de la cavidad que dejó en la ceniza endurecida un cuerpo -humano o animal- al descomponerse con el tiempo; técnica ideada por Giuseppe Fiorelli en 1863.' },
  { term: 'Caldarium', def: 'Sala más caliente de unas termas romanas, con suelo y paredes calentados por el hipocausto y, a menudo, una piscina de agua caliente.' },
  { term: 'Cardo', def: 'Calle principal de orientación norte-sur en el trazado urbano romano, que junto con el decumano organizaba la ciudad en manzanas.' },
  { term: 'Caupona', def: 'Establecimiento donde se servía comida y bebida y, con frecuencia, se ofrecía alojamiento sencillo; similar a una taberna pero con más servicios.' },
  { term: 'Cavea', def: 'Graderío semicircular o en forma de herradura de un teatro o anfiteatro romano, dividido en sectores según la clase social del espectador.' },
  { term: 'Cinabrio', def: 'Mineral de mercurio de color rojo intenso, usado como pigmento en la pintura mural pompeyana; muy tóxico y caro, reservado a las casas más pudientes.' },
  { term: 'Cocciopesto', def: 'Mortero hidráulico hecho con cal y fragmentos de cerámica machacada, usado como pavimento e impermeabilizante en cisternas, baños y patios.' },
  { term: 'Columbario', def: 'Estructura funeraria con nichos en las paredes para alojar urnas cinerarias, llamada así por su parecido con un palomar.' },
  { term: 'Comitium', def: 'Espacio público, normalmente junto al foro, destinado a las asambleas políticas y a las votaciones de los ciudadanos.' },
  { term: 'Compluvium', def: 'Abertura rectangular en el tejado del atrio de una domus por la que entraba luz y se recogía el agua de lluvia, que caía al impluvium.' },
  { term: 'Cuatro estilos pompeyanos', def: 'Clasificación, propuesta por el arqueólogo August Mau en el siglo XIX, de la pintura mural romana en cuatro fases: el primero imita mármoles con relieve de estuco; el segundo abre falsas perspectivas arquitectónicas; el tercero simplifica el fondo con paneles delicados; el cuarto combina los anteriores en composiciones más recargadas.' },
  { term: 'Cubiculum', def: 'Habitación pequeña de una domus, usada como dormitorio o para retirarse, con acceso directo al atrio o al peristilo.' },
  { term: 'Curia', def: 'Edificio o sala donde se reunía el consejo municipal (los decuriones) para deliberar sobre los asuntos de la ciudad.' },
  { term: 'Decumano', def: 'Calle principal de orientación este-oeste en el trazado urbano romano, perpendicular al cardo.' },
  { term: 'Dolium', def: 'Gran vasija de cerámica, a menudo semienterrada, usada para almacenar vino, aceite o grano en grandes cantidades; podía superar la altura de una persona.' },
  { term: 'Duoviri', def: 'Los dos magistrados de mayor rango elegidos cada año en una colonia romana como Pompeya, con funciones judiciales y de gobierno equivalentes a las de los cónsules en Roma.' },
  { term: 'Ediles', def: 'Magistrados municipales responsables del mantenimiento de calles y edificios públicos, del abastecimiento y de organizar espectáculos; un peldaño habitual antes de llegar a duunviro.' },
  { term: 'Emblema', def: 'Panel decorativo central de un mosaico, hecho con teselas más pequeñas y de mayor calidad que el resto, a menudo con una escena figurativa.' },
  { term: 'Erupción pliniana', def: 'Tipo de erupción volcánica explosiva que lanza una columna de gas y ceniza muchos kilómetros de altura, llamada así por la descripción que hizo Plinio el Joven de la erupción del Vesubio del 79 d.C.' },
  { term: 'Fauces', def: 'Pasillo estrecho de entrada a una domus romana, entre la fachada a la calle y el atrio, llamado así por su parecido con unas fauces.' },
  { term: 'Frigidarium', def: 'Sala fría de unas termas romanas, con una piscina de agua sin calentar para el baño final del circuito termal.' },
  { term: 'Fullonica', def: 'Taller de lavandería y tintorería romano, donde se lavaba y abatanaba la ropa con orina fermentada y se prensaba en tinas.' },
  { term: 'Garum', def: 'Salsa de pescado fermentado, muy apreciada en toda la cocina romana, que Pompeya exportaba con marca propia; se elaboraba en factorías costeras cercanas.' },
  { term: 'Herma', def: 'Pilar de sección cuadrada rematado por una cabeza o busto, usado como elemento decorativo en jardines y peristilos.' },
  { term: 'Hipocausto', def: 'Sistema de calefacción romano por suelo elevado sobre pilares, bajo el cual circulaba aire caliente procedente de un horno (praefurnium), típico de las termas.' },
  { term: 'Impluvium', def: 'Estanque poco profundo situado en el suelo del atrio, bajo el compluvium, que recogía el agua de lluvia para uso doméstico o para una cisterna.' },
  { term: 'Insula', def: 'Manzana urbana delimitada por calles, unidad básica de la cuadrícula con la que se organizaba y numeraba una ciudad romana como Pompeya.' },
  { term: 'Lapilli', def: 'Fragmentos de piedra pómez expulsados por un volcán durante una erupción explosiva, del tamaño de una gravilla; capa que cubrió Pompeya en las primeras horas de la erupción del 79.' },
  { term: 'Lararium', def: 'Pequeño altar doméstico dedicado a los lares y penates, los dioses protectores del hogar y la familia, presente en casi todas las casas pompeyanas.' },
  { term: 'Liberto', def: 'Esclavo que ha obtenido la libertad; conservaba vínculos y obligaciones con su antiguo dueño, pero podía hacer negocios, tener propiedades y, en algunos casos, prosperar más que muchos ciudadanos libres de nacimiento.' },
  { term: 'Macellum', def: 'Mercado cubierto de una ciudad romana, dedicado sobre todo a la venta de carne y pescado, con tiendas alrededor de un patio central.' },
  { term: 'Oleada piroclástica', def: 'Corriente de gas volcánico, ceniza y rocas a altísima temperatura que desciende por las laderas de un volcán a gran velocidad; las sucesivas oleadas del Vesubio en el 79 d.C. causaron la mayoría de las muertes en Pompeya y Herculano.' },
  { term: 'Opus incertum', def: 'Técnica de construcción romana con piedras irregulares dispuestas sin un patrón geométrico fijo, revestidas después de mortero.' },
  { term: 'Opus latericium', def: 'Técnica de construcción con ladrillo o placas de terracota dispuestas en hiladas regulares, más habitual en época imperial tardía.' },
  { term: 'Opus reticulatum', def: 'Técnica de construcción con pequeños bloques piramidales de piedra colocados en diagonal, formando un patrón reticular muy característico.' },
  { term: 'Opus sectile', def: 'Técnica decorativa de suelos y paredes con piezas de mármol o piedra de colores cortadas y encajadas formando dibujos geométricos, más lujosa que el simple mosaico de teselas.' },
  { term: 'Opus vittatum', def: 'Técnica de construcción con hiladas alternas de piedra pequeña y ladrillo, usada sobre todo en reparaciones y construcciones tardías, como las que se hacían tras el terremoto del 62 d.C.' },
  { term: 'Orchestra', def: 'Espacio semicircular entre el escenario y el graderío de un teatro romano, reservado a los asientos de las autoridades.' },
  { term: 'Palestra', def: 'Espacio abierto, normalmente rodeado de pórticos, destinado al ejercicio físico y a la formación de los jóvenes; en Pompeya, la Palestra Grande junto al anfiteatro es la mayor conservada.' },
  { term: 'Peristilo', def: 'Patio interior de una domus rodeado de columnas por sus cuatro lados, a menudo con jardín, situado detrás del atrio y las estancias principales.' },
  { term: 'Pistrinum', def: 'Panadería romana, con molinos de piedra en forma de reloj de arena movidos por burros o esclavos y hornos abovedados para cocer el pan.' },
  { term: 'Pómez', def: 'Roca volcánica muy porosa y ligera, formada al enfriarse rápidamente la lava cargada de gas; los lapilli que sepultaron Pompeya son, en gran parte, fragmentos de pómez.' },
  { term: 'Programmata', def: 'Inscripciones electorales pintadas en las fachadas de las calles pompeyanas, con las que vecinos y gremios apoyaban a un candidato a magistrado.' },
  { term: 'Regio', def: 'Cada uno de los nueve distritos en los que Giuseppe Fiorelli dividió Pompeya en el siglo XIX para poder localizar con precisión cada edificio mediante el sistema regio-insula-número.' },
  { term: 'Scaenae frons', def: 'Fachada monumental y decorada situada detrás del escenario de un teatro romano, con columnas, nichos y estatuas.' },
  { term: 'Taberna', def: 'Local comercial abierto a la calle, normalmente de una sola sala con un mostrador, donde se vendía comida, bebida u otros productos.' },
  { term: 'Tablinum', def: 'Sala situada al fondo del atrio, frente a la entrada, donde el dueño de la casa recibía a sus clientes y guardaba documentos y archivos familiares.' },
  { term: 'Tepidarium', def: 'Sala templada de unas termas romanas, de temperatura intermedia entre el frigidarium y el caldarium, usada como transición dentro del circuito termal.' },
  { term: 'Termopolio', def: 'Establecimiento de comida rápida romano, con un mostrador de obra en forma de L o de U con grandes vasijas empotradas (dolia) para servir comida y bebida caliente o fría.' },
  { term: 'Tessera', def: 'Pequeña pieza cúbica de piedra, cerámica o vidrio con la que se componían los mosaicos romanos.' },
  { term: 'Triclinium', def: 'Comedor romano, llamado así por los tres lechos (triclinia) dispuestos en torno a una mesa baja sobre los que los comensales se reclinaban para comer.' },
  { term: 'Velarium', def: 'Gran toldo de tela que se extendía sobre el graderío de un anfiteatro o teatro para proteger al público del sol, sujeto mediante mástiles y cuerdas.' }
];
