/**
 * Manifiesto de imágenes. Todas deben ser de dominio público o CC (Wikimedia Commons)
 * y estar descargadas en public/img/<id>.jpg (optimizadas, ≤1400px de ancho).
 * Rellenado por el agente de imágenes; las claves se usan como `src` lógico.
 *
 * Generado automáticamente por scripts/fetch-images.mjs y scripts/fetch-gallery.mjs
 * — no editar a mano.
 */
export interface ImageMeta {
  id: string;
  file: string;        // ruta relativa a public, p.ej. 'img/foro.jpg'
  alt: string;
  credit: string;      // "Autor — CC BY-SA 4.0, Wikimedia Commons"
  sourceUrl: string;
  width: number;
  height: number;
}
export const IMAGES: Record<string, ImageMeta> = {
  "vesubio-panoramica": {
    id: "vesubio-panoramica",
    file: "img/vesubio-panoramica.jpg",
    alt: "El Vesubio visto desde las ruinas de Pompeya",
    credit: "ElfQrin — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ruins_of_Pompeii_with_the_Vesuvius.jpg",
    width: 1400,
    height: 895,
  },
  "foro-vesubio": {
    id: "foro-vesubio",
    file: "img/foro-vesubio.jpg",
    alt: "El Foro de Pompeya con el Vesubio al fondo",
    credit: "Sarahhoa — CC BY-SA 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii,_Forum_with_Temple_of_Jupiter_and_Arco_onorario_with_Vesuvius_in_the_background,_2016_(2).jpg",
    width: 1400,
    height: 933,
  },
  "foro-columnas": {
    id: "foro-columnas",
    file: "img/foro-columnas.jpg",
    alt: "Columnas del Foro de Pompeya",
    credit: "Wknight94 — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Forum_in_Pompeii_3.jpg",
    width: 1400,
    height: 1050,
  },
  "anfiteatro": {
    id: "anfiteatro",
    file: "img/anfiteatro.jpg",
    alt: "Exterior del anfiteatro de Pompeya",
    credit: "Marco Ober — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Amphitheatre_of_Pompeii,_Exterior,_Noon.jpg",
    width: 1400,
    height: 932,
  },
  "anfiteatro-interior": {
    id: "anfiteatro-interior",
    file: "img/anfiteatro-interior.jpg",
    alt: "Interior de la arena del anfiteatro de Pompeya",
    credit: "No machine-readable author provided. Buckeye~commonswiki assumed (based on copyright claims). — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeji_-_Arena.jpg",
    width: 1400,
    height: 1050,
  },
  "teatro-grande": {
    id: "teatro-grande",
    file: "img/teatro-grande.jpg",
    alt: "El Teatro Grande de Pompeya",
    credit: "Thomas Idris Marquand — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Teatro_Grande_Pompeii.jpg",
    width: 1400,
    height: 1050,
  },
  "odeon": {
    id: "odeon",
    file: "img/odeon.jpg",
    alt: "El Odeón (teatro pequeño) de Pompeya",
    credit: "Juliana Bastos Marques — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Odeon_of_Pompeii,_side_entrance.jpg",
    width: 1400,
    height: 933,
  },
  "via-abbondanza": {
    id: "via-abbondanza",
    file: "img/via-abbondanza.jpg",
    alt: "La Via dell'Abbondanza, arteria principal de Pompeya",
    credit: "Rabax63 — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Via_dell%27Abbondanza_(Pompeii).jpg",
    width: 1400,
    height: 933,
  },
  "via-stabiana-adoquines": {
    id: "via-stabiana-adoquines",
    file: "img/via-stabiana-adoquines.jpg",
    alt: "La Via Stabiana con la Porta di Stabia al fondo",
    credit: "Pierre André Leclercq — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Via_Stabiana_with_Porta_di_Stabia_in_Pompeii_2006.jpg",
    width: 1400,
    height: 1006,
  },
  "termopolio-asellina": {
    id: "termopolio-asellina",
    file: "img/termopolio-asellina.jpg",
    alt: "El termopolio de Asellina, con su mostrador de mármol",
    credit: "Mentnafunangann — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Thermopolium_di_Asellina_1.JPG",
    width: 1400,
    height: 1050,
  },
  "termopolio-regio-v": {
    id: "termopolio-regio-v",
    file: "img/termopolio-regio-v.jpg",
    alt: "Termopolio excavado en la Regio V de Pompeya",
    credit: "Jamie Heath from United Kingdom — CC BY-SA 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Thermopolium_-_Pompeii_Scavi_(54537716223).jpg",
    width: 1400,
    height: 1054,
  },
  "casa-fauno": {
    id: "casa-fauno",
    file: "img/casa-fauno.jpg",
    alt: "Columnata de la Casa del Fauno",
    credit: "Jebulon — CC0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Colonnade_house_faun_Pompeii.jpg",
    width: 1400,
    height: 2166,
  },
  "mosaico-alejandro": {
    id: "mosaico-alejandro",
    file: "img/mosaico-alejandro.jpg",
    alt: "El Mosaico de Alejandro, Museo Arqueológico de Nápoles",
    credit: "Unknown creatorUnknown creator — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alexander_and_Bucephalus_-_Battle_of_Issus_mosaic_-_Museo_Archeologico_Nazionale_-_Naples_BW.jpg",
    width: 1400,
    height: 992,
  },
  "casa-vettii-fresco": {
    id: "casa-vettii-fresco",
    file: "img/casa-vettii-fresco.jpg",
    alt: "Frescos romanos en la Casa de los Vettii",
    credit: "Yair Haklai — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ancient_Roman_frescos_in_the_House_of_the_Vettii_(Pompeii)-6.jpg",
    width: 1400,
    height: 663,
  },
  "casa-vettii-priapo": {
    id: "casa-vettii-priapo",
    file: "img/casa-vettii-priapo.jpg",
    alt: "Detalle del fresco de Príapo en la Casa de los Vettii",
    credit: "Unknown authorUnknown author — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Priapus_Fresco_Detail.jpg",
    width: 1400,
    height: 933,
  },
  "villa-misterios-fresco": {
    id: "villa-misterios-fresco",
    file: "img/villa-misterios-fresco.jpg",
    alt: "Escena del culto dionisíaco en la Villa de los Misterios",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii_Ruins_Scenes_of_a_Dionysiac_Mystery_Cult,_Villa_of_the_Mysteries_Fresco,_c._50_BC_(48445612742).jpg",
    width: 1400,
    height: 933,
  },
  "villa-misterios-exterior": {
    id: "villa-misterios-exterior",
    file: "img/villa-misterios-exterior.jpg",
    alt: "Exterior de la Villa de los Misterios",
    credit: "Mentnafunangann — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Villa_dei_Misteri_(Pompei)_WLM_007.JPG",
    width: 1400,
    height: 936,
  },
  "lupanar-fresco": {
    id: "lupanar-fresco",
    file: "img/lupanar-fresco.jpg",
    alt: "Fresco erótico del Lupanar de Pompeya",
    credit: "WolfgangRieger — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii_-_Lupanar_-_Couple2.jpg",
    width: 1400,
    height: 854,
  },
  "termas-estabianas": {
    id: "termas-estabianas",
    file: "img/termas-estabianas.jpg",
    alt: "Vestuario (apodyterium) de las Termas Estabianas",
    credit: "Mary Harrsch — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Men%27s_apodyterium_(changing_room)_of_the_Stabian_Baths_Pompeii_Prowalk.jpg",
    width: 1197,
    height: 615,
  },
  "termas-foro": {
    id: "termas-foro",
    file: "img/termas-foro.jpg",
    alt: "Caldarium de las Termas del Foro",
    credit: "Isaac Harjo of ProWalk Tours; Screen capture and additional editing by Mary Harrsch — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Caldarium_with_Labrum_in_the_Forum_Baths_Pompeii_ProWalk_Tours.jpg",
    width: 1071,
    height: 629,
  },
  "calcos-yeso": {
    id: "calcos-yeso",
    file: "img/calcos-yeso.jpg",
    alt: "Calco de yeso de una víctima de la erupción",
    credit: "daryl_mitchell from Saskatoon, Saskatchewan, Canada — CC BY-SA 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Plaster_Cast_Body_(15910425865).jpg",
    width: 1400,
    height: 1050,
  },
  "jardin-fugitivos": {
    id: "jardin-fugitivos",
    file: "img/jardin-fugitivos.jpg",
    alt: "El Jardín de los Fugitivos, con los calcos de las víctimas",
    credit: "Mentnafunangann — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Orto_dei_Fuggiaschi_12.JPG",
    width: 1400,
    height: 1050,
  },
  "templo-apolo": {
    id: "templo-apolo",
    file: "img/templo-apolo.jpg",
    alt: "El Templo de Apolo de Pompeya",
    credit: "Marco Ober — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Temple_of_Apollo_-_Tempio_di_Apollo,_Pompeii_(5139).jpg",
    width: 1400,
    height: 875,
  },
  "templo-jupiter": {
    id: "templo-jupiter",
    file: "img/templo-jupiter.jpg",
    alt: "El Templo de Júpiter en el Foro de Pompeya",
    credit: "Jebulon — CC0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Temple_of_Jupiter_Pompeii.jpg",
    width: 1400,
    height: 932,
  },
  "templo-isis": {
    id: "templo-isis",
    file: "img/templo-isis.jpg",
    alt: "El Templo de Isis de Pompeya",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii,_Temple_of_Isis,_East_Portico,_Harpocrates_Niche_with_a_reproduction_of_a_Fresco_(48442486262).jpg",
    width: 1400,
    height: 933,
  },
  "basilica": {
    id: "basilica",
    file: "img/basilica.jpg",
    alt: "La Basílica de Pompeya",
    credit: "Mentnafunangann — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Basilica_(Pompei)_WLM_002.JPG",
    width: 1400,
    height: 936,
  },
  "panaderia-horno": {
    id: "panaderia-horno",
    file: "img/panaderia-horno.jpg",
    alt: "Horno y molinos de una panadería de Pompeya",
    credit: "Isaac Harjo of Prowalk Tours — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bakery_with_oven_and_mills_Pompeii_ProWalk_Tours.jpg",
    width: 1134,
    height: 549,
  },
  "porta-marina": {
    id: "porta-marina",
    file: "img/porta-marina.jpg",
    alt: "La Porta Marina, entrada principal a Pompeya",
    credit: "Falk2 — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:I08_129_Porta_Marina.jpg",
    width: 1400,
    height: 965,
  },
  "cave-canem": {
    id: "cave-canem",
    file: "img/cave-canem.jpg",
    alt: "Mosaico \"Cave Canem\" en la Casa del Poeta Trágico",
    credit: "Carole Raddato from FRANKFURT, Germany — CC BY-SA 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cave_Cavem_mosaic_floor_in_the_vestibulum_of_the_House_of_the_Tragic_Poet,_Pompeii_(14402122118).jpg",
    width: 1400,
    height: 1000,
  },
  "casa-menandro": {
    id: "casa-menandro",
    file: "img/casa-menandro.jpg",
    alt: "Jardín de la Casa del Menandro",
    credit: "Marco Ober — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Casa_del_Menandro,_Garden,_Pompeii_(4970).jpg",
    width: 1400,
    height: 932,
  },
  "palestra-grande": {
    id: "palestra-grande",
    file: "img/palestra-grande.jpg",
    alt: "La Gran Palestra de Pompeya",
    credit: "Sören Bleikertz — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeji_great_palaestra.jpg",
    width: 1024,
    height: 768,
  },
  "fullonica-stephanus": {
    id: "fullonica-stephanus",
    file: "img/fullonica-stephanus.jpg",
    alt: "La Fullonica de Stephanus, tintorería romana",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fullonica_of_Stephanus_(Pompeii)_(48443555206).jpg",
    width: 1400,
    height: 933,
  },
  "graffiti": {
    id: "graffiti",
    file: "img/graffiti.jpg",
    alt: "Grafitos antiguos conservados en los muros de Pompeya",
    credit: "Wknight94 — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii_graffiti.jpg",
    width: 1400,
    height: 1050,
  },
  "necropolis-porta-nocera": {
    id: "necropolis-porta-nocera",
    file: "img/necropolis-porta-nocera.jpg",
    alt: "Tumbas de la necrópolis de Porta Nocera",
    credit: "Ввласенко — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tombs_and_mausoleums_at_Necropolis_of_Porta_Nocera._Pompeii._Italy.jpg",
    width: 1400,
    height: 930,
  },
  "arco-caligula": {
    id: "arco-caligula",
    file: "img/arco-caligula.jpg",
    alt: "El Arco de Calígula, junto al Foro",
    credit: "Isaac Harjo of ProWalk Tours; Screen capture and additional editing by Mary Harrsch — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Arch_of_Caligula_Pompeii_ProWalk_Tours_03.jpg",
    width: 1116,
    height: 661,
  },
  "macellum": {
    id: "macellum",
    file: "img/macellum.jpg",
    alt: "Patio del Macellum, mercado de Pompeya",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Macellum_(Pompeii)_-_Courtyard_with_tholos_(48441993746).jpg",
    width: 1400,
    height: 933,
  },
  "edificio-eumachia": {
    id: "edificio-eumachia",
    file: "img/edificio-eumachia.jpg",
    alt: "Entrada al Edificio de Eumachia, en el Foro",
    credit: "Marco Ober — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Building_of_Eumachia,_Pompeii_Forum,_Entrance.jpg",
    width: 1400,
    height: 932,
  },
  "lararium": {
    id: "lararium",
    file: "img/lararium.jpg",
    alt: "Larario (altar doméstico) en un termopolio de Pompeya",
    credit: "Chappsnet — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lararium_(household_shrine)_in_the_thermopolium_of_Lucius_Vetutius_Placidus.jpg",
    width: 1400,
    height: 933,
  },
  "erupcion-pintura": {
    id: "erupcion-pintura",
    file: "img/erupcion-pintura.jpg",
    alt: "La destrucción de Pompeya y Herculano, óleo de John Martin",
    credit: "John Martin — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Destruction_of_Pompeii_and_Herculaneum.jpg",
    width: 1400,
    height: 871,
  },
  "plinio-grabado": {
    id: "plinio-grabado",
    file: "img/plinio-grabado.jpg",
    alt: "Retrato de Plinio el Viejo",
    credit: "Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pliny_the_Elder.png",
    width: 178,
    height: 238,
  },
  "plano-historico": {
    id: "plano-historico",
    file: "img/plano-historico.jpg",
    alt: "Plano histórico de Pompeya, 1832",
    credit: "William Barnard Clarke — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:1832_S.D.U.K._City_Plan_or_Map_of_Pompeii,_Italy_-_Geographicus_-_Pompeii-SDUK-1832.jpg",
    width: 1400,
    height: 1105,
  },
  "fiorelli-retrato": {
    id: "fiorelli-retrato",
    file: "img/fiorelli-retrato.jpg",
    alt: "Busto de Giuseppe Fiorelli",
    credit: "Edmund F. Arras — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bust_of_Giuseppe_Fiorelli_-_DPLA_-_606d51f38a4e8bbc12e817ef405f1429.jpg",
    width: 1400,
    height: 823,
  },
  "herculano-papiros": {
    id: "herculano-papiros",
    file: "img/herculano-papiros.jpg",
    alt: "Papiros carbonizados de Herculano",
    credit: "Sara Stabile, Francesca Palermo, Inna Bukreeva, Daniela Mele, Vincenzo Formoso, Roberto Bartolino & Alessia Cedola — CC BY 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Herculaneum_papyri.jpg",
    width: 1400,
    height: 1214,
  },
  "perro-mosaico": {
    id: "perro-mosaico",
    file: "img/perro-mosaico.jpg",
    alt: "Mosaico \"Cave Canem\" con un perro guardián",
    credit: "Xuan Che — CC BY 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cave_canem_-_beware_of_the_dog.jpg",
    width: 1400,
    height: 843,
  },
  "cocina-romana": {
    id: "cocina-romana",
    file: "img/cocina-romana.jpg",
    alt: "Utensilio de cocina romano hallado en Pompeya",
    credit: "Tyler Bell — CC BY 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Grill_with_handle_(for_cooking_meat_and_fish)_Roman,_Pompeii,_House_of_the_Vettii,_AD_1-79_(51357506688).jpg",
    width: 1400,
    height: 1089,
  },
  "anfora": {
    id: "anfora",
    file: "img/anfora.jpg",
    alt: "Ánforas romanas entre las ruinas de Pompeya",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii_Ruins_Pottery_Amphorae_(48440850197).jpg",
    width: 1400,
    height: 933,
  },
  "escritorio-tablillas": {
    id: "escritorio-tablillas",
    file: "img/escritorio-tablillas.jpg",
    alt: "Fresco de mujer con estilo y tablillas de cera (la \"Safo\")",
    credit: "Carole Raddato — CC BY-SA 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fresco_showing_a_woman_so-called_Sappho_holding_writing_implements,_from_Pompeii,_Naples_National_Archaeological_Museum_(14842101892).jpg",
    width: 1400,
    height: 1353,
  },
  "calle-fuente": {
    id: "calle-fuente",
    file: "img/calle-fuente.jpg",
    alt: "Fuente pública en un cruce de calles de Pompeya",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii,_Ancient_Roman_Fountain_at_the_junction_of_Via_Stabiana_and_Via_dell%27Abbondanza_(48441020961).jpg",
    width: 1400,
    height: 933,
  },
  "comitium": {
    id: "comitium",
    file: "img/comitium.jpg",
    alt: "El Comitium, edificio de voto del Foro de Pompeya",
    credit: "Mentnafunangann — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Comitium_1.JPG",
    width: 1400,
    height: 1050,
  },
  "porta-marina-g1": {
    id: "porta-marina-g1",
    file: "img/porta-marina-g1.jpg",
    alt: "Pasadizo estrecho y abovedado para peatones en la Porta Marina",
    credit: "Falk2 — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:I08_130a_Porta_Marina,_Durchfahr%C3%B6ffnung.jpg",
    width: 1400,
    height: 2100,
  },
  "porta-marina-g2": {
    id: "porta-marina-g2",
    file: "img/porta-marina-g2.jpg",
    alt: "Rampa de acceso a la Porta Marina vista desde el exterior de la muralla",
    credit: "Falk2 — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:I08_128_Pompeii,_Rampe_zur_Porta_Marina.jpg",
    width: 1400,
    height: 933,
  },
  "porta-marina-g3": {
    id: "porta-marina-g3",
    file: "img/porta-marina-g3.jpg",
    alt: "Tramo de muralla de piedra caliza junto a la Porta Marina",
    credit: "Yair Haklai — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Marina_gate_and_Pompeii_city_walls.jpg",
    width: 1400,
    height: 2958,
  },
  "templo-venus-g1": {
    id: "templo-venus-g1",
    file: "img/templo-venus-g1.jpg",
    alt: "Terraza del Templo de Venus con columnas y vistas al golfo de Nápoles",
    credit: "Falk2 — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:I08_131_Venustempel.jpg",
    width: 1400,
    height: 933,
  },
  "templo-venus-g2": {
    id: "templo-venus-g2",
    file: "img/templo-venus-g2.jpg",
    alt: "Restos de una columna corintia en el Templo de Venus de Pompeya",
    credit: "Roma1314 — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Colonna_a_Pompei.JPG",
    width: 1400,
    height: 930,
  },
  "templo-venus-g3": {
    id: "templo-venus-g3",
    file: "img/templo-venus-g3.jpg",
    alt: "Vista panorámica desde la terraza del Templo de Venus hacia la llanura costera",
    credit: "Bruno Rijsman — CC BY-SA 2.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompei_(Italy,_October_2020)_-_67_(50543741701).jpg",
    width: 1400,
    height: 933,
  },
  "basilica-g1": {
    id: "basilica-g1",
    file: "img/basilica-g1.jpg",
    alt: "Interior de la Basílica de Pompeya con sus columnas de ladrillo",
    credit: "Adam Harangozó — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Basilica,_Pompeii_01.jpg",
    width: 1400,
    height: 933,
  },
  "basilica-g2": {
    id: "basilica-g2",
    file: "img/basilica-g2.jpg",
    alt: "Detalle de una columna de ladrillo de la Basílica de Pompeya",
    credit: "Mentnafunangann — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Basilica_(Pompei)_WLM_003.JPG",
    width: 1400,
    height: 936,
  },
  "templo-apolo-g1": {
    id: "templo-apolo-g1",
    file: "img/templo-apolo-g1.jpg",
    alt: "Reproducción en bronce de Apolo tensando el arco en el Templo de Apolo",
    credit: "Gary Todd from Xinzheng, China — Public domain, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii_Ruins_Temple_of_Apollo_%26_Bronze_Statue_of_Apollo_(48440752001).jpg",
    width: 1400,
    height: 933,
  },
  "templo-apolo-g2": {
    id: "templo-apolo-g2",
    file: "img/templo-apolo-g2.jpg",
    alt: "Inscripción en la columna del reloj de sol del Templo de Apolo",
    credit: "Wknight94 — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pompeii_Temple_of_Apollo_inscription.jpg",
    width: 1400,
    height: 1050,
  },
  "templo-apolo-g3": {
    id: "templo-apolo-g3",
    file: "img/templo-apolo-g3.jpg",
    alt: "Patio porticado del Templo de Apolo con sus columnas jónicas",
    credit: "C1815 — CC0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2025-03-12_Santuario_di_Apollo.jpg",
    width: 1400,
    height: 933,
  },
  "foro-g1": {
    id: "foro-g1",
    file: "img/foro-g1.jpg",
    alt: "Pórtico de columnas en uno de los lados largos del Foro de Pompeya",
    credit: "Mentnafunangann — CC BY-SA 3.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Foro_(Pompei)_WLM_002.JPG",
    width: 1400,
    height: 936,
  },
  "edificio-eumachia-g1": {
    id: "edificio-eumachia-g1",
    file: "img/edificio-eumachia-g1.jpg",
    alt: "Columnas de la entrada porticada del Edificio de Eumáquia",
    credit: "Bernard Gagnon — CC BY 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eumachia_building_(Pompeii)_-_columns.jpg",
    width: 1400,
    height: 907,
  },
  "edificio-eumachia-g2": {
    id: "edificio-eumachia-g2",
    file: "img/edificio-eumachia-g2.jpg",
    alt: "Vista general del patio del Macellum, mercado de Pompeya",
    credit: "Yair Haklai — CC BY-SA 4.0, Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Macellum_(Pompeii).jpg",
    width: 1400,
    height: 663,
  },
};
export const img = (id: string) => IMAGES[id]?.file ? `${import.meta.env.BASE_URL}${IMAGES[id].file}` : '';
export const imgSm = (id: string) => {
  const meta = IMAGES[id];
  if (!meta?.file) return '';
  const smFile = meta.file.replace(/\.jpg$/, '-sm.jpg');
  return `${import.meta.env.BASE_URL}${smFile}`;
};
