import type { IllustrationName, StopCategory } from './types';
/** Fichas propias de los puntos del plano oficial que NO tienen parada en la ruta. Clave: 'REGIO-NUM'. */
export interface OfficialEntry {
  coords?: [number, number];
  category: StopCategory;
  illus: IllustrationName;
  intro: string;
  narration: string[];   // 2-3 párrafos, 110-180 palabras
  lookFor?: string[];
  tips?: string[];
}
export const OFFICIAL_ENTRIES: Record<string, OfficialEntry> = {
  'I-2': {
    coords: [40.7501283, 14.4890852],
    category: 'domus',
    illus: 'fresco',
    intro: 'Entrad en el pequeño triclinio de la izquierda y buscad, en la pared del fondo, una fila de cuadros diminutos que en realidad son solo pintura.',
    narration: [
      'No son de verdad, están pintados, pero el artista los rodeó de un marco tan fino que muchos visitantes de hace dos mil años tuvieron que acercarse para comprobarlo, igual que vosotros ahora. Cada uno de esos cuadritos teatrales muestra una escena de comedia, con máscaras y actores, y de ahí viene uno de los nombres de esta casa.',
      'El otro nombre, Casca Longo, viene de un sello de bronce hallado dentro con el nombre Cascus. Algunos han querido ver ahí a un pariente del Casca que clavó el primer puñal en Julio César, pero no hay ninguna prueba que sostenga ese parentesco, así que quedaos con la duda en lugar de la anécdota fácil.',
      'Fijaos en que ninguno de los cuadros se repite: el dueño, quienquiera que fuese, pagó por una serie completa, no por copias baratas. A pocos pasos, en la Via dell\'Abbondanza, vais a encontrar otra casa que también presume de pintura sin necesidad de una sola escultura cara.',
    ],
    lookFor: ['La fila de cuadros diminutos con escenas de comedia en el triclinio', 'El marco pintado, tan fino que imita uno real'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'I-11': {
    coords: [40.7505182, 14.4896351],
    category: 'domus',
    illus: 'fresco',
    intro: 'Buscad en la fachada, junto a la puerta, las letras rojas medio borradas de un cartel electoral que dio nombre a esta casa.',
    narration: [
      'El nombre no viene de ningún dueño documentado, sino de una pintada electoral en la fachada que pedía el voto para un tal Amando, sacerdote de la ciudad. Los arqueólogos del siglo diecinueve decidieron bautizar así la casa, aunque nunca se ha demostrado que Amando viviera aquí dentro: pudo pintar su cartel en cualquier pared de paso, como hacían decenas de candidatos por toda Pompeya.',
      'Dentro, el esquema es el de tantas domus medianas de la Via dell\'Abbondanza: atrio, tablinum y un jardín trasero que hacía de patio y de despensa a la vez, con parras y hortalizas entre las columnas. No es una casa de las que sacan postal, y por eso mismo conserva mejor lo cotidiano, con el enlucido sin restaurar y la cocina ennegrecida por el humo.',
      'Fijaos, si la reja lo permite, en el umbral de piedra: tiene el hueco donde encajaba la tranca de madera que cerraba la puerta cada noche, el mismo sistema que veréis repetido en casi todas las entradas de esta manzana.',
    ],
    lookFor: ['El cartel electoral pintado junto a la puerta', 'El hueco de la tranca en el umbral'],
    tips: ['Las coordenadas son aproximadas, tomadas de la casa vecina; confirmad en taquilla si está abierta.'],
  },
  'I-12': {
    coords: [40.7507621, 14.4902808],
    category: 'comercio',
    illus: 'termopolio',
    intro: 'Apoyaos en el mostrador de obra y contad los agujeros redondos: son las bocas de las tinajas donde este hombre guardaba lo que vendía al paso.',
    narration: [
      'Este mostrador en forma de ele, con sus tinajas de barro encajadas, perteneció a Lucio Vetucio Plácido, cuyo nombre conocemos por un sello y por tablillas encontradas dentro. No vendía comida caliente para sentarse a comer, sino vino, legumbres cocidas y algún guiso rápido a los que pasaban por la Via dell\'Abbondanza, la calle más transitada de la ciudad.',
      'Detrás del mostrador hay una pequeña vivienda, y en su pared hallaréis pintado un larario que merece la pena mirar despacio: dos serpientes que se acercan a un altar con ofrendas, y encima Baco vestido de racimos de uva junto a Mercurio con su bolsa de monedas, los dos dioses que a Plácido más le convenía tener contentos.',
      'En el momento de la erupción había en la casa una caja con más de mil monedas de bronce y de plata que nadie llegó a tiempo de coger. Seguid la Via dell\'Abbondanza hacia el foro: veréis mostradores parecidos casi en cada esquina, la calle comercial más concurrida de la ciudad.',
    ],
    lookFor: ['El mostrador con las tinajas encajadas', 'El larario pintado con las serpientes y Baco'],
    tips: ['Comprobad en taquilla el horario; suele abrirse dentro del circuito de la Via dell\'Abbondanza.'],
  },
  'I-13': {
    coords: [40.7509056, 14.4906838],
    category: 'domus',
    illus: 'fresco',
    intro: 'Entrad en el dormitorio pequeño y quedaos un momento de pie en el centro: las cuatro paredes os meten dentro de un jardín pintado sin principio ni fin.',
    narration: [
      'En dos habitaciones minúsculas de esta casa, alguien decidió que dormir no tenía por qué significar encerrarse entre paredes de yeso liso. Pintó árboles cargados de fruta, pájaros posados en las ramas y un cielo azul continuo, sin esquinas, sin marco, para que el que se tumbara en la cama tuviera la sensación de dormir al aire libre.',
      'De esos dos cuartos vienen los dos nombres con que se conoce la casa: del Huerto y de los Cubículos Florales. No sabemos quién encargó esta fantasía ni por qué, pero el gasto en pintores buenos delata a alguien con dinero y con ganas de presumir, aunque fuera solo ante las visitas que entraban a saludar antes de acostarse.',
      'Buscad, si la luz ayuda, el detalle que casi nadie señala: entre las ramas hay pájaros de especies distintas, pintados con cuidado suficiente para reconocerlos, no como simple relleno decorativo. La casa está a un paso de la de Ceres, con un jardín de verdad en lugar de pintado.',
    ],
    lookFor: ['El dormitorio pintado como un jardín sin fin', 'Las distintas especies de pájaros entre las ramas'],
    tips: ['Suele verse solo desde la reja; confirmad en taquilla si el circuito la incluye.'],
  },
  'I-14': {
    coords: [40.751224, 14.491134],
    category: 'comercio',
    illus: 'termopolio',
    intro: 'Fijaos en el rótulo pintado sobre el mostrador, ya muy perdido: ahí estuvo la loba de Roma que dio a esta taberna su segundo nombre.',
    narration: [
      'Sotérico, el nombre por el que se conoce esta caupona, aparece en varios grafitos rascados en sus paredes; no sabemos si era el dueño o solo un cliente que quiso dejar constancia de su paso. Sí se conserva el otro nombre, a la Insegna di Roma, por una pintura hoy casi perdida que representaba a la loba amamantando a Rómulo y Remo, un motivo que también veréis, mejor conservado, unas calles más allá.',
      'Como tantas cauponas de Pompeya, esta combinaba mostrador de bebida, cocina pequeña y una o dos habitaciones donde el viajero de paso podía pasar la noche sin lujos. No hay aquí ninguna pintura de las que llenan salas de museo, y por eso mismo conserva el aire de negocio modesto que tuvo siempre.',
      'Mirad el suelo junto al mostrador: el desgaste de las losas marca el camino exacto que hacían los pies de generaciones de clientes, siempre la misma línea, día tras día, durante más de un siglo.',
    ],
    lookFor: ['El resto del rótulo pintado sobre el mostrador', 'El desgaste de las losas frente a la barra'],
    tips: ['Coordenadas tomadas del edificio vecino, la panadería de Sotérico; confirmad en taquilla si está abierta.'],
  },
  'I-15': {
    coords: [40.750512, 14.4918098],
    category: 'domus',
    illus: 'domus',
    intro: 'Id directos al jardín trasero, bajo la pérgola reconstruida: aquí se aprendió a leer los huecos de raíces en la tierra como quien lee un texto.',
    narration: [
      'El nombre de la casa viene de un grafito pequeño, casi un descuido, rascado en el enlucido del jardín: el dibujo de un barco con el nombre Europa junto a él, quizá obra de un marinero que pasó por aquí o de alguien que soñaba con embarcar. Nadie ha explicado el porqué con certeza.',
      'Lo importante de esta casa está en la tierra, no en las paredes. Cuando se excavó el jardín, a mediados del siglo veinte, los arqueólogos encontraron los huecos oscuros que habían dejado las raíces de árboles y vides muertos hacía dos mil años, y a partir de esos huecos, vaciados con yeso, reconstruyeron dónde estaba plantada cada planta y bajo qué pérgola de madera corría cada vid.',
      'Es uno de los jardines romanos mejor documentados que existen, gracias a ese método. Mirad las columnas de la pérgola actual: siguen la disposición original, y la sombra que dan hoy es parecida a la que refrescaba al dueño de la Nave Europa una tarde de agosto del setenta y nueve.',
    ],
    lookFor: ['El grafito del barco Europa en el jardín', 'La disposición de la pérgola sobre los huecos de raíces'],
    tips: ['Confirmad en taquilla si el jardín está abierto; el acceso varía según la temporada.'],
  },
  'I-17': {
    coords: [40.74961, 14.48972],
    category: 'domus',
    illus: 'domus',
    intro: 'Miraos los dos huecos que flanquean la puerta principal: eran tiendas independientes, alquiladas aparte, aunque compartían tejado con la casa de detrás.',
    narration: [
      'Esta casa debe su nombre de conveniencia, casa con tiendas, a algo tan simple como su fachada: dos locales abiertos a la calle, sin comunicación con el interior, que el propietario alquilaba a comerciantes que nada tenían que ver con la familia. Era el modelo de negocio más habitual en Pompeya, no la excepción: cualquier fachada larga se aprovechaba así.',
      'No conocemos el nombre del dueño ni una historia particular que contar de estas paredes, y eso también es un dato: la mayoría de las casas de esta manzana de la Via dell\'Abbondanza vivían de este mismo esquema silencioso, rentas pequeñas que sostenían a familias medianas sin lápidas ni menciones en ningún libro.',
      'Fijaos en el escalón de piedra gastado en el hueco de cada tienda, más hundido en el centro que en los lados: el paso constante de gente entrando y saliendo, durante generaciones, dejó esa curva que todavía se puede seguir con el dedo.',
    ],
    lookFor: ['Los dos huecos de tienda a los lados de la puerta principal', 'El desgaste curvo en los escalones de las tiendas'],
    tips: ['Se ve generalmente desde la calle; confirmad en taquilla si está abierta al público.'],
  },
  'I-18': {
    coords: [40.7494938, 14.4899364],
    category: 'domus',
    illus: 'fresco',
    intro: 'Id al fondo del peristilo y buscad, en rojo sobre la columna, una frase escrita hace dos mil años que todavía funciona como piropo.',
    narration: [
      'Amantes ut apes vitam mellitam exigunt, dice la pintada: los amantes, como las abejas, quieren una vida de miel. De esa frase, escrita en el jardín con la misma soltura con que hoy se escribe en la pared de un bar, viene el nombre de la casa de los amantes.',
      'No sabemos quién la escribió ni para quién, si era un enamorado presumiendo o alguien copiando un verso que ya circulaba de boca en boca por la ciudad. Pompeya está llena de citas de este tipo, mitad poesía, mitad broma, rascadas por manos anónimas en cualquier superficie a mano.',
      'El resto de la casa es modesto, sin frescos de los que hacen historia del arte, y por eso la frase brilla más: es el único motivo por el que alguien se detiene aquí. A un paso, en la Via dell\'Abbondanza, encontraréis decenas de pintadas parecidas, la voz de la calle que ningún historiador inventó.',
    ],
    lookFor: ['La inscripción pintada sobre la columna del peristilo'],
    tips: ['No está en el circuito habitual; confirmad en taquilla si se puede acceder o solo se ve desde la reja.'],
  },
  'I-19': {
    coords: [40.7503617, 14.4904335],
    category: 'domus',
    illus: 'fresco',
    intro: 'Cruzad el atrio y comparad, cuarto a cuarto, cómo cambia la manera de pintar una pared: aquí conviven cuatro modas de golpe.',
    narration: [
      'Los historiadores del arte dividen la pintura de Pompeya en cuatro estilos, del más antiguo, que imita bloques de mármol, al más recargado, con arquitecturas fantásticas y escenas mitológicas flotando en paneles de color. Casi ninguna casa conserva ejemplos claros de los cuatro a la vez; esta sí, y de ahí su nombre.',
      'No fue un capricho de coleccionista: cada reforma se hizo en un momento distinto, con el gusto de esa década, y nadie se molestó en repintar lo anterior si seguía en pie. El resultado, sin querer, es un pequeño manual de historia del arte romano bajo un mismo techo.',
      'Id de sala en sala buscando la juntura entre estilos, el punto exacto donde una pared cambia de década a otra sin previo aviso. Ese salto, más que cualquier fecha, es lo que de verdad enseña esta casa.',
    ],
    lookFor: ['La pared donde se tocan dos estilos de pintura distintos'],
    tips: ['Confirmad en taquilla si está abierta; suele verse también parcialmente desde la reja.'],
  },
  'I-20': {
    coords: [40.7500809, 14.4912971],
    category: 'domus',
    illus: 'columna',
    intro: 'Mirad hacia el peristilo: en lugar de un arquitrabe recto sobre las columnas, alguien tendió arcos, algo tan raro aquí que le dio nombre a la casa.',
    narration: [
      'Casi todos los peristilos de Pompeya cierran sus columnas con una viga horizontal. En esta casa, excavada en mil novecientos cincuenta y cuatro, el propietario prefirió unirlas con arcos, una solución más habitual en la arquitectura pública que en una vivienda privada, y bastó ese capricho para que la llamaran la casa de los arcos.',
      'Sobre el peristilo corría una galería de madera, hoy reconstruida, que daba acceso a las habitaciones del piso superior; subir allí y asomarse debía de ser el mejor sitio de la casa para ver llover. En el jardín se conserva también un larario, el altar doméstico donde la familia hacía sus ofrendas cotidianas.',
      'Fijaos en el grosor de los arcos comparado con el de las columnas que sostienen: no sobra piedra por ningún lado, justo la necesaria, la misma economía de medios que veréis en tantas soluciones improvisadas de esta ciudad.',
    ],
    lookFor: ['Los arcos que unen las columnas del peristilo', 'La galería de madera reconstruida sobre el patio'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'I-21': {
    coords: [40.7495303, 14.4925789],
    category: 'comercio',
    illus: 'gladiador',
    intro: 'Buscad la estatuilla de piedra volcánica de un gladiador que dio nombre a esta taberna, hoy guardada en el museo, pero cuyo hueco de origen seguís pisando.',
    narration: [
      'La figurilla, tallada en toba, se encontró dentro de esta osteria y hoy tiene su propio número de inventario en el Antiquarium; sin ella, esta casa se llamaría de cualquier otra manera. Tras el terremoto del año sesenta y dos, dos viviendas vecinas se unieron en una sola propiedad con bodega de vino, lagar y un triclinio de verano bajo pérgola.',
      'Se excavó en dos tandas, mil novecientos cincuenta y cuatro y mil novecientos cincuenta y ocho, y lo que salió a la luz fue en el fondo una explotación agrícola urbana: viña, prensa y taberna bajo un mismo techo, vendiendo el vino que ella misma producía sin intermediarios.',
      'Desde dos mil cinco, la viña que veis ahí se replantó siguiendo exactamente los huecos fosilizados de las raíces originales, con el mismo método que aplicó Wilhelmina Jashemski en tantos jardines de Pompeya. Bebéis, por así decirlo, del mismo trazado que hace dos mil años.',
    ],
    lookFor: ['La viña replantada según las raíces fosilizadas originales'],
    tips: ['Coordenadas aproximadas, tomadas del Orto dei Fuggiaschi vecino; no está en el circuito habitual, confirmad en taquilla.'],
  },
  'I-22': {
    coords: [40.7504429, 14.4907605],
    category: 'domus',
    illus: 'fresco',
    intro: 'Antes de entrar, deteneos en la fachada: ahí sigue pintado el anuncio de un espectáculo de gladiadores que nunca llegaréis a ver.',
    narration: [
      'El cartel, pintado en rojo, promociona unos juegos de gladiadores patrocinados por Lucio Valerio Primo, un augustal de la ciudad, y forma parte de las decenas de anuncios electorales y de espectáculos que cubrían las fachadas de Pompeya como si fueran carteleras. El nombre de Ceres con que se conoce la casa no está documentado en ninguna inscripción antigua: es una etiqueta moderna, y conviene decirlo así en lugar de darla por segura.',
      'Dentro, excavada en mil novecientos cincuenta y uno, la casa guarda cubículos con pintura de segundo estilo, la que imita arquitecturas de mármol antes de que se pusiera de moda pintar escenas con figuras. En el jardín, pequeñas estatuillas fuente de mármol seguían dando gracia al agua que corría entre los parterres.',
      'Es una de las pocas de este tramo que se visita en el circuito regular, así que aprovechad para fijaros en el contraste entre el cartel de fuera, dirigido a toda la calle, y la intimidad calculada del jardín de dentro.',
    ],
    lookFor: ['El edicto de gladiadores pintado en la fachada', 'Las estatuillas fuente de mármol en el jardín'],
    tips: ['Abierta en el circuito regular de visita.'],
  },
  'I-23': {
    coords: [40.7487467, 14.4901331],
    category: 'comercio',
    illus: 'domus',
    intro: 'Contad las tinas circulares hundidas en el suelo: quince en total, y ninguna otra casa de Pompeya conserva un taller de curtidor como este.',
    narration: [
      'Se excavó en mil ochocientos setenta y cuatro, no en tiempos recientes como a veces se repite, y sigue siendo la única curtiduría identificada con seguridad en toda la ciudad. Los grafitos hallados dentro apuntan a un tal Marco Vesonio Primo como propietario, un nombre que solo conocemos por esas rascaduras casuales en la pared.',
      'Curtir cuero en pleno centro urbano no era agradable: las tinas se llenaban de agua, cal y orina para ablandar y limpiar las pieles, un proceso que apestaba a la manzana entera. Aun así, alguien montó el negocio aquí, cerca de las tiendas y del tránsito de la Via dell\'Abbondanza, señal de que el olor no espantaba tanto a la clientela como cabría pensar.',
      'El mosaico del triclinio de esta casa, con una alegoría de la muerte, se llevó al Museo Arqueológico Nacional de Nápoles; lo que queda aquí son las quince tinas vacías, testigos mudos de un oficio que en Pompeya casi nadie más practicaba a esta escala.',
    ],
    lookFor: ['Las quince tinas cilíndricas hundidas en el suelo del taller'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'I-24': {
    coords: [40.7508392, 14.4917434],
    category: 'comercio',
    illus: 'anfora',
    intro: 'Fijaos en las seis tinajas medio enterradas bajo el pórtico: aquí se vendía garum, la salsa de pescado fermentado que Pompeya exportaba por todo el Mediterráneo.',
    narration: [
      'Conviene aclarar algo antes de nada: esta tienda no perteneció a Umbricio Escauro, el comerciante de garum más famoso de la ciudad, cuyo mosaico de verdad está junto a Porta Marina. La atribución que a veces circula sobre esta casa no tiene ninguna prueba que la sostenga, así que aquí hablamos de un productor sin nombre conocido.',
      'Excavada entre mil novecientos sesenta y mil novecientos sesenta y dos, la tienda conserva sus seis dolia semienterradas en el pórtico, donde fermentaba el pescado con sal durante semanas hasta convertirse en esa salsa que los romanos ponían en casi todos los platos. Se han encontrado ánforas con restos todavía identificables del producto.',
      'En la cocina, al fondo, hay un larario pintado, el pequeño altar donde el dueño pedía protección para un negocio que olía fuerte y rendía bien: el garum de Pompeya viajaba en barco hasta las mesas de medio imperio.',
    ],
    lookFor: ['Las seis tinajas semienterradas en el pórtico', 'El larario pintado en la cocina'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'I-25': {
    coords: [40.7497389, 14.4896687],
    category: 'domus',
    illus: 'domus',
    intro: 'Las herramientas que dieron nombre a esta casa no eran de herrero, sino de carpintero: catorce cinceles, una sierra y un compás salieron de aquí dentro.',
    narration: [
      'A pesar del nombre con que se conoce, casa del herrero, lo que se encontró en las excavaciones de mil novecientos catorce, mil novecientos veintisiete y mil novecientos treinta y tres fue el equipo completo de un carpintero: catorce cinceles, una sierra, compases y una regla plegable de un pie romano, herramientas que cualquier ebanista actual reconocería casi sin cambios.',
      'La casa formó parte en su día de la vecina Casa del Menandro, una de las viviendas más ricas de Pompeya, antes de independizarse como propiedad. De dos víctimas encontradas en ella se ha llegado a secuenciar el genoma completo, un dato que en los últimos años ha cambiado lo que sabemos sobre quién poblaba realmente estas casas.',
      'Buscad, si podéis acercaros, el grafito de amor rascado en una pared: Secundo se lo dedicó a Prima, dos nombres que sin esa frase se habrían perdido para siempre. La Casa del Menandro, con su plata y sus mosaicos, está a un paso de aquí.',
    ],
    lookFor: ['El grafito de amor de Secundo a Prima'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'I-26': {
    coords: [40.7505375, 14.490191],
    category: 'comercio',
    illus: 'domus',
    intro: 'Desde la calle, sin entrar, ya se adivina el oficio de este local: una tintorería que teñía telas para media Pompeya.',
    narration: [
      'El nombre de Terencio, con que a veces se llama a esta officina tintoria, no aparece documentado en ninguna fuente antigua: es una atribución de conveniencia, y conviene tratarla como tal. Lo que sí está probado es el oficio, gracias a las cubetas y a los restos de tinte hallados al excavar el edificio en mil novecientos treinta y siete.',
      'Una cisterna bajo el peristilo de la casa vecina abastecía de agua a la tintorería, prueba de que los negocios de Pompeya rara vez funcionaban en compartimentos estancos: paredes medianeras servían de acueducto informal entre una propiedad y otra. Parte del edificio contiguo se perdió en un bombardeo de mil novecientos cuarenta y tres, una herida de guerra que todavía se aprecia en la fábrica.',
      'Solo se puede ver desde la calle, así que aprovechad para imaginar el olor a mordiente y tinte que debía de llegar hasta la Via di Nola cada vez que se abría la puerta.',
    ],
    lookFor: ['Las cubetas de teñido visibles desde la calle'],
    tips: ['Solo se ve desde la calle; no tiene acceso al interior.'],
  },
  'I-27': {
    coords: [40.7504402, 14.4912304],
    category: 'domus',
    illus: 'lararium',
    intro: 'Levantad la vista al llegar al fondo del atrio: veréis arrancar una escalera hacia un piso superior que en la mayoría de las casas de Pompeya desapareció hace siglos.',
    narration: [
      'Esta casa conserva algo raro: un atrio testudinado, cubierto por un solo tejado a cuatro aguas sin abertura central, y sobre él una escalera que sube a habitaciones del primer piso pintadas todavía en cuarto estilo. De ahí el nombre con que se conoce, casa del primer piso, un dato tan literal como poco frecuente en el resto de la ciudad.',
      'La excavación, entre mil novecientos cincuenta y dos y mil novecientos cincuenta y siete, sacó a la luz un larario en el jardín con dos serpientes agatodemon pintadas, la pareja de guardianes domésticos que veréis repetida, con variantes, en decenas de casas pompeyanas.',
      'Subir con la mirada, ya que no se puede subir con los pies, y pensar que la mayor parte de Pompeya tuvo un segundo piso que el tiempo y los expolios se llevaron, y que aquí, por una vez, algo de esa altura ha sobrevivido.',
    ],
    lookFor: ['La escalera al primer piso', 'El larario del jardín con las dos serpientes'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'I-28': {
    coords: [40.7504402, 14.4912304],
    category: 'comercio',
    illus: 'domus',
    intro: 'Junto a la puerta, buscad el hueco donde encajaba la tranca de madera: cerraba un negocio de habitaciones para viajeros, no una vivienda familiar.',
    narration: [
      'El nombre de Saturnino con que se conoce este edificio es dudoso: las inscripciones de la fachada citan en realidad a Ceia y a Laureato, no a ningún Saturnino, así que lo más honesto es decir que el nombre no está bien resuelto. Lo que sí parece claro es la función: un hospitium con mostrador propio, un alojamiento de paso para quien llegaba a Pompeya sin casa donde quedarse.',
      'Se excavó entre mil novecientos cincuenta y dos y mil novecientos cincuenta y cuatro, y de nuevo en mil novecientos sesenta, pero aquella campaña nunca llegó a publicarse del todo, así que buena parte de lo que se sacó entonces sigue sin estudiar con detalle.',
      'Dentro se hallaron tres esqueletos junto a una copa de cerámica fina de terra sigillata, la vajilla de mesa más apreciada de la época: alguien, en los últimos momentos, tuvo tiempo de coger algo de valor antes de no poder salir.',
    ],
    lookFor: ['El hueco de la tranca de madera junto a la puerta'],
    tips: ['Coordenadas aproximadas, tomadas de un edificio cercano de la misma manzana; confirmad en taquilla si está abierta.'],
  },
  'I-29': {
    coords: [40.7509056, 14.4906838],
    category: 'domus',
    illus: 'domus',
    intro: 'Fijaos primero en el atrio, el corazón de casi cualquier casa romana: aquí se abre ancho, con la piscina central que recogía el agua de lluvia del tejado.',
    narration: [
      'Casa del atrio es un nombre puramente descriptivo, puesto en el siglo pasado por comodidad, sin que exista un dueño o un hallazgo que le diera un apodo más memorable. Y sin embargo esa misma sencillez la hace útil: aquí se puede explicar, sin distracciones de frescos famosos, cómo funcionaba realmente el corazón de una domus romana.',
      'El impluvium central recogía el agua que caía por las cuatro vertientes del tejado y la llevaba a una cisterna bajo el suelo, el sistema de abastecimiento doméstico más extendido de la ciudad, mucho antes de que el acueducto llegara a todas las casas. Alrededor, las habitaciones se abrían sin ventanas a la calle, mirando solo hacia dentro.',
      'Contad los pasos entre la puerta y el impluvium: en la mayoría de las casas pompeyanas esa distancia se calculaba para que quien entrara viera primero el agua, después el jardín al fondo, un efecto de perspectiva que el visitante de hoy sigue notando sin saber por qué.',
    ],
    lookFor: ['El impluvium central del atrio'],
    tips: ['Coordenadas aproximadas, tomadas de la insula vecina; confirmad en taquilla si está abierta.'],
  },
  'II-4': {
    coords: [40.7497718, 14.4953119],
    category: 'comercio',
    illus: 'foro',
    intro: 'Este descampado junto al anfiteatro no tiene columnas que fotografiar, pero durante siglos fue el mercado de ganado de Pompeya.',
    narration: [
      'Foro Boario significa exactamente eso: plaza del ganado, el lugar donde se compraban y vendían bueyes y otros animales de carga en las afueras de la ciudad, lejos del ajetreo más fino del foro civil. Su posición junto a la Palestra Grande y el anfiteatro no es casual: esta esquina de Pompeya concentraba las actividades ruidosas y de mucho espacio.',
      'No queda en pie ningún edificio que lo señale con claridad; es sobre todo una lectura del terreno, apoyada en fuentes antiguas, más que un monumento visitable en el sentido habitual. Aun así, conviene pararse un momento a imaginar el ruido de animales y tratantes justo donde hoy hacen cola los visitantes para entrar al anfiteatro.',
      'Pensad que Pompeya no era solo templos y casas pintadas: también necesitaba un sitio donde cerrar tratos de bueyes, y ese sitio estaba aquí, a un paso de donde miles de personas se sentaban a ver combates de gladiadores.',
    ],
    lookFor: ['El espacio abierto entre la Palestra Grande y el anfiteatro'],
    tips: ['No hay estructura visitable propiamente dicha; es una zona de paso identificada por los arqueólogos.'],
  },
  'II-7': {
    coords: [40.7520301, 14.4933501],
    category: 'domus',
    illus: 'domus',
    intro: 'Buscad la mesa de piedra bajo la pérgola del jardín: aquí se comía tumbado, al aire libre, en las noches de verano.',
    narration: [
      'El triclinio al aire libre da nombre a esta casa: un comedor de tres divanes de obra, dispuesto en el jardín y no dentro de una sala cerrada, pensado para las cenas de las noches cálidas, cuando comer bajo techo debía de parecer un desperdicio del buen tiempo napolitano.',
      'No es una solución única en Pompeya, pero sí una de las mejor conservadas: la estructura de obra imita en piedra los divanes de madera y tela que se usaban en los comedores interiores, con el desnivel justo para reclinarse con el codo apoyado en un cojín que ya no existe.',
      'Alrededor, el jardín hacía también de cocina en miniatura, con plantas aromáticas al alcance de la mano del cocinero. Cenar aquí, con vistas al peristilo y lejos del calor de la cocina cerrada, era probablemente uno de los pequeños lujos de esta casa mediana.',
    ],
    lookFor: ['El triclinio de obra bajo la pérgola del jardín'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'II-8': {
    coords: [40.7502266, 14.4930684],
    category: 'domus',
    illus: 'fresco',
    intro: 'En el jardín trasero busca una pintura de Hércules, el héroe que dio nombre a esta casa sin que sepamos por qué el dueño lo eligió a él.',
    narration: [
      'El jardín, más grande de lo habitual para una casa de este tamaño, conserva restos de pintura con el héroe griego, motivo bastante común en Pompeya como decoración de espacios al aire libre, junto a escenas de caza o de vendimia que solían acompañarlo.',
      'No hay ningún indicio de que el propietario tuviera una devoción especial por Hércules más allá del gusto decorativo: los repertorios mitológicos circulaban entre los pintores como catálogos, y un mismo taller podía repetir la misma escena en varias casas de la ciudad con pequeñas variaciones.',
      'Lo que sí distingue a esta casa es la proporción entre jardín y vivienda: aquí el verde ocupa casi tanto espacio como las habitaciones, una apuesta clara por el desahogo y la sombra frente a la estrechez de tantas domus vecinas.',
    ],
    lookFor: ['Los restos de pintura con Hércules en el jardín'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'II-9': {
    coords: [40.7495098, 14.4934419],
    category: 'puerta',
    illus: 'calle',
    intro: 'Poneos bajo el arco de la puerta y mirad hacia fuera: por aquí entraba el camino que venía de Nuceria, la ciudad vecina que le da nombre a esta entrada.',
    narration: [
      'Porta Nocera es una de las siete puertas que perforaban la muralla de Pompeya, la que miraba hacia el sureste, camino de Nuceria. Como el resto del recinto amurallado, combina tramos de distintas épocas, desde bloques de piedra caliza más antiguos hasta remiendos posteriores en opus incertum.',
      'Justo fuera de esta puerta se extiende una de las necrópolis de la ciudad, porque la ley romana prohibía enterrar dentro del recinto urbano: los muertos quedaban siempre a las afueras, junto a los caminos, para que quien entrara o saliera los tuviera presentes.',
      'Fijaos en la anchura del vano: apenas cabían dos carros cruzándose, prueba de que el tráfico de mercancías pesadas no era la prioridad de esta entrada concreta, más pensada para peatones y carga ligera que para las grandes caravanas del comercio.',
    ],
    lookFor: ['Los distintos tipos de aparejo en los tramos de muralla junto a la puerta'],
    tips: ['Acceso exterior; comprobad en taquilla si el tramo de muralla está incluido en el recorrido.'],
  },
  'II-11': {
    coords: [40.7495098, 14.4934419],
    category: 'domus',
    illus: 'lararium',
    intro: 'Buscad en la pared del jardín un larario rodeado de plantas pintadas: de esa guirnalda floral viene el nombre de esta casa.',
    narration: [
      'A diferencia del larario más sobrio, con solo las serpientes y el altar, este añade alrededor una orla de flores y hojas que lo distingue del resto de los santuarios domésticos de la ciudad, un capricho decorativo del pintor o un encargo expreso del dueño, no lo sabemos con certeza.',
      'Los lararios cumplían la misma función en todas las casas de Pompeya, ricas o modestas: eran el punto donde la familia hacía ofrendas diarias a los Lares, los dioses protectores del hogar, y a menudo también a los antepasados difuntos. Lo que cambiaba era el dinero invertido en decorarlos.',
      'Este, con sus flores pintadas, es un ejemplo de cómo un elemento tan repetido como un larario podía convertirse en la seña de identidad de una casa entera, hasta el punto de darle nombre siglos después de que se apagara el último rezo frente a él.',
    ],
    lookFor: ['La guirnalda floral pintada alrededor del larario'],
    tips: ['Coordenadas aproximadas, cerca de Porta Nocera; confirmad en taquilla si está abierta.'],
  },
  'III-2': {
    coords: [40.751648, 14.491614],
    category: 'servicio',
    illus: 'gladiador',
    intro: 'Este edificio bajo y sencillo cuenta, mejor que ningún cartel, lo frágil que sigue siendo Pompeya incluso hoy: se derrumbó entero en dos mil diez.',
    narration: [
      'La Schola Armaturarum era la sede de una asociación de jóvenes vinculada al entrenamiento con armas, una especie de club deportivo y social a la vez, con pinturas de trofeos militares en su fachada que todavía hoy se distinguen entre los andamios de la reconstrucción.',
      'El seis de noviembre de dos mil diez, tras días de lluvia intensa, el edificio se vino abajo de golpe, y las imágenes del derrumbe dieron la vuelta al mundo como símbolo del abandono que sufría el yacimiento en aquellos años. La noticia sacudió la gestión del parque y aceleró inversiones que hasta entonces se aplazaban una y otra vez.',
      'Lo que veis ahora es una reconstrucción cuidadosa, con la mayor cantidad posible de material original recuperado entre los escombros. Mirad las juntas entre ladrillo antiguo y ladrillo nuevo: ese contraste es, en cierto modo, el monumento más honesto que Pompeya tiene a su propia historia de negligencias y rescates in extremis.',
    ],
    lookFor: ['La diferencia entre el ladrillo original y el de la reconstrucción posterior a 2010'],
    tips: ['Confirmad en taquilla si el interior está accesible; a menudo solo se ve desde la calle.'],
  },
  'III-5': {
    coords: [40.7539854, 14.4909507],
    category: 'necropolis',
    illus: 'ceniza',
    intro: 'Fuera de la muralla, junto al camino de Nola, las tumbas se alinean donde la ley romana obligaba a dejarlas: lejos de los vivos, a la vista de todos.',
    narration: [
      'Enterrar dentro de la ciudad estaba prohibido en el mundo romano, así que cada puerta de Pompeya tenía junto a ella su propia hilera de sepulturas, pensadas para que quien entrara o saliera leyera los nombres de los difuntos como quien lee una fila de anuncios.',
      'Las tumbas de Porta Nola combinan monumentos funerarios de cierta altura, con inscripciones que resumían el cargo y los méritos del difunto, junto a sepulturas mucho más modestas, casi anónimas, apretadas entre las grandes. Esa mezcla es la fotografía más fiel que tenemos de cómo era realmente la sociedad pompeyana, no solo sus familias más ricas.',
      'Caminad despacio leyendo lo que queda legible en la piedra: cada nombre que sobrevive es, contra todo pronóstico, la única voz que le queda a alguien que hace dos mil años tuvo amigos, deudas y un oficio del que hoy solo sabemos una línea.',
    ],
    lookFor: ['Las inscripciones funerarias todavía legibles en los monumentos más altos'],
    tips: ['Acceso exterior a la muralla; confirmad en taquilla si el tramo está incluido en el recorrido del día.'],
  },
  'V-1': {
    coords: [40.7528446, 14.4884573],
    category: 'espectaculo',
    illus: 'gladiador',
    intro: 'No confundáis este cuartel con el más famoso junto a los teatros: Pompeya tuvo más de un lugar donde alojar y entrenar a sus gladiadores.',
    narration: [
      'Menos visitado que el gran cuadripórtico del sur, este conjunto de la Regio V cumplía una función parecida a escala más modesta: alojamiento y espacio de entrenamiento para hombres cuyo oficio era luchar en público para entretenimiento ajeno, casi siempre esclavos o prisioneros de guerra sin ninguna capacidad de elegir su destino.',
      'La vida de un gladiador combinaba entrenamiento duro, disciplina de cuartel y, para los que ganaban fama, una popularidad casi de estrella que contrastaba con su condición legal, a menudo la más baja de la sociedad romana. Los grafitos hallados en cuarteles como este hablan de victorias, de admiradoras y de apuestas, más que de cualquier gloria abstracta.',
      'Pensad en la distancia entre este edificio funcional y el gran anfiteatro donde esos mismos hombres se jugaban la vida: entre uno y otro estaba toda la maquinaria de un espectáculo que movía dinero, política y pasiones populares en igual medida.',
    ],
    lookFor: ['Los restos de las celdas o dormitorios alineados del cuartel'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'V-4': {
    coords: [40.7520709, 14.4860788],
    category: 'domus',
    illus: 'fresco',
    intro: 'En el larario de esta casa hay un relieve de piedra que muestra el Templo de Júpiter viniéndose abajo: el terremoto del año sesenta y dos, contado por quien lo vivió.',
    narration: [
      'Lucio Cecilio Jocundo era banquero, y de él conservamos algo excepcional para la Antigüedad: un archivo de más de ciento cincuenta tablillas de cera con recibos de subastas y cobros, encontrado dentro de un arcón en esta misma casa. Gracias a esos documentos sabemos nombres, cantidades y fechas concretas de operaciones financieras reales de Pompeya.',
      'Su busto de bronce, con un rostro de rasgos marcados que algunos han querido leer como caricatura, decoraba el atrio, y hoy es una de las caras más reproducidas de todo el yacimiento. En el larario del jardín, dos relieves narran el terremoto del año sesenta y dos, con el Templo de Júpiter y el arco del foro derrumbándose entre columnas partidas.',
      'Esos relieves son la prueba visual más antigua que existe de aquel seísmo, encargados quizá por el propio Jocundo para dar gracias por haber sobrevivido. Diecisiete años después, el mismo tipo de catástrofe, mucho mayor, acabaría con la ciudad entera.',
    ],
    lookFor: ['El relieve del terremoto en el larario', 'El rostro del busto de Cecilio Jocundo'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'V-5': {
    coords: [40.7534461, 14.4838403],
    category: 'necropolis',
    illus: 'ceniza',
    intro: 'Bajo la sombra del Vesubio que se adivina al fondo, esta hilera de tumbas se alinea junto al camino que subía hacia el volcán que acabaría con la ciudad.',
    narration: [
      'Porta Vesuvio tomó su nombre del volcán hacia el que apuntaba el camino que salía por ella, y su necrópolis conserva la misma mezcla que todas las de Pompeya: monumentos de familias acomodadas junto a sepulturas humildes, todos expuestos igual al paso de quien entraba o salía de la ciudad.',
      'Hay algo inquietante en visitar una necrópolis con el propio Vesubio como telón de fondo, sabiendo que ninguno de los enterrados aquí antes del setenta y nueve podía imaginar que la montaña que veían cada día terminaría por matar a sus descendientes en una sola tarde.',
      'Fijaos en la orientación de las tumbas hacia el camino, nunca hacia el campo: querían ser vistas, ser leídas, seguir formando parte de la vida de la ciudad aunque ya no pudieran participar en ella.',
    ],
    lookFor: ['La vista del Vesubio desde la línea de tumbas'],
    tips: ['Acceso exterior a la muralla; confirmad en taquilla si el tramo está incluido en el recorrido del día.'],
  },
  'V-8': {
    coords: [40.7522771, 14.4858497],
    category: 'domus',
    illus: 'domus',
    intro: 'Esta casa de nombre tan sencillo como del jardín forma parte del tramo de la Regio V que se excava y se estudia todavía hoy, con hallazgos que van cambiando el mapa cada temporada.',
    narration: [
      'Buena parte de esta zona de Pompeya, al norte del eje principal, se excavó bastante después que el resto de la ciudad, y algunas insulae siguen en proceso de estudio, con equipos internacionales trabajando por campañas. Por eso encontraréis aquí menos carteles explicativos y más andamios que en el sector monumental del sur.',
      'El nombre de la casa, del jardín, es tan genérico como el de tantas otras viviendas de esta manzana: describe lo que se ve, sin apodo de propietario ni hallazgo célebre que la distinga. Y sin embargo, precisamente por eso, sirve para entender cómo era la Pompeya menos fotografiada, la de las casas medianas sin fresco de postal.',
      'Si seguís caminando hacia el norte por este sector, veréis con qué rapidez cambia el paisaje: de las calles empedradas y restauradas a tramos todavía en tierra, donde la excavación sigue en marcha ante vuestros ojos.',
    ],
    lookFor: ['El contraste entre las zonas restauradas y las todavía en excavación de este sector'],
    tips: ['Coordenadas aproximadas, dentro de la misma insula; confirmad en taquilla si está abierta.'],
  },
  'V-9': {
    coords: [40.7524966, 14.4865468],
    category: 'domus',
    illus: 'domus',
    intro: 'El nombre de Orión suena a mito clásico, pero no está probado qué relación real tiene esta casa poco excavada con el cazador de las estrellas.',
    narration: [
      'A diferencia de las grandes domus del centro de Pompeya, muchas viviendas de este tramo norte de la Regio V conservan aún más preguntas que respuestas: se conoce su planta general, pero no siempre el motivo exacto de un nombre moderno como este, puesto por los primeros excavadores según algún detalle decorativo hoy perdido o mal documentado.',
      'Conviene no rellenar ese vacío con una historia bonita pero inventada. Lo honesto es decir que la casa forma parte del entramado denso de viviendas medianas que rodeaba a las más lujosas, como la vecina Casa de las Bodas de Plata, sin competir con ella en riqueza pero compartiendo manzana y probablemente vida de vecindad.',
      'Fijaos, si el acceso lo permite, en el trazado de las habitaciones alrededor del atrio: incluso sin fresco famoso que enseñar, la lógica de circulación de una casa romana se lee igual de bien aquí que en la más rica del barrio.',
    ],
    lookFor: ['El trazado del atrio y las habitaciones que lo rodean'],
    tips: ['Coordenadas aproximadas, junto a la Casa de las Bodas de Plata; confirmad en taquilla si está abierta.'],
  },
  'V-10': {
    coords: [40.7522771, 14.4858497],
    category: 'domus',
    illus: 'fresco',
    intro: 'En lugar de escenas mitológicas, las paredes de esta casa llevaban versos griegos pintados: poesía de verdad, no solo decoración.',
    narration: [
      'De ahí viene el nombre, casa de los epigramas: pequeños poemas de tradición helenística, copiados o adaptados en las paredes, en un gesto poco frecuente que delata a un propietario con gusto literario, o al menos con ganas de que sus visitas lo creyeran así.',
      'Los epigramas griegos eran breves, ingeniosos, a menudo con un giro final sorprendente, y circulaban en antologías que cualquier persona instruida del Mediterráneo oriental podía conocer. Encontrarlos pintados en una casa pompeyana demuestra hasta qué punto la cultura griega seguía siendo el modelo de prestigio para las élites romanas, incluso en una ciudad de provincias como esta.',
      'Buscad, si la conservación lo permite, el punto donde el texto pintado se vuelve ilegible: la mayoría de estos epigramas se conocen hoy solo por copias hechas en el siglo diecinueve, antes de que la pintura siguiera perdiéndose con el paso del tiempo.',
    ],
    lookFor: ['Los restos de texto griego pintado en las paredes'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'V-11': {
    coords: [40.7525371, 14.4858869],
    category: 'domus',
    illus: 'fresco',
    intro: 'Seguid con el dedo, en la pintura de esta casa, una línea de tallos y hojas que se enrosca sobre sí misma sin cortarse nunca: eso es un girali.',
    narration: [
      'Girali es el nombre que dan los arqueólogos italianos a esos motivos de vegetación que serpentean por paredes y frisos, roleos vegetales que imitaban la talla en piedra o estuco de los edificios más lujosos, trasladada aquí a la pintura por ser más barata que el relieve real.',
      'Esta casa debe su nombre a la abundancia de ese motivo decorativo en sus paredes, un recurso que los pintores de Pompeya dominaban hasta el punto de improvisar variaciones sin perder nunca el ritmo de la curva. Es una decoración que envejece bien: incluso deslucida por el tiempo, la línea del roleo sigue siendo reconocible.',
      'Fijaos en los pequeños animales o figuras que a veces se esconden entre las hojas pintadas, casi un juego visual del pintor para quien se detuviera a mirar de cerca en lugar de pasar de largo, exactamente lo que estáis haciendo ahora.',
    ],
    lookFor: ['Los roleos vegetales pintados en las paredes', 'Las figuras pequeñas escondidas entre las hojas'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'V-12': {
    coords: [40.7524377, 14.4860042],
    category: 'domus',
    illus: 'lararium',
    intro: 'Casi todas las casas de Pompeya tenían uno, pero en esta el larario ocupa tanto protagonismo que terminó dándole nombre al edificio entero.',
    narration: [
      'Un larario era el altar doméstico donde la familia hacía ofrendas a los Lares, los espíritus protectores del hogar, casi siempre representados como jóvenes danzantes con un cuerno de la abundancia, junto a la serpiente agatodemon que simbolizaba la fertilidad de la tierra y del propio hogar.',
      'En la mayoría de las casas el larario es un rincón discreto, una hornacina pequeña cerca de la cocina. Aquí, en cambio, ocupa un lugar tan destacado dentro de la vivienda que los primeros excavadores no encontraron mejor manera de nombrar la casa que por ese altar, sin apodo de propietario ni hallazgo llamativo que lo sustituyera.',
      'Pensad en el gesto diario que implicaba: cada mañana, alguien de la casa dejaba aquí una ofrenda pequeña, vino o incienso, un ritual tan rutinario como para nosotros encender la cafetera, y sin embargo cargado de un sentido religioso que hoy nos cuesta imaginar del todo.',
    ],
    lookFor: ['El larario central de la casa, más grande de lo habitual'],
    tips: ['Coordenadas aproximadas, dentro de la misma insula; confirmad en taquilla si está abierta.'],
  },
  'VI-5': {
    coords: [40.7514752, 14.4837979],
    category: 'comercio',
    illus: 'termopolio',
    intro: 'Otro mostrador con tinajas encajadas, esta vez en la Via Consolare, la calle que salía de Pompeya hacia el norte, camino de Nápoles.',
    narration: [
      'Los thermopolia no eran restaurantes en el sentido moderno: eran mostradores de calle donde comprar algo rápido, de pie, sin mesa ni mantel, el equivalente romano a un puesto de comida callejera. Este, en la Via Consolare, servía sobre todo a quien entraba o salía de la ciudad por la cercana Porta Ercolano, sin tiempo para sentarse a comer con calma.',
      'Las tinajas encastradas en el mostrador guardaban líquidos y alimentos que se mantenían frescos gracias a la propia obra de fábrica, más que por cualquier sistema de refrigeración; el barro y la piedra hacían de aislante natural en los meses de más calor.',
      'Contad cuántos mostradores de este tipo habéis visto ya en el recorrido de hoy: Pompeya tenía docenas repartidos por toda la ciudad, uno cada pocas manzanas, la prueba de que comer fuera de casa era una costumbre tan romana como cualquier banquete de postín.',
    ],
    lookFor: ['Las tinajas encastradas en el mostrador de obra'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-7': {
    coords: [40.7509649, 14.4828052],
    category: 'comercio',
    illus: 'pan',
    intro: 'Buscad la muela circular de piedra volcánica junto al horno: la movía una mula en círculos, ciega, durante horas, para moler el grano de todo el barrio.',
    narration: [
      'El horno abovedado de esta panadería, muy parecido al que veréis en otras de la ciudad, se calentaba con leña metida por una boca lateral, y el pan se cocía directamente sobre la solera de piedra, dejando marcas que los arqueólogos han podido identificar incluso en panes carbonizados hallados en otros hornos de Pompeya.',
      'Las muelas de piedra volcánica, en forma de reloj de arena, molían el grano gracias a la fuerza de un animal enganchado a un brazo de madera que giraba sin parar; el trabajo era tan duro que a menudo se confiaba a mulas o a esclavos, nunca a mano libre de una sola persona.',
      'Imaginad el ruido y el calor de este rincón antes del amanecer, cuando el panadero encendía el horno para tener el pan listo a la hora en que la ciudad empezaba a moverse: Pompeya, como cualquier ciudad romana, olía a pan recién hecho mucho antes de oler a nada más.',
    ],
    lookFor: ['La muela de piedra en forma de reloj de arena', 'La boca del horno abovedado'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-9': {
    coords: [40.7516727, 14.4832976],
    category: 'domus',
    illus: 'fresco',
    intro: 'En una de las salas de esta casa, Adonis yace pintado con la pierna herida, mientras Venus se inclina sobre él: una escena de amor y muerte que da nombre a la vivienda.',
    narration: [
      'El mito era muy popular entre los pintores de Pompeya: Adonis, el joven amado por Venus, muere corneado por un jabalí durante una cacería, y la diosa llega demasiado tarde para salvarlo. La escena permitía combinar cuerpos idealizados, dramatismo y un punto de melancolía elegante, justo lo que buscaban los propietarios de casas de cierto nivel.',
      'No hace falta creer en los dioses para entender por qué esta historia se repetía tanto: hablaba de un amor imposible de proteger del todo, un tema que atravesaba clases sociales y siglos sin perder fuerza, tan válido en el año setenta y nueve como en cualquier otra época.',
      'Fijaos en el gesto de las manos de Venus sobre el cuerpo de Adonis, más que en la herida misma: ahí está, si el pintor era bueno, la verdadera emoción de la escena, no en la sangre sino en el cuidado inútil que llega tarde.',
    ],
    lookFor: ['La escena pintada de Venus junto a Adonis herido'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-13': {
    coords: [40.7526832, 14.484774],
    category: 'domus',
    illus: 'columna',
    intro: 'En el jardín de esta casa hay un altar de obra tan grande que parece un pequeño monumento público metido a la fuerza en una vivienda privada.',
    narration: [
      'De ese altar descomunal, decorado con relieves, viene el nombre de la casa, ara máxima, un término que en Roma designaba también el gran altar dedicado a Hércules en el Foro Boario de la propia capital. Aquí, en Pompeya, alguien quiso un eco doméstico de ese prestigio religioso, a una escala que ninguna otra casa de la ciudad se permitió.',
      'Levantar un altar así en un jardín privado no era solo devoción: era también una forma de exhibir recursos, de convertir el culto familiar en un espectáculo que cualquier visita notaba nada más entrar. La religión doméstica romana tenía mucho de escaparate, y esta casa lo demuestra sin disimulo.',
      'Fijaos en la desproporción entre el tamaño del altar y el de la casa que lo rodea: es como si el jardín entero se hubiera construido alrededor de esa sola pieza, y no al revés.',
    ],
    lookFor: ['El gran altar de obra decorado con relieves en el jardín'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-15': {
    coords: [40.7526256, 14.4843524],
    category: 'domus',
    illus: 'fresco',
    intro: 'El nombre de esta casa no viene de la Antigüedad, sino de una visita real de finales del siglo diecinueve que la puso de moda entre los estudiosos.',
    narration: [
      'Casa del Príncipe de Nápoles se llama así por la visita de un miembro de la familia real italiana durante las excavaciones, un gesto habitual en la Pompeya decimonónica, cuando descubrir una casa nueva era también un acontecimiento social que merecía una visita ilustre y un nombre a la altura.',
      'Más allá de la anécdota del bautizo, la casa conserva un atrio elegante y pinturas de cuarto estilo bien conservadas, con esa mezcla de arquitecturas fingidas y paneles de color que se puso de moda en las últimas décadas de vida de la ciudad, después del terremoto del año sesenta y dos.',
      'Fijaos en el contraste entre el nombre, que suena a anécdota cortesana, y la sobriedad real de la decoración: casi ninguna casa de Pompeya se llama hoy como la llamaron sus propios dueños, y esta es un buen recordatorio de hasta qué punto los nombres que usamos son cosa nuestra, no suya.',
    ],
    lookFor: ['Las pinturas de cuarto estilo del atrio'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-17': {
    coords: [40.7523434, 14.4800602],
    category: 'necropolis',
    illus: 'ceniza',
    intro: 'Salid por Porta Ercolano y caminad despacio: a ambos lados de la calzada se alinean las tumbas más monumentales de toda Pompeya.',
    narration: [
      'A diferencia de otras necrópolis de la ciudad, más discretas, la de Porta Ercolano concentra los monumentos funerarios de algunas de las familias más ricas de Pompeya, con exedras semicirculares para sentarse a conversar junto a la tumba y altares decorados con guirnaldas talladas en piedra.',
      'Aquí se enterró, entre otros, la sacerdotisa Mamia, con un monumento en forma de exedra que todavía domina un tramo entero de la calzada, y varios libertos enriquecidos que usaron sus tumbas para dejar en piedra lo que la sociedad romana les negaba en vida: un lugar de honor bien visible.',
      'Caminad hasta el final de la hilera y girad para mirar hacia la ciudad: esta misma vista, calzada, tumbas y murallas al fondo, es la que tuvieron generaciones enteras de pompeyanos cada vez que volvían a casa desde Herculano.',
    ],
    lookFor: ['El monumento en exedra de la sacerdotisa Mamia', 'Las guirnaldas talladas en los altares funerarios'],
    tips: ['Acceso exterior a la muralla; confirmad en taquilla si el tramo está incluido en el recorrido del día.'],
  },
  'VI-23': {
    coords: [40.7518, 14.4856],
    category: 'domus',
    illus: 'fresco',
    intro: 'Buscad, si la pintura lo permite, la figura de un músico rodeado de animales que se acercan mansos a escuchar: es Orfeo, el que amansaba fieras con la lira.',
    narration: [
      'El mito de Orfeo, el músico capaz de encantar a los animales y hasta de convencer a los dioses del inframundo, era un motivo habitual en la decoración pompeyana, sobre todo en salas donde se recibía a las visitas y convenía dejar una impresión culta sin necesidad de explicar demasiado.',
      'No conocemos el nombre de quien encargó esta pintura ni el motivo exacto por el que eligió esta escena en concreto entre todo el repertorio mitológico disponible, y conviene no inventar una razón que no está documentada. Lo que sí sabemos es que la casa entera tomó su nombre de esta única imagen.',
      'Fijaos en los animales que rodean a Orfeo, si se distinguen: los pintores solían variar las especies de un encargo a otro, casi como una firma discreta, un detalle que distingue esta versión del mito de cualquier otra pintada en la ciudad.',
    ],
    lookFor: ['La figura de Orfeo con la lira rodeado de animales'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-24': {
    coords: [40.7501549, 14.4831099],
    category: 'domus',
    illus: 'domus',
    intro: 'El nombre de esta casa promete estanterías de rollos de papiro, pero lo cierto es que no está del todo claro qué llevó a llamarla así.',
    narration: [
      'Casa de la Biblioteca es un nombre puesto por los primeros excavadores, probablemente por algún hallazgo o alguna estancia que interpretaron como espacio de lectura o archivo, aunque el registro exacto de ese hallazgo no siempre se conservó con el detalle que nos gustaría tener hoy. Conviene, de nuevo, no dar por seguro más de lo que la evidencia sostiene.',
      'Tener libros en casa, en el sentido de rollos de papiro o pergamino, era en Pompeya un signo claro de estatus y de educación, algo reservado a familias con recursos y con tiempo para el ocio intelectual, muy lejos de la alfabetización básica que sí compartían comerciantes y tenderos para llevar sus cuentas.',
      'Está muy cerca de la Casa del Brazalete de Oro, una de las viviendas más ricas de este tramo de la muralla: si el nombre de biblioteca tiene algo de verdad, encaja con un vecindario de familias que podían permitirse ese lujo silencioso.',
    ],
    lookFor: ['La disposición de las habitaciones que dio origen al nombre de la casa'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VI-27': {
    coords: [40.7521372, 14.4834857],
    category: 'domus',
    illus: 'fresco',
    intro: 'Esta casa tiene algo que casi ninguna otra de Pompeya se permitió: dos atrios completos bajo un mismo techo, como si fueran dos casas fundidas en una.',
    narration: [
      'Un atrio tuscánico y otro tetrástilo, con cuatro columnas sosteniendo el hueco central, conviven aquí en lo que originalmente pudo ser la fusión de dos viviendas samnitas más antiguas, de una época anterior a la colonia romana que Pompeya se convirtió después del año ochenta antes de nuestra era.',
      'El nombre de la casa viene de la figura de un centauro, mitad hombre y mitad caballo, encontrada o pintada en su interior; un motivo decorativo menos frecuente que otros mitos griegos, lo que hizo que se quedara como seña de identidad del edificio entero.',
      'Recorred los dos atrios seguidos y fijaos en cómo cambia la luz de uno a otro, según el tamaño del hueco superior: es la manera más clara de entender, sin necesidad de plano, que estáis caminando por dos casas que un día decidieron dejar de serlo por separado.',
    ],
    lookFor: ['Los dos atrios distintos bajo el mismo techo'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VII-3': {
    coords: [40.7495105, 14.4837142],
    category: 'domus',
    illus: 'domus',
    intro: 'Cerca de Porta Marina, por donde entraba el aire y la gente que venía del puerto, esta casa lleva un nombre que huele a mar sin que sepamos bien por qué.',
    narration: [
      'Casa del Marinero es, como tantos nombres de este tipo, una etiqueta puesta por los excavadores a partir de algún detalle hoy difícil de precisar con seguridad, quizá un grafito, quizá una pintura perdida con el tiempo. En una ciudad portuaria como Pompeya, con su río Sarno navegable hasta cerca de las murallas, no faltaban marineros ni comerciantes llegados por mar.',
      'Esta parte de la ciudad, pegada a Porta Marina, concentraba a quienes vivían del tráfico entre el puerto y el interior: transportistas, changadores, taberneros que atendían a marineros de paso. La vida aquí debía de tener un ritmo distinto, marcado por las mareas de mercancías más que por el calendario cívico del foro.',
      'Bajad la vista hacia la pendiente de la calle en dirección al mar: por esa misma cuesta subían, cargados, quienes traían del puerto ánforas de vino, aceite y garum para vender en la ciudad alta.',
    ],
    lookFor: ['La pendiente de la calle hacia Porta Marina'],
    tips: ['Coordenadas aproximadas, tomadas de la misma insula; confirmad en taquilla si está abierta.'],
  },
  'VII-4a': {
    coords: [40.74888, 14.4840306],
    category: 'domus',
    illus: 'fresco',
    intro: 'En una de las salas, Triptólemo sube a un carro tirado por serpientes aladas, listo para repartir el trigo por el mundo entero.',
    narration: [
      'El mito cuenta que Deméter, la diosa del grano, enseñó a Triptólemo el arte de la agricultura y le entregó un carro alado para que difundiera el cultivo del trigo entre los pueblos que aún no lo conocían, una escena que combina agradecimiento agrícola y viaje heroico a partes iguales.',
      'No es casualidad que este mito apareciera en casas pompeyanas: la región vivía en buena parte del comercio de grano y de los productos de una tierra volcánica extraordinariamente fértil, así que una escena sobre el origen divino de la agricultura tenía un eco muy directo para cualquier propietario local.',
      'Fijaos en las serpientes que tiran del carro, más que en la figura de Triptólemo: los pintores solían lucirse en esos detalles secundarios, convencidos de que el ojo del visitante se entretendría ahí antes de reconocer la escena completa.',
    ],
    lookFor: ['El carro de serpientes aladas de Triptólemo'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VII-4b': {
    coords: [40.748829, 14.4838464],
    category: 'domus',
    illus: 'fresco',
    intro: 'La loba de Roma, con Rómulo y Remo mamando debajo, está pintada en esta casa con más detalle del que veréis en cualquier moneda o estatua conocida.',
    narration: [
      'Es la misma leyenda fundacional que ya habréis visto perdida en el rótulo de una taberna cercana, pero aquí sobrevive con claridad suficiente para distinguir a la loba, atenta y protectora, y a los dos gemelos abandonados que ella decide alimentar en lugar de devorar.',
      'Pintar el mito de Roma en una casa de Pompeya no era un gesto neutro: recordaba a cualquier visita que esta ciudad, aunque provincial, formaba parte de la misma historia que se contaba en la capital del imperio, la misma loba, los mismos fundadores.',
      'Comparad mentalmente esta pintura con la que apenas se adivina en la taberna de Sotérico, unas calles atrás: dos versiones de la misma escena, una casi perdida y otra todavía legible, dos maneras de sobrevivir que tuvo el mismo mito durante dos mil años.',
    ],
    lookFor: ['La loba amamantando a Rómulo y Remo'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VII-6b': {
    coords: [40.7494612, 14.484267],
    category: 'servicio',
    illus: 'foro',
    intro: 'Esta losa de piedra con agujeros de tamaños distintos no es decoración: era la báscula oficial de la ciudad, donde se comprobaba que nadie os engañara al pesar.',
    narration: [
      'La Mensa Ponderaria, junto al Foro, tenía una serie de cavidades cilíndricas de capacidad exactamente calibrada, en las que los inspectores municipales comprobaban que las medidas de grano, aceite o vino que usaban los comerciantes coincidieran con el patrón oficial de la ciudad.',
      'No era un trámite decorativo: falsear una medida era un fraude que afectaba directamente a la confianza del mercado, y una ciudad que vivía del comercio como Pompeya necesitaba un patrón público, visible junto al edificio de gobierno, al que cualquiera pudiera acudir a comparar.',
      'Fijaos en el tamaño decreciente de los huecos, de mayor a menor: ese orden, tan simple, es en realidad uno de los primeros sistemas métricos estandarizados que se conservan físicamente, no solo descritos en un texto antiguo.',
    ],
    lookFor: ['Los huecos cilíndricos de distinto tamaño en la losa de piedra'],
    tips: ['Suele verse desde el recorrido del foro; confirmad en taquilla el acceso exacto.'],
  },
  'VII-19': {
    coords: [40.7506333, 14.4863349],
    category: 'domus',
    illus: 'mosaico',
    intro: 'Antes de entrar, bajad la vista al umbral: un mosaico muestra un oso herido por una jabalina, la imagen que da nombre a toda la casa.',
    narration: [
      'Las escenas de caza en el umbral cumplían una función parecida a la de los famosos perros mosaico de otras casas pompeyanas: anunciar algo sobre el carácter del dueño, en este caso quizá una afición real a la caza, o simplemente el gusto por una imagen dramática en el primer punto que veía cualquier visita.',
      'El oso, herido pero todavía en pie, con el asta clavada en el cuerpo, transmite una violencia contenida que los mosaístas romanos sabían capturar con pocas teselas bien colocadas, sin necesidad de más color que el blanco y negro.',
      'Pisar justo sobre esa imagen al entrar era, para los romanos, parte del ritual de bienvenida: el mosaico del suelo hablaba antes que el dueño de la casa, y aquí lo que decía era claro, esto es una casa de gente que no se asusta con facilidad.',
    ],
    lookFor: ['El mosaico del oso herido en el umbral de entrada'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VII-24': {
    coords: [40.750767, 14.4853005],
    category: 'domus',
    illus: 'fresco',
    intro: 'En una sala de esta casa, Ariadna duerme sola en la playa de Naxos, sin saber todavía que su amante Teseo acaba de abandonarla en un barco que ya no se ve.',
    narration: [
      'El mito era uno de los favoritos de la pintura romana: Ariadna, tras ayudar a Teseo a escapar del laberinto de Creta, es abandonada por él mientras duerme, y solo al despertar descubrirá que la nave se ha ido sin ella. Poco después llegará Baco, que la hará su esposa, pero los pintores casi siempre elegían congelar el momento de mayor soledad, justo antes del rescate.',
      'Esta casa se conoce también por sus capiteles pintados de colores, un detalle arquitectónico poco frecuente que algunos catálogos usan como nombre alternativo. Entre la Ariadna dormida y esos capiteles, la vivienda deja claro que su dueño invertía en detalles que otros propietarios pasaban por alto.',
      'Fijaos en la postura de Ariadna, con un brazo caído: es casi idéntica a una escultura clásica muy copiada en la Antigüedad, la Ariadna dormida, señal de que el pintor trabajaba a partir de modelos ya famosos en su época, no de su propia imaginación.',
    ],
    lookFor: ['La escena pintada de Ariadna dormida', 'Los capiteles pintados de colores'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VII-25': {
    coords: [40.7499657, 14.4831525],
    category: 'domus',
    illus: 'domus',
    intro: 'Cerca de Porta Marina, esta casa lleva el nombre de un tal Castricio del que apenas sabemos nada más que ese nombre.',
    narration: [
      'El apellido Castricio aparece en algún hallazgo epigráfico asociado al edificio, pero no hay datos firmes sobre su cargo, su oficio o su relación exacta con la propiedad; lo más honesto es tratarlo como un nombre de conveniencia, útil para localizar la casa en los planos, no como una biografía documentada.',
      'Esta zona cercana a Porta Marina, en pendiente hacia el mar, concentraba viviendas que aprovechaban el desnivel para ganar plantas hacia abajo, con terrazas y miradores que debían de ofrecer vistas al golfo antes de que los edificios modernos de Torre Annunziata cambiaran el paisaje para siempre.',
      'Si la pendiente de la calle os cuesta al subir, pensad que los pompeyanos de esta zona la recorrían a diario cargados de agua, de compra o de ambas cosas, sin más ayuda que sus propias piernas.',
    ],
    lookFor: ['El desnivel de la calle hacia Porta Marina'],
    tips: ['Coordenadas aproximadas, tomadas de la casa vecina; confirmad en taquilla si está abierta.'],
  },
  'VII-26': {
    coords: [40.7505159, 14.4867087],
    category: 'domus',
    illus: 'domus',
    intro: 'El nombre de esta casa viene de Marco Cesio Blando, conocido gracias a un sello de bronce hallado entre sus paredes.',
    narration: [
      'Un sello personal como el suyo servía para estampar la firma en documentos o mercancías, el equivalente romano a una rúbrica, y es prácticamente el único rastro seguro que tenemos de este hombre: ni su oficio ni el resto de su biografía han llegado hasta nosotros con la misma claridad que su nombre.',
      'Casas como esta, de tamaño mediano y sin frescos que hayan hecho historia del arte, forman la mayoría silenciosa de Pompeya: no las visita ninguna guía de las gruesas, pero sumadas cuentan mucho mejor cómo vivía la ciudad entera que las pocas mansiones que sí aparecen en todos los libros.',
      'Fijaos en la sencillez del atrio, sin más adorno que el enlucido liso: Cesio Blando, quienquiera que fuese, no necesitaba impresionar a nadie con su casa para tener un lugar reconocido en su barrio.',
    ],
    lookFor: ['La sencillez del atrio sin decoración añadida'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VII-27': {
    coords: [40.7503152, 14.4867248],
    category: 'domus',
    illus: 'domus',
    intro: 'Levantad la vista hacia la calle: aquí se conserva uno de los pocos balcones de madera que sobresalían sobre las aceras estrechas de Pompeya.',
    narration: [
      'La mayoría de las casas pompeyanas tuvo alguna vez un piso superior con balcones o galerías de madera que ganaban espacio sobre la calle, pero casi todos desaparecieron con el incendio y el derrumbe del setenta y nueve, o se perdieron después por el expolio de la madera reutilizable. Este balcón colgante es una de las pocas referencias que ha permitido reconstruir cómo era esa parte alta, invisible, de la ciudad.',
      'Vivir con un balcón así sobre una calle estrecha significaba ganar una habitación extra sin ocupar suelo, a costa de ensombrecer el tramo de calzada de debajo; los vecinos de enfrente debían de conocerse casi tan bien como los de la misma casa, con las conversaciones subiendo y bajando de piso a piso.',
      'Imaginad el ruido de la calle llegando amortiguado hasta ese balcón, la ropa tendida, quizá una maceta: el detalle doméstico que ninguna pintura registra pero que la arqueología, a través de agujeros y vigas fosilizadas, consigue devolvernos igualmente.',
    ],
    lookFor: ['La estructura del balcón colgante sobre la calle'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VIII-4': {
    coords: [40.7483552, 14.4851951],
    category: 'domus',
    illus: 'domus',
    intro: 'Esta casa lleva el nombre de un general francés que nunca vivió en Pompeya, pero que la sacó a la luz mientras gobernaba Nápoles durante unos meses de mil setecientos noventa y nueve.',
    narration: [
      'Jean-Étienne Championnet ocupó Nápoles al frente de las tropas revolucionarias francesas y, en el breve tiempo de la República Partenopea, impulsó excavaciones en Pompeya como parte del prestigio cultural que todo gobernante de la época quería asociar a su nombre. La casa quedó bautizada así en su honor, aunque su gobierno duró apenas unos meses antes de la restauración borbónica.',
      'Es un buen recordatorio de que la historia de las excavaciones de Pompeya no es solo la historia romana que se enseña dentro: también es la historia de los siglos dieciocho y diecinueve, de reyes, generales y académicos que se disputaban el prestigio de sacar a la luz cada nueva casa.',
      'Fijaos en que el nombre nada tiene que ver con quien vivió aquí en el año setenta y nueve: como en tantos otros casos de este plano, la etiqueta que usamos hoy pertenece a quien la excavó, no a quien la habitó.',
    ],
    lookFor: ['La disposición general de la casa, típica de las excavaciones de finales del siglo dieciocho'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VIII-5': {
    coords: [40.7483552, 14.4851951],
    category: 'domus',
    illus: 'mosaico',
    intro: 'Bajad la vista al suelo nada más entrar: figuras geométricas en blanco y negro se repiten habitación tras habitación, sin una sola escena narrativa.',
    narration: [
      'Frente a los mosaicos con escenas de caza, dioses o animales que veréis en otras casas, este suelo apuesta todo a la geometría pura: rombos, trenzados y tableros de ajedrez que cubren estancia tras estancia con una disciplina casi obsesiva. De ahí el nombre con que se conoce la casa.',
      'Este tipo de decoración era más barato que un mosaico figurativo complejo, pero exigía igualmente un dominio técnico grande: cada tesera debía encajar en un patrón repetido sin errores visibles a lo largo de metros y metros de suelo, un trabajo de precisión que hoy asociamos más a la artesanía textil que a la construcción.',
      'Caminad despacio siguiendo con la vista el mismo dibujo de una sala a la siguiente: notaréis que el patrón cambia de habitación en habitación, nunca se repite exactamente igual, prueba de que ni siquiera la decoración más sobria escapaba del gusto por la variación en esta ciudad.',
    ],
    lookFor: ['Los distintos patrones geométricos de los suelos de mosaico'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VIII-6': {
    coords: [40.7481977, 14.485942],
    category: 'servicio',
    illus: 'columna',
    intro: 'Este patio porticado no era un gimnasio cualquiera: aquí se entrenaban los hijos de las familias más influyentes de Pompeya, los llamados iuvenes.',
    narration: [
      'Los iuvenes formaban una asociación de jóvenes de familias acomodadas que combinaba entrenamiento físico, instrucción militar básica y vida social, una especie de escuela de futuros dirigentes de la ciudad. Pertenecer a ella era también una forma de hacerse notar entre quienes algún día competirían por los cargos públicos de Pompeya.',
      'El espacio, distinto de la gran Palestra junto al anfiteatro, era de escala más recogida, pensado para un grupo reducido y selecto, no para el ejercicio abierto a cualquier ciudadano. La diferencia de tamaño entre una y otra dice mucho sobre cómo la sociedad romana organizaba el acceso al prestigio desde la juventud.',
      'Pensad en los nombres que hoy conocemos por inscripciones electorales de Pompeya: buena parte de esos candidatos adultos pasaron antes por patios de entrenamiento como este, aprendiendo tanto a manejar un arma como a hacerse valer entre iguales.',
    ],
    lookFor: ['El pórtico que rodea el patio de entrenamiento'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VIII-7': {
    coords: [40.7490439, 14.4871436],
    category: 'domus',
    illus: 'fresco',
    intro: 'Entrad y dejad que el color os golpee antes que ningún detalle: estas paredes están pintadas de un rojo intenso que ha dado nombre a la casa entera.',
    narration: [
      'El llamado rojo pompeyano, ese tono entre bermellón y granate que hoy se vende como color de pintura en cualquier tienda de decoración, alcanza en esta casa una de sus expresiones más completas, cubriendo panel tras panel del cuarto estilo con esa intensidad que ninguna fotografía reproduce del todo bien.',
      'Conseguir ese color no era barato: el pigmento, a menudo derivado del cinabrio o de tierras rojas tratadas con calor, se aplicaba en varias capas hasta lograr una superficie casi vibrante, y su coste explica por qué no todas las casas de Pompeya podían permitirse cubrir tantas paredes con él.',
      'Quedaos un momento de pie en el centro de la sala más roja y dejad que los ojos se acostumbren: notaréis que el color cambia según la luz que entra por la puerta, más vivo a mediodía, casi oscuro al atardecer, exactamente como debía de verlo la familia que vivió aquí.',
    ],
    lookFor: ['La intensidad del rojo pompeyano en los paneles pintados'],
    tips: ['No está en el circuito habitual de apertura; confirmad en taquilla si está abierta.'],
  },
  'VIII-9': {
    coords: [40.7482865, 14.4879886],
    category: 'templo',
    illus: 'columna',
    intro: 'Estas pocas columnas de piedra dórica, más gastadas que ninguna otra ruina de Pompeya, son también las más antiguas: llevan aquí desde antes de que existiera la propia ciudad romana.',
    narration: [
      'El santuario, dedicado a Atenea y a Heracles, se levantó en el siglo sexto antes de nuestra era, cuando esta zona todavía respondía a poblaciones griegas y osco-samnitas, mucho antes de que Pompeya se convirtiera en colonia romana. Sus columnas dóricas, bajas y robustas, sin la esbeltez de los templos romanos posteriores, delatan esa antigüedad a simple vista.',
      'Para cuando llegó la erupción del setenta y nueve, el templo llevaba siglos en ruinas parciales, casi olvidado dentro de una ciudad que había cambiado varias veces de lengua, de dioses principales y de forma de gobierno. Aun así, nadie se atrevió a borrarlo del todo: los pompeyanos respetaban la antigüedad de un lugar sagrado incluso cuando ya no lo frecuentaban con la misma devoción.',
      'Poneos junto a las columnas y mirad hacia el Foro Triangular que se abre alrededor: estáis en el rincón más viejo de toda la ciudad, el que ya existía cuando Roma todavía discutía su propia forma de gobierno.',
    ],
    lookFor: ['Las columnas dóricas, más bajas y robustas que las de época romana'],
    tips: ['Suele verse en el recorrido del Foro Triangular; confirmad en taquilla el acceso exacto.'],
  },
  'VIII-11': {
    coords: [40.74877, 14.48916],
    category: 'espectaculo',
    illus: 'teatro',
    intro: 'Este pórtico enorme empezó siendo un lugar de paseo para el público del teatro y terminó convertido en cuartel de gladiadores.',
    narration: [
      'Construido detrás del Teatro Grande para que los espectadores pasearan entre acto y acto o se refugiaran de la lluvia, el gran patio porticado cambió de función tras el terremoto del año sesenta y dos: sus galerías se tabicaron en pequeñas celdas y el conjunto pasó a servir de cuartel para gladiadores, con espacio de sobra para entrenar en el centro.',
      'De aquí salieron, en excavaciones del siglo dieciocho bajo el gobierno borbónico, algunas de las armaduras de gladiador más espectaculares que hoy se exhiben en el Museo Arqueológico de Nápoles: cascos de bronce con relieves mitológicos, grebas decoradas, todo un ajuar pensado para el espectáculo tanto como para el combate.',
      'Recorred el perímetro del patio contando las columnas: es fácil olvidar, paseando entre ellas, que este mismo lugar sirvió primero para el ocio del público y después para encerrar a los hombres que ese mismo público iba a aplaudir o a condenar en la arena.',
    ],
    lookFor: ['Las celdas tabicadas entre las columnas del pórtico'],
    tips: ['Suele visitarse junto al Teatro Grande; confirmad en taquilla el acceso exacto.'],
  },
  'VIII-12': {
    coords: [40.7488318, 14.4890205],
    category: 'espectaculo',
    illus: 'teatro',
    intro: 'A diferencia del gran teatro de al lado, este estaba cubierto: entrad y notad cómo cambia el sonido bajo un techo que ya no existe.',
    narration: [
      'El Teatro Pequeño, también llamado Odeón, se construyó cubierto desde el principio, algo poco habitual en el mundo romano, pensado para conciertos y recitales donde la acústica cerrada importaba más que en las representaciones al aire libre del teatro vecino. Cabían unos mil trescientos espectadores, una fracción del aforo del Teatro Grande.',
      'Lo dedicaron hacia el ochenta o el setenta y cinco antes de nuestra era los mismos duunviros que financiaron el anfiteatro, Cayo Quincio Valgo y Marco Porcio, dos nombres que aparecen una y otra vez detrás de los grandes proyectos públicos de la Pompeya de aquella generación, ávidos de dejar su huella en piedra.',
      'Fijaos en los telamones de toba, figuras arrodilladas que hacían de soporte decorativo, agachados bajo un peso invisible desde hace dos mil años. Se ve bien desde el pasillo exterior aunque no se pueda entrar, así que no hace falta más que asomarse.',
    ],
    lookFor: ['Los telamones de toba arrodillados', 'La diferencia de tamaño con el Teatro Grande vecino'],
    tips: ['Visible solo desde fuera; no tiene acceso al interior.'],
  },
  'VIII-15': {
    coords: [40.749567, 14.4881669],
    category: 'domus',
    illus: 'domus',
    intro: 'Un busto y una herma con el mismo rostro dieron nombre a esta casa: Cayo Cornelio Rufo, un hombre que se aseguró de que nadie lo olvidara.',
    narration: [
      'Excavada entre mil ochocientos cincuenta y cinco y mil ochocientos noventa y tres, en una de las campañas más largas y menos documentadas del siglo diecinueve, esta casa entregó un busto y una herma con los rasgos de Cornelio Rufo, suficiente para bautizarla con su nombre aunque no sepamos gran cosa más de su vida.',
      'De aquí procede también un cartibulum de mármol decorado con grifos, una mesa de aparato para el atrio que hoy se conserva en el Museo Arqueológico Nacional de Nápoles, y una llave de bronce que servía para abrir el grifo de la fuente del atrio, un detalle doméstico tan pequeño como revelador del nivel de vida de la casa.',
      'Pensad en esa llave de bronce cada vez que veáis una fuente de atrio en otra casa: la mayoría ha perdido para siempre el pequeño objeto cotidiano que la hacía funcionar de verdad.',
    ],
    lookFor: ['El hueco donde estuvo el cartibulum de mármol del atrio'],
    tips: ['Estado de apertura no confirmado; consultad en taquilla si se puede visitar.'],
  },
  'VIII-16': {
    coords: [40.7491213, 14.4859469],
    category: 'domus',
    illus: 'mosaico',
    intro: 'En el mosaico del vestíbulo, un jabalí se defiende de dos perros que lo acosan por los flancos: la escena que da nombre a toda la casa.',
    narration: [
      'El mosaico de entrada, con el jabalí acosado por los dos perros, cumplía la misma función que los famosos perros guardianes de otras casas pompeyanas: recibir al visitante con una imagen que hablaba del carácter del dueño antes de que este apareciera en persona. En el atrio hay además otro mosaico con una muralla almenada, un motivo defensivo poco frecuente en suelos domésticos.',
      'Se conocen los nombres de dos hombres relacionados con la casa gracias a sellos de bronce hallados en ella, Quinto Delio Amico y Cayo Julio Suave, hoy conservados en el Museo Arqueológico Nacional de Nápoles; probablemente sellaban sacos o cofres con sus iniciales, una firma práctica más que un gesto artístico.',
      'La casa solo se ve desde fuera, así que aprovechad para fijaros bien en el mosaico del jabalí a través de la reja: es de los pocos detalles de esta vivienda que se distinguen sin necesidad de entrar.',
    ],
    lookFor: ['El mosaico del jabalí acosado por dos perros en el vestíbulo'],
    tips: ['Visible solo desde fuera, a través de la reja.'],
  },
  'VIII-17': {
    coords: [40.7485155, 14.4862436],
    category: 'domus',
    illus: 'fresco',
    intro: 'El nombre de esta casa no viene de la Antigüedad, sino de una princesa francesa que financió su excavación hace dos siglos.',
    narration: [
      'Carolina Bonaparte Murat, hermana de Napoleón y reina consorte de Nápoles, patrocinó excavaciones en Pompeya y encargó un plano detallado de esta casa al arquitecto François Mazois, un gesto de mecenazgo que quedó grabado en el nombre del edificio para siempre, mucho más duradero que su breve reinado.',
      'Dentro se conservan frescos con el mito de Perseo y Andrómeda, el héroe que rescata a la princesa encadenada a una roca, junto a escenas con pigmeos en escenarios nilóticos, un tema que combinaba exotismo egipcio y humor en la pintura romana de la época. La casa se restauró entre dos mil quince y dos mil dieciséis.',
      'Desde dos mil dieciocho, un equipo académico de la Universidad de Oxford excava aquí de manera activa, así que el acceso puede estar restringido según la campaña en curso: es una de las pocas casas de Pompeya donde la investigación sigue escribiéndose delante de vuestros ojos.',
    ],
    lookFor: ['Los frescos de Perseo y Andrómeda', 'Las escenas pintadas con pigmeos'],
    tips: ['Excavación académica activa; el acceso puede estar restringido, confirmad en taquilla.'],
  },
  'VIII-18': {
    coords: [40.7484237, 14.4837195],
    category: 'villa',
    illus: 'columna',
    intro: 'Adosada a la muralla, bajo el Templo de Venus, esta villa se descubrió por accidente cuando un bombardeo de mil novecientos cuarenta y tres abrió un boquete en la ladera.',
    narration: [
      'El pórtico de cuarenta y tres columnas de ladrillo estucado, apoyado contra el lienzo de muralla que mira al mar, es lo primero que se reconoce de esta villa aterrazada, construida aprovechando el desnivel hacia el Sarno para ganar vistas que ninguna casa del interior de la ciudad podía tener.',
      'Dentro se conservan frescos con los mitos de Dédalo e Ícaro y de Teseo enfrentándose al Minotauro, escenas de vuelo y de laberinto que encajan bien con una villa pensada para impresionar a quien llegaba por mar. El arqueólogo Amedeo Maiuri la excavó en mil novecientos cuarenta y siete, tras aquel descubrimiento involuntario de la guerra.',
      'A pesar del nombre con que se la conoce, villa imperial, no está probado que perteneciera de verdad a la familia del emperador: es una atribución basada en su tamaño y su posición privilegiada, no en ninguna inscripción que lo confirme. Se abre solo de manera ocasional.',
    ],
    lookFor: ['El pórtico de columnas de ladrillo estucado sobre la muralla'],
    tips: ['Apertura ocasional; confirmad en taquilla si está accesible ese día.'],
  },
  'VIII-20': {
    coords: [40.7482951, 14.4833309],
    category: 'servicio',
    illus: 'domus',
    intro: 'Junto al Antiquarium, este vivero no reconstruye ninguna casa: cultiva las mismas plantas que los arqueólogos identifican en las raíces fosilizadas de los jardines de Pompeya.',
    narration: [
      'El Orto Botanico funciona como banco de semillas y vivero del parque arqueológico, un laboratorio al aire libre donde se cultivan las especies vegetales que la investigación arqueobotánica ha identificado en los jardines antiguos, a partir de semillas carbonizadas y de los moldes de raíces que el método de Wilhelmina Jashemski hizo posible interpretar.',
      'Gracias a este tipo de trabajo sabemos qué árboles daban sombra en el peristilo de tal casa o qué vides trepaban por la pérgola de tal otra, y este vivero es donde esas conclusiones se comprueban de verdad plantando y observando, no solo leyendo huecos vacíos en la tierra.',
      'Vale la pena parar aquí después de tantas casas de piedra y pintura: es el único punto del recorrido donde Pompeya sigue creciendo, literalmente, en lugar de solo conservarse.',
    ],
    lookFor: ['Las especies vegetales identificadas a partir de restos arqueobotánicos'],
    tips: ['Abierto de nueve a diecinueve horas.'],
  },
  'IX-4': {
    coords: [40.7519883, 14.4873784],
    category: 'domus',
    illus: 'fresco',
    intro: 'En una franja pintada de esta casa, unos pigmeos navegan en barcas diminutas entre hipopótamos, en un Nilo que ningún pompeyano había visto jamás con sus propios ojos.',
    narration: [
      'Las escenas nilóticas, con su mezcla de humor y exotismo, gustaban en Pompeya como decoración de casas de cierto nivel: cocodrilos, hipopótamos y pigmeos navegando entre cañaverales representaban un Egipto de fantasía, más cercano al imaginario popular que a cualquier conocimiento geográfico real del país del Nilo.',
      'La casa se excavó en mil ochocientos setenta y siete, en plena época en que este tipo de hallazgo alimentaba la moda europea por el exotismo egipcio, la misma fascinación que llenaba los salones burgueses de motivos con esfinges y jeroglíficos decorativos sin mucho rigor.',
      'Fijaos en el tono de humor de la escena, casi de viñeta, más que en cualquier pretensión etnográfica: los pigmeos aparecen en posturas exageradas, medio cómicas, un recordatorio de que el arte romano también sabía reírse de lo lejano sin necesidad de entenderlo del todo.',
    ],
    lookFor: ['La franja pintada con la escena nilótica de pigmeos e hipopótamos'],
    tips: ['Estado de apertura no confirmado; consultad en taquilla si se puede visitar.'],
  },
  'IX-5': {
    coords: [40.7501931, 14.4883051],
    category: 'domus',
    illus: 'columna',
    intro: 'Contad las columnas del atrio: dieciséis, de más de cuatro metros y medio, un lujo arquitectónico que casi ninguna otra casa de Pompeya se permitió.',
    narration: [
      'Este tipo de atrio, llamado corintio, sustituye el hueco central sencillo de la mayoría de las casas por un anillo completo de columnas que sostiene la cubierta alrededor del impluvium, una solución mucho más cara y más vistosa que el atrio tuscánico habitual. La casa se excavó en dos tandas, mil ochocientos cincuenta y ocho y mil ochocientos sesenta y seis.',
      'Los capiteles de las columnas llevan motivos dionisíacos, relacionados con Baco y su cortejo, un tema decorativo que se repetía en las partes más representativas de las casas ricas, pensado para impresionar a quien cruzaba el umbral antes de llegar siquiera al resto de la vivienda.',
      'El edificio sufrió los bombardeos de mil novecientos cuarenta y tres y fue restaurado después; cada columna en pie es, en cierto modo, una reconstrucción tan cuidadosa como la lectura arqueológica que la hizo posible.',
    ],
    lookFor: ['Las dieciséis columnas del atrio corintio', 'Los capiteles con motivos dionisíacos'],
    tips: ['Estado de apertura no confirmado; consultad en taquilla si se puede visitar.'],
  },
  'IX-8': {
    coords: [40.7511681, 14.4902207],
    category: 'domus',
    illus: 'fresco',
    intro: 'Esta casa se excavó despacio, año tras año entre mil novecientos sesenta y cuatro y mil novecientos setenta y siete, con un cuidado que cambió lo que esperamos de una excavación pompeyana.',
    narration: [
      'De aquella campaña sistemática salió, en mil novecientos setenta y tres, un sello de bronce con el nombre de Cayo Julio Filipo, y también los restos de tres personas que no lograron escapar, entre ellas una mujer joven embarazada, un hallazgo que hizo mucho por humanizar, fuera de cualquier dato frío, lo que significó realmente la erupción para quienes la vivieron.',
      'En el interior se conserva un fresco con el castigo de Dirce, un mito violento sobre venganza y crueldad que la pintura romana no dudaba en mostrar con crudeza; y una crátera de bronce con ocho figuras, hoy en el Antiquarium del parque, uno de los objetos metálicos más elaborados hallados en una casa privada de la ciudad.',
      'Pensad en el contraste entre el rigor casi silencioso de una excavación de trece años y la violencia de las escenas que esa misma paciencia sacó a la luz: la arqueología cuidadosa no siempre encuentra historias tranquilas.',
    ],
    lookFor: ['El fresco con el castigo de Dirce'],
    tips: ['Estado de apertura no confirmado; consultad en taquilla si se puede visitar.'],
  },
  'IX-9': {
    coords: [40.7520821, 14.4879758],
    category: 'domus',
    illus: 'fresco',
    intro: 'En la cocina de esta casa, alguien pintó un cerdo con más cariño del que cabría esperar de una simple decoración de servicio.',
    narration: [
      'De ese fresco viene el nombre popular, casa del cerdito, aunque también se conoce como casa de Sulpicio Rufo por un sello con ese nombre hallado en su interior, uno más de los muchos casos en que una misma vivienda pompeyana arrastra dos etiquetas distintas según qué hallazgo se priorice al bautizarla.',
      'El resto de la decoración combina pintura de tercer y cuarto estilo, es decir, paneles de color sobrio con arquitecturas fingidas más recargadas superpuestas después, la misma superposición de modas que se repite en tantas casas medianas de Pompeya reformadas a lo largo de generaciones.',
      'Las coordenadas de esta ficha son aproximadas, tomadas de la insula vecina, porque el punto exacto no aparece recogido en las fuentes disponibles: un pequeño recordatorio de que incluso hoy quedan esquinas de Pompeya por precisar del todo.',
    ],
    lookFor: ['El fresco del cerdo en la cocina'],
    tips: ['Coordenadas aproximadas, tomadas de la insula vecina; confirmad en taquilla si está abierta.'],
  },
};
