/**
 * Leyenda del plano oficial "Pianta degli scavi di Pompei" (Parco Archeologico di Pompei),
 * transcrita del plano en papel que se entrega en taquilla. Numeración por Regio.
 * `stopId` enlaza con una parada de la ruta (route.ts o extra.ts) cuando existe.
 * Los puntos sin parada tienen ficha propia en OFFICIAL_ENTRIES (official-entries.ts).
 */
export type Regio = 'I' | 'II' | 'III' | 'V' | 'VI' | 'VII' | 'VIII' | 'IX';
export interface LegendItem { regio: Regio; num: string; it: string; es: string; stopId?: string; accessible?: boolean }

export const REGIO_META: Record<Regio, { color: string; label: string; area: string }> = {
  I: { color: '#b4321e', label: 'Regio I', area: 'Sureste: Via dell\'Abbondanza baja, Menandro, calcos' },
  II: { color: '#b98a1b', label: 'Regio II', area: 'Este: anfiteatro, Palestra Grande, grandes jardines' },
  III: { color: '#6b3a3a', label: 'Regio III', area: 'Noreste: Porta Nola y su necrópolis' },
  V: { color: '#3f6b3a', label: 'Regio V', area: 'Norte: excavaciones recientes, termopolio, Porta Vesuvio' },
  VI: { color: '#2e5c8a', label: 'Regio VI', area: 'Noroeste: las grandes casas, Porta Ercolano, villas' },
  VII: { color: '#7a2e5c', label: 'Regio VII', area: 'Centro: foro, termas, Lupanar' },
  VIII: { color: '#c96a2b', label: 'Regio VIII', area: 'Sur: Basílica, teatros, Templo de Isis' },
  IX: { color: '#1f6b5c', label: 'Regio IX', area: 'Centro-este: Termas Centrales, Castos Amantes' },
};

export const OFFICIAL_LEGEND: LegendItem[] = [
  // REGIO I
  { regio: 'I', num: '1', it: 'Casa del Citarista', es: 'Casa del Citarista', stopId: 'casa-citarista' },
  { regio: 'I', num: '2', it: 'Casa di Casca Longus o dei Quadretti teatrali', es: 'Casa de Casca Longo o de los Cuadritos teatrales', accessible: true },
  { regio: 'I', num: '3', it: 'Fullonica di Stephanus', es: 'Fullonica de Stephanus', stopId: 'fullonica-stephanus', accessible: true },
  { regio: 'I', num: '4', it: 'Casa del Larario di Achille', es: 'Casa del Larario de Aquiles', stopId: 'casa-larario-aquiles', accessible: true },
  { regio: 'I', num: '5', it: 'Casa del Criptoportico', es: 'Casa del Criptopórtico', stopId: 'casa-criptoportico', accessible: true },
  { regio: 'I', num: '6', it: 'Casa dei Ceii', es: 'Casa de los Ceios', stopId: 'casa-ceii' },
  { regio: 'I', num: '7', it: 'Casa del Menandro', es: 'Casa del Menandro', stopId: 'casa-menandro', accessible: true },
  { regio: 'I', num: '8', it: 'Casa di Paquio Proculo', es: 'Casa de Paquio Próculo', stopId: 'casa-paquio-proculo' },
  { regio: 'I', num: '9', it: 'Casa dell\'Efebo', es: 'Casa del Efebo', stopId: 'casa-efebo', accessible: true },
  { regio: 'I', num: '10', it: 'Casa di Fabius Amandius', es: 'Casa de Fabio Amandio', stopId: 'casa-fabio-amandio' },
  { regio: 'I', num: '11', it: 'Casa del Sacerdos Amandus', es: 'Casa del Sacerdote Amando' },
  { regio: 'I', num: '12', it: 'Casa e Thermopolium di Vetutius Placidus', es: 'Casa y termopolio de Vetucio Plácido' },
  { regio: 'I', num: '13', it: 'Casa del Frutteto', es: 'Casa del Huerto' },
  { regio: 'I', num: '14', it: 'Caupona di Sotericus (o all\'Insegna di Roma)', es: 'Caupona de Sotérico' },
  { regio: 'I', num: '15', it: 'Casa della Nave Europa', es: 'Casa de la Nave Europa', accessible: true },
  { regio: 'I', num: '16', it: 'Orto dei Fuggiaschi', es: 'Jardín de los Fugitivos', stopId: 'jardin-fugitivos', accessible: true },
  { regio: 'I', num: '17', it: 'Casa con Botteghe', es: 'Casa con tiendas' },
  { regio: 'I', num: '18', it: 'Casa degli Amanti', es: 'Casa de los Amantes' },
  { regio: 'I', num: '19', it: 'Casa dei Quattro Stili', es: 'Casa de los Cuatro Estilos', accessible: true },
  { regio: 'I', num: '20', it: 'Casa degli Archi', es: 'Casa de los Arcos' },
  { regio: 'I', num: '21', it: 'Osteria del Gladiatore', es: 'Taberna del Gladiador' },
  { regio: 'I', num: '22', it: 'Casa di Cerere', es: 'Casa de Ceres' },
  { regio: 'I', num: '23', it: 'Conceria', es: 'Curtiduría' },
  { regio: 'I', num: '24', it: 'Bottega del Garum', es: 'Tienda del garum' },
  { regio: 'I', num: '25', it: 'Casa del Fabbro', es: 'Casa del Herrero' },
  { regio: 'I', num: '26', it: 'Officina Tintoria di Terenzio', es: 'Tintorería de Terencio' },
  { regio: 'I', num: '27', it: 'Casa del Primo Piano', es: 'Casa del Primer Piso' },
  { regio: 'I', num: '28', it: 'Casa di Saturnino', es: 'Casa de Saturnino' },
  { regio: 'I', num: '29', it: 'Casa dell\'Atrio', es: 'Casa del Atrio' },
  // REGIO II
  { regio: 'II', num: '1', it: 'Casa di Octavius Quartio', es: 'Casa de Octavio Cuartio', stopId: 'casa-octavio-cuartio', accessible: true },
  { regio: 'II', num: '2', it: 'Casa della Venere in conchiglia', es: 'Casa de la Venus en la Concha', stopId: 'casa-venus-concha', accessible: true },
  { regio: 'II', num: '3', it: 'Praedia di Giulia Felice', es: 'Predios de Julia Félix', stopId: 'casa-julia-felix', accessible: true },
  { regio: 'II', num: '4', it: 'Foro Boario', es: 'Foro Boario' },
  { regio: 'II', num: '5', it: 'Anfiteatro', es: 'Anfiteatro', stopId: 'anfiteatro', accessible: true },
  { regio: 'II', num: '6', it: 'Palestra Grande', es: 'Palestra Grande', stopId: 'palestra-grande', accessible: true },
  { regio: 'II', num: '7', it: 'Casa del Triclinio all\'aperto o estivo', es: 'Casa del Triclinio al aire libre' },
  { regio: 'II', num: '8', it: 'Casa del Giardino di Ercole', es: 'Casa del Jardín de Hércules' },
  { regio: 'II', num: '9', it: 'Porta Nocera e cinta muraria', es: 'Porta Nocera y murallas' },
  { regio: 'II', num: '10', it: 'Necropoli di Porta Nocera', es: 'Necrópolis de Porta Nocera', stopId: 'necropolis-porta-nocera' },
  { regio: 'II', num: '11', it: 'Casa del Larario Fiorito', es: 'Casa del Larario Florido' },
  // REGIO III
  { regio: 'III', num: '1', it: 'Casa di Trebio Valente', es: 'Casa de Trebio Valente', stopId: 'casa-trebio-valente' },
  { regio: 'III', num: '2', it: 'Schola Armaturarum', es: 'Schola Armaturarum' },
  { regio: 'III', num: '3', it: 'Casa del Moralista', es: 'Casa del Moralista', stopId: 'casa-moralista' },
  { regio: 'III', num: '4', it: 'Porta Nola e cinta muraria', es: 'Porta Nola y murallas', stopId: 'porta-nola' },
  { regio: 'III', num: '5', it: 'Necropoli di Porta Nola', es: 'Necrópolis de Porta Nola' },
  // REGIO V
  { regio: 'V', num: '1', it: 'Caserma dei Gladiatori', es: 'Cuartel de los Gladiadores' },
  { regio: 'V', num: '2', it: 'Casa di Marco Lucrezio Frontone', es: 'Casa de Marco Lucrecio Frontón', stopId: 'casa-marco-lucrecio-fronton' },
  { regio: 'V', num: '3', it: 'Casa delle Nozze d\'Argento', es: 'Casa de las Bodas de Plata', stopId: 'casa-bodas-plata' },
  { regio: 'V', num: '4', it: 'Casa di Cecilio Giocondo', es: 'Casa de Cecilio Jocundo' },
  { regio: 'V', num: '5', it: 'Necropoli di Porta Vesuvio', es: 'Necrópolis de Porta Vesuvio' },
  { regio: 'V', num: '6', it: 'Casa di Leda e il Cigno', es: 'Casa de Leda y el Cisne', stopId: 'casa-leda' },
  { regio: 'V', num: '7', it: 'Thermopolium', es: 'Termopolio de la Regio V', stopId: 'termopolio-regio-v' },
  { regio: 'V', num: '8', it: 'Casa del Giardino', es: 'Casa del Jardín' },
  { regio: 'V', num: '9', it: 'Casa di Orione', es: 'Casa de Orión' },
  { regio: 'V', num: '10', it: 'Casa degli Epigrammi', es: 'Casa de los Epigramas' },
  { regio: 'V', num: '11', it: 'Casa dei Girali', es: 'Casa de los Roleos' },
  { regio: 'V', num: '12', it: 'Casa del Larario', es: 'Casa del Larario' },
  // REGIO VI
  { regio: 'VI', num: '1', it: 'Casa del Fauno', es: 'Casa del Fauno', stopId: 'casa-fauno', accessible: true },
  { regio: 'VI', num: '2', it: 'Casa dell\'Ancora', es: 'Casa del Ancla', stopId: 'casa-ancla' },
  { regio: 'VI', num: '3', it: 'Casa della Fontana Piccola', es: 'Casa de la Fuente Pequeña', stopId: 'casa-fontana-pequena' },
  { regio: 'VI', num: '4', it: 'Casa del Poeta Tragico', es: 'Casa del Poeta Trágico', stopId: 'casa-poeta-tragico' },
  { regio: 'VI', num: '5', it: 'Thermopolium', es: 'Termopolio de la Via Consolare' },
  { regio: 'VI', num: '6', it: 'Casa di Pansa', es: 'Casa de Pansa', stopId: 'casa-pansa' },
  { regio: 'VI', num: '7', it: 'Casa del Forno', es: 'Casa del Horno' },
  { regio: 'VI', num: '8', it: 'Casa di Sallustio', es: 'Casa de Salustio', stopId: 'casa-salustio' },
  { regio: 'VI', num: '9', it: 'Casa dell\'Adone Ferito', es: 'Casa del Adonis Herido' },
  { regio: 'VI', num: '10', it: 'Casa dei Dioscuri', es: 'Casa de los Dioscuros', stopId: 'casa-dioscuros' },
  { regio: 'VI', num: '11', it: 'Casa dei Vettii', es: 'Casa de los Vettii', stopId: 'casa-vettii' },
  { regio: 'VI', num: '12', it: 'Casa degli Amorini Dorati', es: 'Casa de los Amorcillos Dorados', stopId: 'casa-amorini-dorados' },
  { regio: 'VI', num: '13', it: 'Casa dell\'Ara Massima', es: 'Casa del Ara Máxima' },
  { regio: 'VI', num: '14', it: 'Castellum Aquae', es: 'Castellum Aquae', stopId: 'castellum-aquae' },
  { regio: 'VI', num: '15', it: 'Casa del Principe di Napoli', es: 'Casa del Príncipe de Nápoles' },
  { regio: 'VI', num: '16', it: 'Porta Ercolano e cinta muraria', es: 'Porta Ercolano y murallas', stopId: 'porta-ercolano' },
  { regio: 'VI', num: '17', it: 'Necropoli di Porta Ercolano', es: 'Necrópolis de Porta Ercolano' },
  { regio: 'VI', num: '18', it: 'Villa di Diomede', es: 'Villa de Diomedes', stopId: 'villa-diomede', accessible: true },
  { regio: 'VI', num: '19', it: 'Villa dei Misteri', es: 'Villa de los Misterios', stopId: 'villa-misterios', accessible: true },
  { regio: 'VI', num: '20', it: 'Casa della Fontana Grande', es: 'Casa de la Fuente Grande', stopId: 'casa-fontana-grande' },
  { regio: 'VI', num: '21', it: 'Casa del Labirinto', es: 'Casa del Laberinto', stopId: 'casa-laberinto' },
  { regio: 'VI', num: '22', it: 'Casa di Apollo', es: 'Casa de Apolo', stopId: 'casa-apolo' },
  { regio: 'VI', num: '23', it: 'Casa di Orfeo', es: 'Casa de Orfeo' },
  { regio: 'VI', num: '24', it: 'Casa della Biblioteca', es: 'Casa de la Biblioteca' },
  { regio: 'VI', num: '25', it: 'Casa di Meleagro', es: 'Casa de Meleagro', stopId: 'casa-meleagro' },
  { regio: 'VI', num: '26', it: 'Casa del Chirurgo', es: 'Casa del Cirujano', stopId: 'casa-cirujano' },
  { regio: 'VI', num: '27', it: 'Casa del Centauro', es: 'Casa del Centauro' },
  { regio: 'VI', num: '28', it: 'Torre di Mercurio', es: 'Torre de Mercurio', stopId: 'torre-mercurio' },
  // REGIO VII
  { regio: 'VII', num: '1', it: 'Terme Suburbane', es: 'Termas Suburbanas', stopId: 'terme-suburbane' },
  { regio: 'VII', num: '2', it: 'Porta Marina e cinta muraria', es: 'Porta Marina y murallas', stopId: 'porta-marina' },
  { regio: 'VII', num: '3', it: 'Casa del Marinaio', es: 'Casa del Marinero' },
  { regio: 'VII', num: '4a', it: 'Casa di Trittolemo', es: 'Casa de Triptólemo' },
  { regio: 'VII', num: '4b', it: 'Casa di Romolo e Remo', es: 'Casa de Rómulo y Remo' },
  { regio: 'VII', num: '5', it: 'Santuario di Apollo', es: 'Santuario de Apolo', stopId: 'templo-apolo', accessible: true },
  { regio: 'VII', num: '6a', it: 'Foro', es: 'Foro', stopId: 'foro', accessible: true },
  { regio: 'VII', num: '6b', it: 'Mensa Ponderaria', es: 'Mensa Ponderaria' },
  { regio: 'VII', num: '7', it: 'Granai del Foro', es: 'Graneros del Foro', stopId: 'granai-foro' },
  { regio: 'VII', num: '8', it: 'Tempio di Giove', es: 'Templo de Júpiter', stopId: 'templo-giove' },
  { regio: 'VII', num: '9', it: 'Archi onorari', es: 'Arcos honoríficos', stopId: 'arco-caligula' },
  { regio: 'VII', num: '10', it: 'Terme del Foro', es: 'Termas del Foro', stopId: 'termas-foro', accessible: true },
  { regio: 'VII', num: '11', it: 'Tempio della Fortuna Augusta', es: 'Templo de la Fortuna Augusta', stopId: 'templo-fortuna-augusta' },
  { regio: 'VII', num: '12', it: 'Macellum', es: 'Macellum', stopId: 'edificio-eumachia', accessible: true },
  { regio: 'VII', num: '13', it: 'Santuario dei Lari Pubblici', es: 'Santuario de los Lares Públicos', stopId: 'santuario-lares' },
  { regio: 'VII', num: '14', it: 'Tempio del Genius Augusti (Tempio di Vespasiano)', es: 'Templo del Genio de Augusto (Vespasiano)', stopId: 'templo-vespasiano' },
  { regio: 'VII', num: '15', it: 'Portico della Concordia Augusta (Edificio di Eumachia)', es: 'Pórtico de la Concordia Augusta (Edificio de Eumaquia)', stopId: 'edificio-eumachia', accessible: true },
  { regio: 'VII', num: '16', it: 'Terme Stabiane', es: 'Termas Estabianas', stopId: 'termas-estabianas', accessible: true },
  { regio: 'VII', num: '17', it: 'Casa di Sirico', es: 'Casa de Sirico', stopId: 'casa-sirico', accessible: true },
  { regio: 'VII', num: '18', it: 'Lupanare', es: 'Lupanar', stopId: 'lupanar' },
  { regio: 'VII', num: '19', it: 'Casa dell\'Orso Ferito', es: 'Casa del Oso Herido' },
  { regio: 'VII', num: '20', it: 'Panificio di Popidio Prisco', es: 'Panadería de Popidio Prisco', stopId: 'panaderia-popidio-prisco' },
  { regio: 'VII', num: '21', it: 'Casa della Caccia Antica', es: 'Casa de la Caza Antigua', stopId: 'casa-caza-antigua', accessible: true },
  { regio: 'VII', num: '22', it: 'Casa di Marco Fabio Rufo', es: 'Casa de Marco Fabio Rufo', stopId: 'casa-marco-fabio-rufo' },
  { regio: 'VII', num: '23', it: 'Casa del Bracciale d\'Oro', es: 'Casa del Brazalete de Oro', stopId: 'casa-brazalete-oro' },
  { regio: 'VII', num: '24', it: 'Casa di Arianna', es: 'Casa de Ariadna' },
  { regio: 'VII', num: '25', it: 'Casa di Castricio', es: 'Casa de Castricio' },
  { regio: 'VII', num: '26', it: 'Casa di Cesio Blando', es: 'Casa de Cesio Blando' },
  { regio: 'VII', num: '27', it: 'Casa del Balcone Pensile', es: 'Casa del Balcón Colgante' },
  // REGIO VIII
  { regio: 'VIII', num: '1', it: 'Santuario di Venere', es: 'Santuario de Venus', stopId: 'templo-venus', accessible: true },
  { regio: 'VIII', num: '2', it: 'Basilica', es: 'Basílica', stopId: 'basilica', accessible: true },
  { regio: 'VIII', num: '3', it: 'Comitium e edifici municipali', es: 'Comitium y edificios municipales', stopId: 'comitium' },
  { regio: 'VIII', num: '4', it: 'Casa di Championnet', es: 'Casa de Championnet' },
  { regio: 'VIII', num: '5', it: 'Casa dei Mosaici Geometrici', es: 'Casa de los Mosaicos Geométricos', accessible: true },
  { regio: 'VIII', num: '6', it: 'Palestra degli Iuvenes', es: 'Palestra de los Jóvenes' },
  { regio: 'VIII', num: '7', it: 'Casa delle Pareti Rosse', es: 'Casa de las Paredes Rojas' },
  { regio: 'VIII', num: '8', it: 'Foro Triangolare e Palestra Sannitica', es: 'Foro Triangular y Palestra Samnita', stopId: 'foro-triangular', accessible: true },
  { regio: 'VIII', num: '9', it: 'Tempio Dorico - Santuario di Atena e Eracle', es: 'Templo Dórico, santuario de Atenea y Heracles', accessible: true },
  { regio: 'VIII', num: '10', it: 'Teatro Grande', es: 'Teatro Grande', stopId: 'teatro-grande', accessible: true },
  { regio: 'VIII', num: '11', it: 'Quadriportico dei teatri o Caserma dei Gladiatori', es: 'Cuadripórtico de los teatros o Cuartel de los Gladiadores', accessible: true },
  { regio: 'VIII', num: '12', it: 'Teatro Piccolo - Odeion', es: 'Teatro Pequeño, Odeón' },
  { regio: 'VIII', num: '13', it: 'Tempio di Esculapio o di Giove Meilichio', es: 'Templo de Esculapio o de Júpiter Meilichio', stopId: 'templo-jupiter-meilichio' },
  { regio: 'VIII', num: '14', it: 'Tempio di Iside', es: 'Templo de Isis', stopId: 'templo-isis' },
  { regio: 'VIII', num: '15', it: 'Casa dei Cornelii', es: 'Casa de los Cornelios' },
  { regio: 'VIII', num: '16', it: 'Casa del Cinghiale', es: 'Casa del Jabalí' },
  { regio: 'VIII', num: '17', it: 'Casa della Regina Carolina', es: 'Casa de la Reina Carolina' },
  { regio: 'VIII', num: '18', it: 'Villa Imperiale', es: 'Villa Imperial' },
  { regio: 'VIII', num: '19', it: 'Antiquarium', es: 'Antiquarium', stopId: 'antiquarium', accessible: true },
  { regio: 'VIII', num: '20', it: 'Orto botanico', es: 'Jardín botánico' },
  { regio: 'VIII', num: '21', it: 'Necropoli di Porta Stabia', es: 'Necrópolis de Porta Stabia', stopId: 'porta-stabia' },
  // REGIO IX
  { regio: 'IX', num: '1', it: 'Casa di Marco Lucrezio su via Stabiana', es: 'Casa de Marco Lucrecio en la Via Stabiana', stopId: 'casa-marco-lucrecio' },
  { regio: 'IX', num: '2', it: 'Terme Centrali', es: 'Termas Centrales', stopId: 'termas-centrales' },
  { regio: 'IX', num: '3', it: 'Casa di Obellio Firmo', es: 'Casa de Obelio Firmo', stopId: 'casa-obellio-firmo' },
  { regio: 'IX', num: '4', it: 'Casa dei Pigmei', es: 'Casa de los Pigmeos' },
  { regio: 'IX', num: '5', it: 'Casa di M. Epidius Rufus', es: 'Casa de Marco Epidio Rufo' },
  { regio: 'IX', num: '6', it: 'Thermopolium di Asellina', es: 'Termopolio de Asellina', stopId: 'via-abbondanza' },
  { regio: 'IX', num: '7', it: 'Insula dei Casti Amanti', es: 'Insula de los Castos Amantes', stopId: 'casa-casti-amanti' },
  { regio: 'IX', num: '8', it: 'Casa di Giulio Polibio', es: 'Casa de Julio Polibio' },
  { regio: 'IX', num: '9', it: 'Casa del Porcellino', es: 'Casa del Cerdito' },
  { regio: 'IX', num: '10', it: 'Casa del Centenario', es: 'Casa del Centenario', stopId: 'casa-centenario' },
];
export const legendKey = (i: LegendItem) => `${i.regio}-${i.num}`;
