import type { Route, Stop } from './types';

const STOPS: Stop[] = [
  {
    id: 'porta-marina',
    order: 1,
    name: 'Porta Marina',
    category: 'puerta',
    coords: [40.748509, 14.483085],
    minutes: 10,
    walkMinutesToNext: 2,
    intro: 'Bienvenidos a Pompeya: pisamos ya la rampa de la Porta Marina, la entrada que un día miraba de frente al mar.',
    narration: [
      'Estamos entrando en la ciudad por donde entraban los romanos que llegaban en barco. La Porta Marina era, como su nombre indica, la puerta del mar. Hoy la costa ha retrocedido más de un kilómetro, porque la erupción del año setenta y nueve rellenó de cenizas y piedra pómez toda la llanura costera. Pero en tiempos de los romanos, el agua llegaba casi hasta el pie de esta muralla.',
      'Fijaos en que la rampa tiene dos pasos distintos, separados por un muro central. El más ancho, a la derecha según subimos, era para los animales de carga y los carros. El más estrecho, a la izquierda, era exclusivamente para peatones, y por eso conserva restos de un techo abovedado que lo protegía y lo mantenía en sombra. Era, en cierto modo, el primer control de tráfico urbano que vamos a ver hoy, y no será el último.',
      'La muralla que atravesamos es mucho más antigua que la propia puerta. Pompeya empezó a fortificarse en piedra caliza local ya en el siglo seis antes de nuestra era, y fue reforzando sus defensas durante siglos, primero frente a otras ciudades itálicas y después, sobre todo, durante la llamada guerra social, cuando los pueblos aliados de Roma se levantaron para pedir la ciudadanía romana. Las huellas de proyectiles de aquella guerra todavía se pueden reconocer en algunos tramos de muro cercanos.',
      'Pompeya quedó sepultada bajo varios metros de ceniza y permaneció prácticamente olvidada durante diecisiete siglos, hasta que unos trabajadores que abrían un canal de riego en el siglo dieciocho tropezaron con sus ruinas. Desde entonces no ha dejado de excavarse, de estudiarse y de sorprendernos. Hoy caminamos nosotros sobre las mismas losas de piedra volcánica que pulieron las ruedas de los carros romanos, así que fijaos bien dónde pisáis.',
    ],
    lookFor: [
      'Los dos pasadizos separados por el muro central: uno ancho para carros y animales, otro estrecho y cubierto para peatones.',
      'Las marcas de erosión en los bloques de piedra, desgastados por siglos de tránsito antes incluso de la erupción.',
      'La diferencia de nivel entre la calle exterior y la ciudad: la Porta Marina salva un desnivel importante mediante la rampa.',
      'Los tramos de muralla a ambos lados, construidos con piedra caliza local en distintas fases.',
    ],
    anecdote: 'La estación de tren que habéis dejado atrás, Pompei Scavi Villa dei Misteri, se construyó a propósito junto a esta puerta a comienzos del siglo veinte, siguiendo la misma lógica que los romanos: llegar a la ciudad por el lado del mar.',
    directionsToNext: 'Subid por la rampa de la Porta Marina siguiendo la Via Marina. A unos cien metros, antes de llegar a la plaza del foro, girad a la izquierda hacia la terraza ajardinada: ahí está el Templo de Venus. Son unos cuatro minutos a pie, casi todo en subida suave.',
    image: { src: 'porta-marina', alt: 'Rampa de acceso de la Porta Marina en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'calle',
    tips: [
      'La rampa es empedrada y tiene pendiente: calzado con buen agarre desde el primer minuto.',
      'Es el punto de entrada más habitual y suele haber cola a primera hora; llegar al abrir el recinto evita el calor y las aglomeraciones.',
      'Pompeya cuenta con el itinerario "Pompei per tutti", una ruta accesible sin barreras de unos tres coma cinco kilómetros pensada para sillas de ruedas y carritos; preguntad por ella en taquilla si la necesitan.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'templo-venus',
    order: 2,
    name: 'Templo de Venus',
    latinName: 'Templum Veneris Pompeianae',
    category: 'templo',
    coords: [40.748425, 14.483872],
    regio: 'VIII.1.3',
    minutes: 10,
    walkMinutesToNext: 1,
    intro: 'Deteneos aquí un momento, en la terraza más privilegiada de toda la ciudad, dedicada a la diosa que le daba nombre y suerte.',
    narration: [
      'Venus no era una diosa cualquiera para los pompeyanos. Tras la guerra social, Roma convirtió la ciudad en una colonia militar de veteranos bajo el mando de Sila, y el nuevo nombre oficial pasó a ser Colonia Cornelia Veneria Pompeianorum. Venus Pompeiana se convirtió así en la protectora oficial de la ciudad, y este templo, construido sobre la terraza más alta y más visible desde el mar, era su gran escaparate.',
      'El edificio se levantaba en el centro de un patio porticado, rodeado de columnas de orden corintio, con mármoles de colores que llegaban desde Grecia y el norte de África. En el momento de la erupción se estaban llevando a cabo obras de remodelación, probablemente para reparar los daños del terremoto que había sacudido la ciudad diecisiete años antes. Por eso el templo que vemos hoy quedó a medio terminar para siempre.',
      'Lo que de verdad quita el aliento aquí es la vista. Mirad hacia el mar: esta terraza se construyó expresamente para que la diosa, y quien llegara en barco, viera primero este templo antes que ninguna otra cosa de la ciudad. Era, literalmente, la tarjeta de presentación de Pompeya para cualquier viajero que se acercara por mar.',
      'De la decoración original queda muy poco en pie. Buena parte del mármol fue arrancado siglos después de la erupción, ya en época medieval o moderna, para fabricar cal en hornos improvisados entre las ruinas. Aun así, la disposición de las columnas y el trazado del recinto permiten imaginar perfectamente la escala del santuario.',
    ],
    lookFor: [
      'La orientación de la terraza, pensada para ser vista desde el mar antes que cualquier otro edificio de la ciudad.',
      'Los restos de columnas corintias que rodeaban el patio del santuario.',
      'Las diferencias de altura y acabado que delatan las obras de reconstrucción inacabadas tras el terremoto anterior a la erupción.',
      'La panorámica actual del golfo de Nápoles, que ayuda a entender por qué se eligió este lugar exacto.',
    ],
    anecdote: 'El propio nombre oficial de la colonia romana, Colonia Cornelia Veneria Pompeianorum, llevaba a Venus incorporada como parte del título de la ciudad: no había forma más clara de declarar de quién eran estas tierras.',
    directionsToNext: 'Volved sobre vuestros pasos hacia la Via Marina y continuad hacia la plaza. A la izquierda, antes de entrar en el foro propiamente dicho, encontraréis la Basílica. Menos de tres minutos caminando.',
    illus: 'columna',
    tips: [
      'Es una parada corta pero muy fotogénica al amanecer, con el Vesubio al fondo; conviene no gastar aquí demasiado tiempo del recorrido total.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'basilica',
    order: 3,
    name: 'Basílica',
    category: 'foro',
    coords: [40.7488, 14.4845],
    regio: 'VIII.1.1',
    minutes: 10,
    walkMinutesToNext: 1,
    intro: 'Entramos en el edificio más grande de todo el foro: aquí no se rezaba, aquí se hacían negocios y se impartía justicia.',
    narration: [
      'Esta basílica es uno de los edificios de este tipo más antiguos que se conservan de todo el mundo romano, construida hacia el año ciento veinte antes de nuestra era. La palabra basílica no tenía entonces ningún sentido religioso: era sencillamente un gran salón cubierto, con naves separadas por columnas, donde se concentraba la vida legal y comercial de la ciudad.',
      'Imaginad este espacio lleno de gente: comerciantes cerrando tratos a voces, abogados discutiendo causas ante un juez, ciudadanos esperando su turno para resolver disputas de herencias o de deudas. Al fondo, sobre una plataforma elevada llamada tribunal, se sentaba el magistrado que administraba justicia. Las columnas que ven en pie, muy altas y estrechas, sostenían originalmente un segundo piso con una galería.',
      'Las paredes de la basílica están cubiertas de graffiti, algunos de ellos garabateados por gente que mataba el tiempo mientras esperaba su turno. Hay firmas, cálculos, incluso dibujos rápidos de gladiadores, que probablemente hacían soñar despiertos a más de un pompeyano aburrido durante una vista judicial interminable.',
      'Este modelo arquitectónico, un salón rectangular con naves y una cabecera para la autoridad, tuvo una segunda vida varios siglos después: cuando el cristianismo se convirtió en religión oficial del Imperio, adoptó precisamente esta forma para sus primeras grandes iglesias. Así que, en cierto modo, estamos delante del abuelo arquitectónico de buena parte de las catedrales que conocemos hoy.',
      'El propio pavimento de la basílica merece una mirada atenta, con sus grandes losas encajadas con precisión y ya bastante desgastadas por el tránsito constante de comerciantes y litigantes. La entrada principal, orientada hacia el foro, se resolvía mediante un pórtico elevado por unos escalones, de manera que quien entraba desde la plaza percibía de inmediato la solemnidad del edificio antes incluso de cruzar el umbral.',
    ],
    lookFor: [
      'La plataforma elevada del tribunal, al fondo del edificio, donde se sentaba el magistrado.',
      'Las altas columnas de ladrillo que en origen estaban revestidas de estuco imitando mármol.',
      'Los graffiti grabados en el estuco de las paredes, incluidos dibujos de gladiadores.',
      'La diferencia de anchura entre la nave central y las laterales, típica de este tipo de edificio civil.',
    ],
    anecdote: 'El escritor romano Vitrubio, que escribió el gran tratado de arquitectura de la Antigüedad, cita expresamente basílicas de este tipo como modelo a seguir para cualquier ciudad que se preciara de tener un foro digno.',
    directionsToNext: 'Salid de la basílica hacia la plaza del foro y girad a la derecha: el Templo de Apolo está en el lado oeste, apenas a un par de minutos.',
    image: { src: 'basilica', alt: 'Columnas de la Basílica de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'columna',
    tips: [
      'Hay poca sombra en esta zona a mediodía; es buen momento para beber agua antes de seguir hacia el foro abierto.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'templo-apolo',
    order: 4,
    name: 'Templo de Apolo',
    latinName: 'Templum Apollinis',
    category: 'templo',
    coords: [40.74921, 14.4844],
    regio: 'VII.7.32',
    minutes: 10,
    walkMinutesToNext: 3,
    intro: 'Este es el santuario más antiguo de toda Pompeya, dedicado al dios de la profecía y de la luz mucho antes de que la ciudad fuera romana.',
    narration: [
      'El culto a Apolo en este lugar se remonta al siglo seis antes de nuestra era, cuando Pompeya era todavía una ciudad de tradición etrusca y samnita, con fuerte influencia griega llegada a través de las colonias del sur de Italia. Es, con diferencia, el edificio religioso más antiguo documentado en todo el yacimiento, muy anterior al Templo de Venus o al de Júpiter que veremos enseguida.',
      'El templo que contemplan hoy es el resultado de sucesivas reconstrucciones, la última de ellas tras el terremoto que sacudió la ciudad en el año sesenta y dos, diecisiete años antes de la erupción final. Se alza sobre un podio alto, rodeado de treinta y ocho columnas de orden jónico que en su día estuvieron pintadas de colores vivos, algo que a menudo olvidamos al ver el mármol y la piedra desnudos de hoy.',
      'A ambos lados del pórtico de entrada había dos estatuas de bronce que representaban a Apolo y a su hermana Diana, ambos como arqueros, tensando el arco. Las originales se conservan en el Museo Arqueológico Nacional de Nápoles, y las que ven aquí son reproducciones, pero permiten hacerse una idea exacta de cómo se recibía a los fieles que entraban en el recinto sagrado.',
      'En el centro del patio hay también un altar y una columna que sostenía un reloj de sol, uno de los instrumentos de medición del tiempo más sofisticados que se han encontrado en la ciudad. Todo el conjunto refleja una época en la que Pompeya miraba tanto hacia Roma como hacia el mundo griego, y este templo es la prueba material más antigua de esa doble identidad.',
    ],
    lookFor: [
      'Las columnas jónicas que rodean el patio del templo, con restos de policromía en algunos capiteles.',
      'Las reproducciones en bronce de Apolo y Diana como arqueros, a ambos lados de la escalinata.',
      'La columna con el reloj de sol, en el centro del patio.',
      'El podio elevado del templo central, más alto que el resto del pavimento del recinto.',
    ],
    anecdote: 'En 1817, durante las excavaciones borbónicas, aparecieron aquí las estatuas originales de Apolo y Diana, tan bien conservadas que causaron sensación en toda Europa y alimentaron la moda neoclásica del momento.',
    directionsToNext: 'Cruzad el templo hacia el este, en dirección a la gran explanada abierta: han llegado al Foro. Apenas un minuto de camino.',
    image: { src: 'templo-apolo', alt: 'Columnas del Templo de Apolo en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'columna',
    tips: [
      'Buscad el ángulo desde la escalinata del templo: es uno de los mejores puntos para fotografiar el Vesubio enmarcado por las columnas.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'foro',
    order: 5,
    name: 'Foro',
    latinName: 'Forum',
    category: 'foro',
    coords: [40.749447, 14.484825],
    minutes: 20,
    walkMinutesToNext: 1,
    intro: 'Parad un momento en el centro exacto de la plaza: a un lado el Vesubio, al otro el Templo de Júpiter, y alrededor toda la vida pública de Pompeya.',
    narration: [
      'Este rectángulo alargado, de poco más de cien metros de largo, era el corazón político, religioso y comercial de la ciudad. Estaba cerrado al tráfico rodado mediante bloques de piedra colocados en sus accesos, así que en época romana solo se caminaba por aquí, exactamente igual que hacemos nosotros ahora. Alrededor se concentraban los edificios más importantes: templos, tribunales, mercados y sedes administrativas.',
      'Mirad hacia el norte: ahí se alza el Templo de Júpiter, conocido también como el Capitolio, dedicado a la tríada formada por Júpiter, Juno y Minerva. Su posición no es casual, porque desde ese punto exacto el templo queda perfectamente enmarcado por la silueta del Vesubio al fondo. Es una de las postales más repetidas y más impresionantes de toda Pompeya, y conviene recordar que, para los pompeyanos, aquella montaña no era un volcán peligroso, sino simplemente una montaña cubierta de viñedos.',
      'A ambos lados de la plaza corría un pórtico de columnas de dos pisos que daba sombra a los paseantes y protegía los escaparates de los comercios. En el extremo norte se conserva también un arco honorífico, probablemente dedicado al emperador Calígula o a algún miembro de su familia, que servía de acceso monumental hacia las termas del foro y hacia el barrio residencial más elegante de la ciudad.',
      'El foro era también el lugar donde se votaba, donde se celebraban ceremonias religiosas oficiales y donde los candidatos a magistrados hacían campaña electoral, algo que veremos reflejado más adelante en los graffiti pintados por toda la ciudad. Basta con pararse aquí en silencio un momento e imaginar el ruido de los vendedores, las discusiones políticas y las procesiones religiosas para entender que esto era, sencillamente, la plaza mayor de una ciudad viva y bulliciosa.',
    ],
    lookFor: [
      'El encuadre del Templo de Júpiter con el Vesubio exactamente detrás, en el extremo norte de la plaza.',
      'Los bloques de piedra en los accesos, que impedían el paso de carros a la plaza.',
      'Los restos del pórtico de columnas que recorría los lados largos del foro.',
      'El arco honorífico cercano al extremo norte, junto al acceso hacia las termas.',
    ],
    anecdote: 'En una de las casas de la ciudad apareció un relieve de mármol que representa el propio foro sacudido por un terremoto, con las estatuas y columnas tambaleándose: un raro testimonio antiguo de cómo vivieron los pompeyanos el gran seísmo del año sesenta y dos.',
    directionsToNext: 'Recorred el lado este de la plaza hacia el edificio con columnas de ladrillo rojo: ahí están el Edificio de Eumáquia y el Macellum, apenas a tres minutos.',
    image: { src: 'foro-vesubio', alt: 'El foro de Pompeya con el Vesubio al fondo', credit: 'Wikimedia Commons' },
    illus: 'foro',
    tips: [
      'Los baños públicos más cercanos al foro están junto a las Termas del Foro, nuestra próxima parada larga; aprovechad si lo necesitan.',
      'Es un buen punto para repartir el grupo un momento y dejar que cada uno busque su propia foto con el Vesubio de fondo.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'edificio-eumachia',
    order: 6,
    name: 'Edificio de Eumáquia y Macellum',
    category: 'comercio',
    coords: [40.7491654, 14.485323],
    regio: 'VII.9.1',
    minutes: 12,
    walkMinutesToNext: 4,
    intro: 'Aquí conocemos a la mujer más poderosa de la Pompeya conocida, y al lado, al mercado que alimentaba a toda la ciudad.',
    narration: [
      'El edificio grande que tienen delante lo construyó una mujer llamada Eumáquia, sacerdotisa pública y patrona del gremio de los batanadores, es decir, de quienes trabajaban con la lana y las telas. Lo dedicó a la Concordia Augusta y a la Piedad, dos virtudes muy queridas por el emperador de turno, y en su interior se encontró una estatua suya, hoy en el Museo Arqueológico de Nápoles, con una inscripción que deja muy claro quién pagaba y quién mandaba aquí.',
      'Que una mujer financiara un edificio público de este tamaño dice mucho sobre su fortuna y su influencia social, aunque no pudiera ocupar cargos políticos como los hombres. Es probable que el edificio funcionara como sede de negocios textiles y como lugar de reunión del gremio, una especie de bolsa de comercio de la lana en pleno centro de la ciudad.',
      'Justo al lado se encuentra el Macellum, el mercado cubierto de alimentos frescos de Pompeya. En el centro había un templete circular, probablemente destinado a la venta de pescado, con un desagüe central para limpiar los puestos con agua corriente. Alrededor se disponían tiendas más pequeñas para carne, pan y otros productos.',
      'En las excavaciones del Macellum aparecieron restos de espinas de pescado y huesos de animales que confirman su función, además de pinturas murales con escenas mitológicas que decoraban los muros. Entre el edificio de Eumáquia y el Macellum se resume perfectamente la doble cara del comercio pompeyano: por un lado, los grandes negocios textiles y las finanzas; por otro, la compra diaria de comida fresca para las familias de la ciudad.',
    ],
    lookFor: [
      'La gran entrada porticada del edificio de Eumáquia, con su inscripción dedicada a la Concordia Augusta.',
      'Los restos circulares del templete central del Macellum, donde probablemente se vendía pescado.',
      'El sistema de desagüe en el suelo del mercado, pensado para limpiar los puestos de pescado.',
      'Los fragmentos de pintura mural conservados en algunos muros del Macellum.',
    ],
    anecdote: 'La estatua de Eumáquia lleva una inscripción en la que se declara expresamente patrona de los batanadores: un gremio le agradecía en piedra, para la eternidad, el dinero que había puesto sobre la mesa.',
    directionsToNext: 'Salid del foro por el lado norte hacia la Via del Foro y tomad la Via delle Terme a la izquierda. Seguid esta calle unos trescientos cincuenta metros hasta la entrada de las Termas del Foro, unos siete minutos caminando.',
    image: { src: 'edificio-eumachia', alt: 'Fachada del Edificio de Eumáquia en el foro de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'columna',
    tips: [
      'Si el grupo va con niños, el Macellum es un buen sitio para explicar de forma sencilla cómo se compraba la comida en una ciudad romana.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'termas-foro',
    order: 7,
    name: 'Termas del Foro',
    latinName: 'Thermae Forenses',
    category: 'termas',
    coords: [40.7504, 14.4841],
    regio: 'VII.5.24',
    minutes: 15,
    walkMinutesToNext: 1,
    intro: 'Entramos en unas termas pequeñas pero casi perfectamente conservadas, construidas nada más fundarse la colonia romana.',
    narration: [
      'Estas termas se levantaron muy poco después de que Pompeya se convirtiera en colonia romana, hacia el año ochenta antes de nuestra era, y funcionan como un manual perfecto de cómo era el ritual del baño en el mundo romano. A diferencia de las Termas Estabianas, que veremos más adelante, aquí todo está a una escala más manejable, lo que permite entender con claridad cada sala y su función.',
      'El recorrido del baño comenzaba en el apodyterium, el vestuario, donde cada cliente dejaba su ropa en pequeñas hornacinas. De ahí se pasaba al frigidarium, la sala fría, después al tepidarium, templado, y finalmente al caldarium, la sala caliente, calentada por un sistema de hipocausto: un suelo elevado sobre pequeñas columnas de ladrillo por donde circulaba aire caliente procedente de un horno.',
      'Fijaos en el techo abovedado del vestuario masculino, decorado con estucos y con una serie de figuras llamadas telamones, especie de atlantes en miniatura que parecen sostener con esfuerzo la repisa superior. Es una de las decoraciones interiores mejor conservadas de todo el complejo termal de Pompeya, y da una idea de lo cuidada que era la estética incluso en un edificio de uso tan cotidiano.',
      'Como en casi todas las termas romanas, existían secciones separadas para hombres y para mujeres, con accesos independientes desde la calle, aunque compartían el mismo horno y el mismo sistema de calefacción. Ir a las termas no era solo cuestión de higiene: era también un lugar de socialización, de negocios informales y de puro chismorreo, algo que cualquier ciudad mediterránea actual reconocería sin dificultad.',
    ],
    lookFor: [
      'El techo abovedado y estucado del vestuario masculino, con las figuras de telamones sosteniendo la repisa.',
      'Las columnillas de ladrillo del hipocausto, visibles en algunas salas donde se ha retirado el suelo original.',
      'Las hornacinas del apodyterium, donde los clientes guardaban su ropa mientras se bañaban.',
      'La diferencia de tamaño y decoración entre la sección masculina y la femenina.',
    ],
    anecdote: 'El filósofo Séneca, que vivió una temporada cerca de aquí, se quejaba por escrito del ruido insoportable que llegaba desde unas termas vecinas a su alojamiento: gritos de masajistas, chapoteos y algún que otro cantante entusiasmado con la acústica de la sala.',
    directionsToNext: 'Salid de las termas y tomad la Via delle Terme hacia el oeste, después girad por el Vicolo di Modesto: la Casa del Poeta Trágico está a mano izquierda, unos cuatro minutos a pie.',
    image: { src: 'termas-foro', alt: 'Interior de las Termas del Foro en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'termas',
    tips: [
      'Hay baños públicos modernos muy cerca, en la zona del foro; conviene usarlos antes de adentrarse en el barrio de las domus.',
      'El suelo de algunas salas es irregular; caminad despacio si llevan calzado de suela lisa.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'casa-poeta-tragico',
    order: 8,
    name: 'Casa del Poeta Trágico',
    latinName: 'Domus Poetae Tragici',
    category: 'domus',
    coords: [40.750672, 14.483814],
    regio: 'VI.8.5',
    minutes: 10,
    walkMinutesToNext: 2,
    intro: 'Antes de entrar, miren al suelo: un perro de mosaico les está advirtiendo, en latín, que tengáis cuidado.',
    narration: [
      'Esta casa no es de las más grandes de Pompeya, pero es probablemente una de las más conocidas gracias a un pequeño detalle en el umbral de la entrada: un mosaico que representa un perro atado con cadena, con la inscripción cave canem, es decir, cuidado con el perro. Es una de las imágenes más reproducidas de todo el mundo romano, y muchos visitantes vienen a Pompeya solo para verla con sus propios ojos.',
      'La casa recibió su nombre moderno por otro mosaico, hoy conservado en el Museo Arqueológico de Nápoles, que representa el ensayo de una compañía teatral antes de una representación, con actores probándose máscaras y un director dando instrucciones. Aquella escena, junto con otras pinturas de tema mitológico que decoraban las paredes, llevó a los primeros excavadores a imaginar que aquí había vivido un poeta dedicado al teatro trágico, aunque no hay ninguna prueba real de quién habitó la casa.',
      'A pesar de su tamaño modesto, la vivienda sigue el esquema clásico de la domus romana: un atrio central con su apertura al cielo para recoger el agua de lluvia, habitaciones alrededor, y al fondo un pequeño jardín porticado. Las pinturas que decoraban las paredes, hoy muy deterioradas por la exposición al aire libre durante casi dos siglos de excavaciones, representaban escenas de la mitología griega como el sacrificio de Ifigenia o el abandono de Ariadna.',
      'Esta casa alcanzó una fama inesperada en el siglo diecinueve gracias a la novela Los últimos días de Pompeya, del escritor británico Edward Bulwer-Lytton, que situó aquí parte de su trama. Aquella novela, un auténtico éxito de ventas en su época, contribuyó más que cualquier tratado académico a popularizar Pompeya entre el gran público europeo.',
    ],
    lookFor: [
      'El mosaico del perro encadenado con la inscripción cave canem en el umbral de entrada.',
      'La disposición clásica de atrio, habitaciones e impluvium para recoger el agua de lluvia.',
      'Los restos de pintura mural con escenas mitológicas en las paredes del interior.',
      'El pequeño jardín porticado al fondo de la vivienda.',
    ],
    anecdote: 'El mosaico original del cave canem sigue in situ, protegido por un cristal, exactamente donde lo pisaron durante generaciones los visitantes y los propios habitantes de la casa antes del año setenta y nueve.',
    directionsToNext: 'Seguid por el Vicolo di Modesto hasta la Via della Fortuna y girad a la derecha: la entrada a la Casa del Fauno, la mayor mansión de Pompeya, está a menos de cuatro minutos.',
    image: { src: 'cave-canem', alt: 'Mosaico cave canem en la Casa del Poeta Trágico', credit: 'Wikimedia Commons' },
    illus: 'mosaico',
    tips: [
      'La entrada suele estar acordonada para proteger el mosaico original; se ve perfectamente sin necesidad de pisar el umbral.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'casa-fauno',
    order: 9,
    name: 'Casa del Fauno',
    latinName: 'Domus Fauni',
    category: 'domus',
    coords: [40.75125, 14.484583],
    regio: 'VI.12.2',
    minutes: 18,
    walkMinutesToNext: 2,
    intro: 'Ocupamos ahora una manzana entera de la ciudad: esta es, sin discusión, la casa privada más grande de toda Pompeya.',
    narration: [
      'La Casa del Fauno ocupa por sí sola una manzana completa, casi tres mil metros cuadrados, lo que la convierte en la vivienda privada más extensa jamás encontrada en la ciudad. Se construyó a comienzos del siglo dos antes de nuestra era, en plena época de expansión y riqueza samnita, y su tamaño y su lujo hacen pensar en una de las familias más poderosas de la Pompeya prerromana.',
      'La casa tiene, de hecho, dos atrios y dos peristilos, es decir, dos conjuntos completos de patios y jardines porticados, algo excepcional incluso para los estándares más altos de la arquitectura doméstica romana. Recibe su nombre moderno de una pequeña estatua de bronce, un fauno danzante, encontrada en el atrio principal; la que ven hoy es una copia, ya que el original se conserva en el Museo Arqueológico de Nápoles.',
      'Pero el verdadero tesoro de esta casa es el mosaico de Alejandro, una obra maestra de más de veinte metros cuadrados compuesta por millones de diminutas teselas, que representaba el enfrentamiento entre Alejandro Magno y el rey persa Darío en la batalla de Iso. Se cree que es copia de un cuadro griego original, hoy perdido, y es una de las piezas de arte antiguo más estudiadas del mundo. El original también se trasladó a Nápoles para su conservación.',
      'Recorrer esta casa, aunque hoy veamos sobre todo suelos, arranques de columnas y muros bajos, sirve para entender la escala de las élites pompeyanas antes de la llegada de Roma. Aquí no solo se vivía: se recibía a clientes, se negociaban acuerdos y se exhibía riqueza y cultura griega ante cualquier visitante importante que cruzara el umbral.',
    ],
    lookFor: [
      'Las huellas en el suelo de los dos atrios y los dos peristilos que estructuran la casa.',
      'La reproducción del fauno danzante en el atrio principal.',
      'El lugar exacto donde apareció el mosaico de Alejandro, hoy señalado, aunque el original esté en Nápoles.',
      'Los suelos de mosaico geométrico que aún se conservan en varias estancias.',
    ],
    anecdote: 'Cuando se descubrió el mosaico de Alejandro en 1831, el hallazgo causó tal sensación que el propio rey de Nápoles ordenó trasladarlo de inmediato a la capital, dejando en la casa únicamente una reproducción para los visitantes.',
    directionsToNext: 'Seguid por el Vicolo dei Vettii, la calle lateral hacia el norte: la Casa de los Vettii está a apenas dos minutos.',
    image: { src: 'casa-fauno', alt: 'Peristilo de la Casa del Fauno en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'mosaico',
    tips: [
      'Es una parada extensa: reservad tiempo suficiente, porque la casa es literalmente del tamaño de una manzana entera.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'casa-vettii',
    order: 10,
    name: 'Casa de los Vettii',
    latinName: 'Domus Vettiorum',
    category: 'domus',
    coords: [40.752083, 14.484583],
    regio: 'VI.15.1',
    minutes: 18,
    walkMinutesToNext: 5,
    intro: 'Dos hermanos libertos, hechos a sí mismos, decoraron esta casa para que nadie dudara de lo lejos que habían llegado.',
    narration: [
      'La Casa de los Vettii perteneció a dos hermanos, Aulo Vettio Restituto y Aulo Vettio Convivio, que habían sido esclavos y consiguieron la libertad antes de amasar una notable fortuna, probablemente gracias al comercio. Al no poder acceder a los cargos políticos reservados a los ciudadanos de nacimiento libre, invirtieron su dinero en lo que sí estaba a su alcance: convertir su casa en un escaparate de buen gusto y de riqueza.',
      'Nada más entrar, en el vestíbulo, hay una pintura de Príapo pesando su enorme miembro viril en una balanza frente a un saco de monedas. Puede sorprender a primera vista, pero en la cultura romana era un símbolo perfectamente serio de prosperidad y de protección contra la envidia ajena, y se colocaba deliberadamente en un lugar visible para dar la bienvenida a cualquier visitante.',
      'El resto de la casa está decorado en lo que los historiadores del arte llaman cuarto estilo pompeyano, con paneles de color rojo intenso y amarillo que enmarcan escenas mitológicas: Ariadna abandonada, Hércules niño estrangulando serpientes, Dédalo e Ícaro. En una de las habitaciones más pequeñas, de acceso restringido, se conserva un ciclo de pinturas de tema erótico que probablemente formaba parte de la decoración privada de los dueños.',
      'La casa fue restaurada durante años y reabierta al público en 2023 con su jardín interior recreado tal como lucía en el año setenta y nueve, con estatuas, fuentes y plantas dispuestas según los restos de raíces encontrados por los arqueólogos. Pasear por ese jardín es probablemente lo más parecido que podemos hacer hoy a visitar realmente una casa romana en pleno funcionamiento.',
    ],
    lookFor: [
      'La pintura de Príapo pesando su miembro en una balanza, en el vestíbulo de entrada.',
      'Los paneles rojos del cuarto estilo pompeyano con escenas mitológicas en las salas principales.',
      'El jardín central restaurado, con sus fuentes, estatuas y plantación reconstruida.',
      'La sala con las pinturas de tema erótico, de acceso a veces restringido o por turnos.',
    ],
    anecdote: 'Los hermanos Vettii nunca llegaron a tener un apellido de rancio abolengo romano, pero lograron que su casa fuera, con el tiempo, una de las más visitadas y admiradas de todo el yacimiento: la mejor venganza posible contra el estigma de haber nacido esclavos.',
    directionsToNext: 'Bajad de nuevo por el Vicolo dei Vettii hasta la Via della Fortuna, girad hacia el Vicolo Storto y cruzad la Via Stabiana hasta el Vicolo del Lupanare. El Lupanar está a la derecha, unos siete minutos de camino.',
    image: { src: 'casa-vettii-fresco', alt: 'Fresco del cuarto estilo pompeyano en la Casa de los Vettii', credit: 'Wikimedia Commons' },
    illus: 'fresco',
    tips: [
      'Es una de las casas con más aforo limitado y colas en horas centrales; si pueden elegir, visitadla a primera hora.',
      'La sala de las pinturas eróticas a veces abre por turnos controlados por el personal del recinto.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'lupanar',
    order: 11,
    name: 'Lupanar',
    category: 'comercio',
    coords: [40.75025, 14.486778],
    regio: 'VII.12.18',
    minutes: 12,
    walkMinutesToNext: 2,
    intro: 'Este es el único burdel construido expresamente como tal que se ha identificado en toda Pompeya.',
    narration: [
      'A diferencia de otros locales de la ciudad donde también se ejercía la prostitución de forma más discreta, este edificio se construyó desde el principio con esa única función. Tiene dos plantas: en la de abajo se alinean cinco celdas pequeñas, cada una con una cama de obra fabricada en piedra, que en su día se cubría con un colchón; arriba había habitaciones algo más amplias, probablemente reservadas a clientes de mayor poder adquisitivo.',
      'Sobre el dintel de cada puerta hay una pequeña pintura erótica que representa distintas posturas, y durante mucho tiempo se interpretó como una especie de carta de servicios para clientes que no sabían leer o que hablaban otras lenguas, dado el ajetreo del puerto y la llegada constante de viajeros de toda la cuenca mediterránea. Los historiadores actuales matizan esa lectura, pero la función decorativa y sugerente de las pinturas es innegable.',
      'Las paredes están literalmente cubiertas de graffiti, más de ciento cincuenta inscripciones conservadas, con nombres de mujeres y de hombres, valoraciones sobre los servicios recibidos, precios en ases, que era la moneda de cobre más común, y algún que otro comentario que no ha perdido un ápice de mala idea con el paso de los siglos.',
      'Este lugar nos permite hablar sin tapujos de una realidad muy presente en cualquier ciudad portuaria de la Antigüedad: la esclavitud sexual y el trabajo forzado de muchas de las mujeres, y también de algunos hombres, que trabajaban aquí, casi siempre en condiciones muy alejadas de cualquier idea romántica. Detrás del morbo turístico que suele rodear esta parada hay, sobre todo, una historia dura de personas sin ningún poder de decisión sobre su propia vida.',
    ],
    lookFor: [
      'Las camas de obra de piedra en cada una de las cinco celdas de la planta baja.',
      'Las pequeñas pinturas eróticas sobre los dinteles de las puertas.',
      'Los graffiti con nombres, precios y comentarios grabados en las paredes.',
      'La estrechez y sencillez de las celdas, muy alejada de cualquier decoración lujosa.',
    ],
    anecdote: 'Entre los graffiti conservados hay frases tan simples como aquí gocé de una mujer estupenda, firmadas por clientes anónimos que jamás imaginaron que sus palabras se leerían casi dos mil años después por turistas de todo el mundo.',
    directionsToNext: 'Salid a la Via degli Augustali y tomad el Vicolo del Lupanare hacia la Via Stabiana: las Termas Estabianas están justo en la esquina, a dos minutos.',
    image: { src: 'lupanar-fresco', alt: 'Pinturas eróticas sobre los dinteles del Lupanar de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'lupanar',
    tips: [
      'Es la parada con más cola de todo el recorrido; el aforo dentro es muy reducido y conviene tener paciencia o volver más tarde.',
      'El acceso tiene un escalón alto y un pasillo estrecho, poco cómodo para movilidad reducida.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'termas-estabianas',
    order: 12,
    name: 'Termas Estabianas',
    latinName: 'Thermae Stabianae',
    category: 'termas',
    coords: [40.749921, 14.487616],
    regio: 'VII.1.8',
    minutes: 15,
    walkMinutesToNext: 1,
    intro: 'Estas son las termas más antiguas y más completas de Pompeya, en pie desde la época samnita.',
    narration: [
      'Las Termas Estabianas tienen su origen en el siglo dos antes de nuestra era, en época samnita, mucho antes de que Pompeya se convirtiera en colonia romana. A lo largo de los siglos siguientes se fueron ampliando y modernizando, hasta convertirse en el complejo termal más grande y más completo de toda la ciudad, con capacidad para atender a un número considerable de bañistas a la vez.',
      'El conjunto incluye una gran palestra al aire libre, un patio porticado destinado al ejercicio físico antes del baño, con lucha, boxeo o simples paseos. Desde ahí se accedía a las distintas salas: vestuarios separados para hombres y mujeres, salas frías, templadas y calientes, y una piscina descubierta, la natatio, para nadar al aire libre.',
      'El techo del vestuario masculino conserva una decoración de estuco excepcional, con relieves de figuras aladas, animales fantásticos y motivos vegetales que muestran el nivel de detalle que se ponía incluso en los espacios de paso. El sistema de calefacción, mediante hipocausto y paredes huecas por donde circulaba el aire caliente, permitía mantener temperaturas muy distintas de una sala a otra con un control sorprendentemente eficaz para la tecnología de la época.',
      'Estar aquí ayuda a entender que ir a las termas era una parte central de la rutina diaria de cualquier pompeyano, rico o modesto, ya que la entrada solía costar una cantidad simbólica de dinero. Se venía a lavarse, sí, pero también a hacer ejercicio, a cerrar negocios, a ponerse al día de los chismes de la ciudad y, simplemente, a pasar el rato con los vecinos.',
    ],
    lookFor: [
      'La gran palestra porticada al aire libre, usada para el ejercicio físico antes del baño.',
      'Los relieves de estuco en el techo abovedado del vestuario masculino.',
      'La piscina descubierta o natatio, destinada a la natación al aire libre.',
      'Las columnillas de ladrillo del hipocausto en las salas donde se conserva a la vista.',
    ],
    anecdote: 'Los romanos consideraban de mala educación bañarse antes de mediodía; las termas abrían sobre todo por la tarde, y acudir demasiado pronto era casi tan mal visto como llegar demasiado tarde a una cena de gala.',
    directionsToNext: 'Salid a la Via Stabiana y cruzad justo enfrente: han llegado al cruce con la Via dell’Abbondanza, con sus pasos de peatones de piedra y sus fuentes públicas. Un minuto de camino.',
    image: { src: 'termas-estabianas', alt: 'Palestra de las Termas Estabianas en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'termas',
    tips: [
      'Hay aseos públicos junto a la entrada de las termas, últimos antes de adentrarse en la Via dell’Abbondanza.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'via-abbondanza',
    order: 13,
    name: 'Cruce de la Via dell’Abbondanza',
    category: 'calle',
    coords: [40.7498, 14.4878],
    minutes: 15,
    walkMinutesToNext: 2,
    intro: 'Pisamos ahora la calle principal de Pompeya, con sus pasos de piedra, sus fuentes y las paredes cubiertas de propaganda electoral.',
    narration: [
      'La Via dell’Abbondanza era la gran arteria comercial de la ciudad, la calle más larga y más concurrida, que unía el foro con las zonas residenciales del este y con la Puerta de Sarno. Cruza aquí mismo con la Via Stabiana, uno de los dos grandes ejes que organizaban toda la trama urbana de Pompeya, así que este cruce era, literalmente, el centro neurálgico del tráfico peatonal de la ciudad.',
      'Fijaos en las grandes piedras colocadas en mitad de la calzada, con espacios entre ellas. Servían para que los peatones cruzaran de una acera a otra sin mojarse los pies, ya que estas calles se inundaban con facilidad con el agua de lluvia y con los vertidos domésticos, mientras que los huecos entre piedra y piedra dejaban pasar las ruedas de los carros, calculadas exactamente al mismo ancho en toda la ciudad.',
      'En las fachadas de esta zona todavía se leen restos de pinturas electorales, llamadas programmata, con las que distintos grupos de vecinos, gremios o incluso colectivos como los panaderos o las lavanderas pedían el voto para sus candidatos favoritos a las elecciones municipales. Es una de las formas de propaganda política más antiguas que se conservan escritas directamente sobre un muro real.',
      'Un poco más adelante en esta misma calle se encuentra el termopolio de Asellina, un mostrador de comida rápida con grandes recipientes empotrados donde se guardaban alimentos calientes: guisos, legumbres, vino especiado. Este tipo de locales eran habituales en una ciudad donde muchas viviendas modestas carecían de cocina propia, así que buena parte de la población comía a diario fuera de casa, exactamente igual que hacen hoy millones de personas en cualquier ciudad mediterránea.',
    ],
    lookFor: [
      'Los pasos de peatones de piedra en mitad de la calzada, con el hueco calculado para las ruedas de los carros.',
      'Las rodadas profundas marcadas en las losas de piedra volcánica por el paso constante de carros.',
      'Los restos de pintura electoral, o programmata, en las fachadas cercanas al cruce.',
      'El mostrador con recipientes empotrados del termopolio de Asellina, un poco más adelante en la misma calle.',
    ],
    anecdote: 'Algunas de las pintadas electorales conservadas fueron firmadas, según se cree, por las prostitutas o por los propios tenderos del barrio: una prueba de que, aunque no todos podían votar, casi todo el mundo tenía una opinión política que dejar por escrito.',
    directionsToNext: 'Continuad hacia el este por la Via dell’Abbondanza. Pasado el termopolio de Asellina, seguid unos trescientos metros hasta la Fullonica de Stephanus, a mano derecha, unos seis minutos de camino.',
    image: { src: 'via-abbondanza', alt: 'Pasos de peatones de piedra en la Via dell’Abbondanza', credit: 'Wikimedia Commons' },
    illus: 'termopolio',
    tips: [
      'Las piedras del cruce son irregulares y resbalan si ha llovido: pisad con cuidado al cruzar.',
      'Hay una fuente pública de piedra muy cerca del cruce; en varios puntos de la calle encontrarán otras similares para refrescarse.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'fullonica-stephanus',
    order: 14,
    name: 'Fullonica de Stephanus',
    category: 'comercio',
    coords: [40.750311, 14.489139],
    regio: 'I.6.7',
    minutes: 12,
    walkMinutesToNext: 2,
    intro: 'Una casa señorial reconvertida en lavandería industrial: así reciclaban los pompeyanos el espacio urbano.',
    narration: [
      'Esta fullonica era un taller de lavado y tratamiento de telas, propiedad de un tal Stephanus, cuyo nombre aparece en pintadas electorales encontradas en la fachada. Lo interesante es que el edificio no se construyó de cero para esta función, sino que se instaló dentro de lo que originalmente había sido una casa privada de cierto nivel, aprovechando su atrio y sus habitaciones para el nuevo uso industrial.',
      'El proceso de limpieza de la ropa en época romana era bastante distinto del actual. Las telas se pisaban con los pies dentro de pequeñas cubas o pilas, mezclando agua con tierra de batán y con orina humana recogida a propósito en ánforas colocadas en las esquinas de las calles, ya que el amoniaco de la orina servía como agente desengrasante. Después las prendas se aclaraban, se estiraban y se prensaban para darles forma.',
      'Todavía se conservan varias de esas pilas escalonadas donde los trabajadores, generalmente esclavos o libertos, permanecían de pie durante horas pisando la ropa con un movimiento rítmico parecido al de quien pisa uva para hacer vino. También se ha conservado parte de la prensa de tela, una estructura de madera y piedra que aplanaba las prendas ya limpias antes de devolverlas a sus dueños.',
      'Esta fullonica es un ejemplo perfecto de cómo funcionaba la economía urbana de Pompeya: nada se desperdiciaba, ni siquiera la orina de los transeúntes, y cualquier espacio doméstico podía transformarse en un pequeño negocio si la ocasión lo permitía. Detrás de la elegancia de las domus que hemos visitado antes había también, muy cerca, un mundo de trabajo manual duro y de olores que hoy nos costaría mucho soportar.',
    ],
    lookFor: [
      'Las pilas escalonadas de piedra donde se pisaba la ropa con los pies.',
      'Los restos de la estructura de la prensa de telas al fondo del taller.',
      'La disposición del antiguo atrio de la casa, reconvertido en zona de trabajo con tinas de lavado.',
      'Las pinturas y graffiti electorales con el nombre de Stephanus en la fachada exterior.',
    ],
    anecdote: 'En varias esquinas de Pompeya se han encontrado restos de ánforas empotradas en la calle: los propios ciudadanos orinaban ahí a cambio de nada, sin saber que estaban surtiendo de materia prima gratuita a negocios como este.',
    directionsToNext: 'Seguid por la Via dell’Abbondanza y girad por el Vicolo di Paquio Proculo hacia la Via di Nola: la Casa del Menandro está un poco más al sur, unos siete minutos caminando.',
    image: { src: 'fullonica-stephanus', alt: 'Pilas de lavado de la Fullonica de Stephanus en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'domus',
    tips: [
      'El suelo de las pilas suele estar húmedo o resbaladizo tras la lluvia; extremad la precaución.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'casa-menandro',
    order: 15,
    name: 'Casa del Menandro',
    latinName: 'Domus Menandri',
    category: 'domus',
    coords: [40.749722, 14.49],
    regio: 'I.10.4',
    minutes: 14,
    walkMinutesToNext: 4,
    intro: 'En esta casa vivía, probablemente, alguien emparentado con la propia familia imperial romana, y guardaba un tesoro escondido.',
    narration: [
      'La Casa del Menandro es una de las viviendas más extensas y mejor conservadas de Pompeya, con un peristilo ajardinado, unas termas privadas propias y una serie de habitaciones decoradas con pinturas de gran calidad. Los estudios sobre los sellos encontrados en el interior apuntan a que pudo pertenecer a una rama de la familia de Popea Sabina, la segunda esposa del emperador Nerón, lo que explicaría tanto lujo en una casa privada.',
      'El nombre moderno de la casa procede de un fresco que representa al comediógrafo griego Menandro sentado con un rollo de papiro en la mano, en una de las salas del peristilo. La familia propietaria, aunque itálica, quiso rodearse de referencias a la cultura griega clásica, algo habitual entre las élites romanas de la época, que consideraban el griego la lengua de la alta cultura.',
      'El hallazgo más espectacular de esta casa fue un pequeño tesoro de ciento dieciocho piezas de plata, entre vajilla, copas y cucharas, escondido dentro de un arcón bajo la escalera de un sótano durante la erupción, probablemente por algún habitante que esperaba volver a recuperarlo cuando pasara el peligro. Nunca pudo hacerlo, y las piezas permanecieron ocultas hasta su descubrimiento en el siglo veinte.',
      'La casa contaba también con sus propios baños privados, algo poco frecuente incluso entre las familias acomodadas de Pompeya, lo que confirma el altísimo nivel económico de sus propietarios. Recorrerla permite entender que, en la cúspide de la sociedad pompeyana, la línea entre vivienda privada y pequeño palacio era, en la práctica, bastante difusa.',
    ],
    lookFor: [
      'El fresco con el retrato del comediógrafo Menandro en una de las salas del peristilo.',
      'El peristilo ajardinado con columnas, uno de los más amplios y elegantes del yacimiento.',
      'La zona de las termas privadas, poco habitual en una vivienda particular.',
      'El acceso al sótano donde apareció escondido el tesoro de plata.',
    ],
    anecdote: 'El tesoro de plata de la Casa del Menandro se considera uno de los mayores conjuntos de vajilla de plata romana conservados en su contexto original, y hoy puede verse expuesto en el Museo Arqueológico Nacional de Nápoles.',
    directionsToNext: 'Volved hacia la Via Stabiana y bajad por el Vicolo del Balcone Pensile hasta la Via dei Teatri: el conjunto del Teatro Grande, el Odeón y el Cuadripórtico está al fondo, unos siete minutos de camino.',
    image: { src: 'casa-menandro', alt: 'Peristilo de la Casa del Menandro en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'domus',
    tips: [
      'Es una casa amplia y a veces con acceso restringido a ciertas salas por turnos de conservación; consultad el panel de la entrada.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'teatro-grande',
    order: 16,
    name: 'Teatro Grande, Odeón y Cuadripórtico',
    category: 'espectaculo',
    coords: [40.748795, 14.488416],
    regio: 'VIII.7',
    minutes: 20,
    walkMinutesToNext: 1,
    intro: 'Entramos en el barrio de los espectáculos: un gran teatro al aire libre, un pequeño teatro cubierto para música, y un patio que terminó siendo cuartel de gladiadores.',
    narration: [
      'El Teatro Grande aprovecha la pendiente natural del terreno, siguiendo la tradición griega de excavar las gradas directamente en la ladera de una colina, una técnica más económica que levantar toda la estructura desde cero. Se construyó en el siglo segundo antes de nuestra era y fue remodelado ya en época imperial gracias al mecenazgo de una familia local, los Holconios, que financiaron buena parte de las obras de ampliación. Tenía capacidad para varios miles de espectadores que venían a ver representaciones teatrales, principalmente comedias y mimos populares.',
      'Justo al lado se encuentra el Odeón, un teatro más pequeño y completamente cubierto, pensado para conciertos de música, recitales de poesía y otros espectáculos que requerían mejor acústica y menos aforo. La cubierta, hoy desaparecida, permitía además representaciones durante el invierno o con mal tiempo, algo imposible en el teatro grande, siempre al aire libre.',
      'Detrás de ambos edificios se extiende un gran patio porticado, el Cuadripórtico, que originalmente servía como zona de paseo y de descanso para el público durante los entreactos, protegido del sol o de la lluvia bajo sus columnas. Con el tiempo, sin embargo, este espacio cambió radicalmente de función: se transformó en cuartel y escuela de gladiadores, con celdas para alojarlos y un almacén de armas.',
      'En ese cuartel, durante la erupción del año setenta y nueve, quedaron atrapadas varias personas, entre ellas gladiadores, y se recuperaron cascos y armas decoradas que hoy se exhiben en distintos museos. Es un buen recordatorio de que los espacios de una ciudad romana no eran estáticos: un patio de recreo tranquilo podía convertirse, con los años, en algo completamente distinto según las necesidades del momento.',
    ],
    lookFor: [
      'Las gradas del Teatro Grande, excavadas directamente en la pendiente natural del terreno.',
      'La estructura cerrada y compacta del Odeón, pensada para conciertos y recitales.',
      'Las columnas del Cuadripórtico que rodean el gran patio situado detrás de los teatros.',
      'Los restos de las celdas donde se alojaba a los gladiadores en el mismo patio.',
    ],
    anecdote: 'Entre los objetos hallados en el cuartel de gladiadores hay cascos decorados con escenas de amazonas y relieves mitológicos: piezas más pensadas para desfilar antes del combate que para servir de protección real.',
    directionsToNext: 'Salid del Cuadripórtico hacia el sur: el Templo de Isis está a apenas dos minutos, justo detrás del teatro.',
    image: { src: 'teatro-grande', alt: 'Gradas del Teatro Grande de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'teatro',
    tips: [
      'Las gradas de piedra son altas y sin pasamanos en varios tramos; tengáis cuidado si bajan hasta la orquesta.',
      'Es una buena zona de sombra parcial a media mañana gracias a las columnas del Cuadripórtico.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'templo-isis',
    order: 17,
    name: 'Templo de Isis',
    latinName: 'Templum Isidis',
    category: 'templo',
    coords: [40.7492, 14.4883],
    regio: 'VIII.7.28',
    minutes: 12,
    walkMinutesToNext: 10,
    intro: 'Un templo egipcio en pleno corazón de una ciudad romana, financiado por un liberto que quería comprarle a su hijo un futuro político.',
    narration: [
      'El culto a la diosa egipcia Isis se había extendido por todo el Mediterráneo tras la conquista romana de Egipto, y Pompeya no fue una excepción. Este templo quedó completamente destruido por el terremoto del año sesenta y dos y fue reconstruido enteramente por un liberto llamado Numerio Popidio Ampliato, según reza una inscripción encontrada en el lugar, en nombre de su hijo, un niño de solo seis años.',
      'La razón no era solo religiosa: al no poder los libertos ocupar cargos públicos, muchos invertían su fortuna en financiar edificios a nombre de sus hijos nacidos ya libres, comprándoles de facto un puesto en el consejo municipal gracias a semejante generosidad. El pequeño Numerio Popidio Celsino, gracias al templo pagado por su padre, entró en el consejo de decuriones de la ciudad siendo todavía un niño.',
      'Dentro del recinto se conserva una pequeña piscina llamada purgatorium, donde se guardaba agua sagrada, se creía que traída directamente del río Nilo, utilizada en los rituales de purificación de los sacerdotes. Las paredes del templo estaban decoradas con escenas que mezclaban mitología egipcia y romana, hoy conservadas en el Museo Arqueológico Nacional de Nápoles.',
      'El descubrimiento de este templo en el siglo dieciocho provocó una auténtica fiebre por lo egipcio en toda Europa, que llegó incluso a la ópera: se dice que inspiró parte de la ambientación de La flauta mágica de Mozart, y desde luego alimentó la moda decorativa egipcia que triunfó en los salones neoclásicos de finales de aquel siglo.',
      'El pequeño templo se levanta sobre un podio alto rodeado de columnas, con un altar situado justo frente a la escalinata de acceso, donde se realizaban ofrendas antes de entrar en el recinto sagrado. Junto a él había también una sala destinada a los banquetes rituales de los sacerdotes, decorada igualmente con motivos egipcios, que completaba el conjunto de este pequeño pero intenso santuario extranjero dentro de una ciudad profundamente romana.',
    ],
    lookFor: [
      'La pequeña piscina del purgatorium, destinada al agua sagrada de los rituales de purificación.',
      'Los restos del altar principal, frente a la escalinata de acceso al templo.',
      'La inscripción, hoy en réplica, que recuerda la reconstrucción financiada por Numerio Popidio Ampliato.',
      'Las columnas y el pórtico que rodean el pequeño patio del santuario.',
    ],
    anecdote: 'El niño en cuyo nombre se reconstruyó este templo entró en el consejo municipal sin haber cumplido la edad mínima habitual, gracias únicamente al dinero de su padre: una forma de ascenso social tan antigua como eficaz.',
    directionsToNext: 'Salid hacia la Via Stabiana y tomad la Via dell’Abbondanza hacia el este durante unos quinientos metros, hasta la altura de la Via di Championnet: la Casa de la Venus en la Concha está a la izquierda, unos nueve minutos de camino.',
    image: { src: 'templo-isis', alt: 'Restos del Templo de Isis en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'columna',
    tips: [
      'Es una parada tranquila y con poca afluencia comparada con otras cercanas; buen momento para sentarse un momento a la sombra.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'casa-venus-concha',
    order: 18,
    name: 'Casa de la Venus en la Concha',
    latinName: 'Domus Veneris in Conchiglia',
    category: 'domus',
    coords: [40.751957, 14.492723],
    regio: 'II.3.3',
    minutes: 10,
    walkMinutesToNext: 3,
    intro: 'Al fondo del jardín de esta casa modesta apareció una de las imágenes más fotografiadas de toda Pompeya.',
    narration: [
      'Esta vivienda es de tamaño discreto comparada con las grandes domus que hemos visitado antes, pero guarda en su jardín una de las pinturas murales más celebradas de todo el yacimiento: una Venus de tamaño casi natural, reclinada dentro de una enorme concha marina, flanqueada por dos pequeños amorcillos y con una estatua de Marte cercana observando la escena.',
      'La pintura se conserva directamente sobre el muro que cierra el jardín, expuesta a la intemperie desde su descubrimiento, lo cual explica que hoy la vean protegida por una estructura de cristal que intenta frenar el deterioro provocado por la luz solar y la humedad. Aun con las pérdidas de color inevitables tras dos mil años, la composición sigue siendo asombrosamente elegante.',
      'El resto del jardín estaba decorado con pequeñas esculturas y fuentes, formando un rincón de recreo privado pensado para el disfrute de la familia, más que para impresionar a grandes visitas oficiales. Es un buen ejemplo de cómo incluso las casas de tamaño medio en Pompeya dedicaban recursos considerables a rodearse de arte y de referencias mitológicas en su vida cotidiana.',
      'Venus, como recordarán desde nuestra primera parada junto al mar, era la diosa protectora de toda la ciudad, así que no debería sorprendernos encontrarla representada una y otra vez en las casas particulares, no solo en los grandes templos oficiales. Cada familia pompeyana, a su manera, colocaba su propia versión de la diosa en el lugar de la casa que consideraba más especial.',
      'La casa debe su nombre moderno precisamente a esta pintura, descubierta ya en el siglo veinte durante una de las últimas grandes campañas de excavación de esa zona de la ciudad. A pesar de tratarse de una vivienda modesta en comparación con la Casa del Fauno o la Casa de los Vettii, el cuidado puesto en decorar este rincón concreto demuestra que el buen gusto no era exclusivo de las grandes fortunas de Pompeya.',
    ],
    lookFor: [
      'La gran pintura de Venus en la concha marina, en el muro del fondo del jardín.',
      'Las pequeñas figuras de amorcillos que acompañan a la diosa en la composición.',
      'La estatua de Marte situada cerca de la escena principal.',
      'Los restos de las fuentes y pequeñas esculturas que decoraban el resto del jardín.',
    ],
    anecdote: 'Esta imagen de Venus en la concha es, junto al mosaico del cave canem, una de las escenas de Pompeya más reproducidas en postales, carteles y portadas de libros sobre la ciudad.',
    directionsToNext: 'La Casa de Octavio Cuartio está prácticamente pared con pared, un minuto caminando hacia el este por la misma Via dell’Abbondanza.',
    illus: 'fresco',
    tips: [
      'El cristal protector puede producir reflejos; buscad el ángulo lateral para fotografiar el fresco sin deslumbrarse.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'casa-octavio-cuartio',
    order: 19,
    name: 'Casa de Octavio Cuartio',
    latinName: 'Domus Loreii Tiburtini',
    category: 'domus',
    coords: [40.7517, 14.4924],
    regio: 'II.2.2',
    minutes: 15,
    walkMinutesToNext: 5,
    intro: 'Un canal de agua atraviesa todo el jardín de esta casa: aquí los dueños se construyeron su propia villa de recreo dentro de la ciudad.',
    narration: [
      'Esta casa se conoce también como la Casa de Loreio Tiburtino, por una inscripción electoral encontrada en la fachada, aunque el nombre que finalmente se le atribuyó, Octavio Cuartio, corresponde probablemente a su verdadero propietario. Lo que hace especial a esta vivienda es su enorme jardín trasero, organizado en torno a un largo canal de agua llamado eurípo, que recorre buena parte de la parcela en línea recta.',
      'A un lado del canal había un cenador cubierto con bancos, un biclinium, donde la familia y sus invitados podían recostarse a comer mientras contemplaban el agua correr y escuchaban el sonido de pequeñas fuentes distribuidas a lo largo del recorrido. Sobre el canal se alzaba además una pérgola cubierta de vides, que en verano ofrecía sombra fresca y racimos de uva al alcance de la mano.',
      'Las paredes que rodean el jardín conservan pinturas con escenas mitológicas como la caza de Acteón, convertido en ciervo y devorado por sus propios perros por haber visto bañarse a la diosa Diana, o la trágica historia de Píramo y Tisbe. Hay también elementos decorativos de inspiración egipcia, como pequeñas estatuas relacionadas con el culto a Isis, que reflejan la misma moda oriental que vimos en el templo anterior.',
      'Esta casa demuestra que algunas familias pompeyanas, sin salir de la ciudad, intentaban recrear en su propia parcela la experiencia de una villa de recreo campestre, con agua corriente, sombra vegetal y escenas mitológicas por todas partes. Era una forma de lujo pensada, sobre todo, para el disfrute privado de quienes vivían allí, más que para impresionar a desconocidos.',
    ],
    lookFor: [
      'El largo canal de agua o eurípo que atraviesa el jardín en línea recta.',
      'Los restos del cenador con bancos, el biclinium, junto al canal.',
      'Las pinturas mitológicas de Acteón y de Píramo y Tisbe en los muros del jardín.',
      'Las pequeñas estatuas de inspiración egipcia distribuidas por el recinto.',
    ],
    anecdote: 'El eurípo de esta casa imita a pequeña escala los grandes canales ornamentales de las villas imperiales romanas, como si sus propietarios quisieran, dentro de sus posibilidades, vivir como un emperador aunque fuera solo en su propio patio trasero.',
    directionsToNext: 'Bajad por la Via di Championnet hacia el sur, en dirección al Vicolo di Championnet: el Jardín de los Fugitivos está a unos cinco minutos.',
    illus: 'domus',
    tips: [
      'El jardín es largo y sin apenas sombra directa en las horas centrales del día; llevad agua.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'jardin-fugitivos',
    order: 20,
    name: 'Jardín de los Fugitivos',
    latinName: 'Hortus Fugitivorum',
    category: 'domus',
    coords: [40.749678, 14.492318],
    regio: 'I.21.6',
    minutes: 15,
    walkMinutesToNext: 6,
    intro: 'Aquí, en lo que fue un huerto y un viñedo, la erupción sorprendió a un grupo de personas mientras intentaban escapar.',
    narration: [
      'Este espacio era en origen un huerto y viñedo dentro de las murallas de la ciudad, un uso agrícola perfectamente normal en una Pompeya que, aunque urbana, conservaba huertos y jardines productivos en varias zonas, sobre todo cerca de las puertas. El nombre moderno del lugar, sin embargo, hace referencia a algo mucho más trágico que ocurrió aquí durante la erupción.',
      'En este punto se encontró un grupo de trece víctimas, probablemente una familia completa con niños, que habían intentado huir de la ciudad cuando ya era demasiado tarde. Quedaron atrapadas por la lluvia de ceniza y los gases tóxicos, y sus cuerpos, al descomponerse dentro de la ceniza endurecida, dejaron huecos con la forma exacta de sus posturas finales en el momento de morir.',
      'Fue el arqueólogo Giuseppe Fiorelli quien, en 1863, tuvo la idea de verter yeso líquido dentro de esos huecos antes de retirar la ceniza que los rodeaba, logrando así reproducir con un detalle estremecedor no solo los cuerpos, sino también los pliegues de la ropa e incluso las expresiones de las caras en el instante final. Los calcos que ven expuestos aquí, en vitrinas junto al recorrido, son precisamente ese testimonio directo de la tragedia humana detrás de las ruinas.',
      'Más allá de la evidente carga emocional del lugar, esta técnica revolucionó por completo la manera de estudiar la erupción, porque permitió a los investigadores conocer con precisión la edad, la postura, e incluso, en algunos casos, la vestimenta de las víctimas. Detenerse aquí en silencio, después de haber recorrido casas, termas y tiendas llenas de vida cotidiana, ayuda a no olvidar nunca que Pompeya no es solo un decorado antiguo, sino el lugar donde miles de personas reales perdieron la vida en apenas unas horas.',
    ],
    lookFor: [
      'Los calcos de yeso expuestos en vitrinas, con las posturas finales de las víctimas.',
      'Las marcas de los antiguos surcos de plantación de vides conservadas en el terreno.',
      'La disposición del grupo de calcos, que sugiere que intentaban huir juntos en el mismo momento.',
      'Los detalles de ropa y calzado que aún se distinguen en algunos de los calcos mejor conservados.',
    ],
    anecdote: 'La técnica del vaciado en yeso ideada por Fiorelli se sigue usando hoy en día, ahora combinada con escáneres y resinas transparentes que permiten además estudiar los huesos sin romper el molde exterior.',
    directionsToNext: 'Salid hacia el este por el camino perimetral en dirección a la Via di Nocera: la Palestra Grande se abre a la izquierda, unos cinco minutos de camino.',
    image: { src: 'jardin-fugitivos', alt: 'Calcos de yeso en el Jardín de los Fugitivos de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'yeso',
    tips: [
      'Es una de las paradas más emotivas del recorrido; conviene avisar con antelación si viajáis con niños pequeños.',
      'No se permite el uso de flash frente a las vitrinas de los calcos.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'palestra-grande',
    order: 21,
    name: 'Palestra Grande',
    latinName: 'Palaestra Magna',
    category: 'servicio',
    coords: [40.75081, 14.49395],
    minutes: 12,
    walkMinutesToNext: 3,
    intro: 'Este inmenso patio cuadrado era el gimnasio de la juventud pompeyana, casi tan grande como dos campos de fútbol juntos.',
    narration: [
      'La Palestra Grande se construyó en época de Augusto, a comienzos del siglo primero de nuestra era, como un enorme espacio de ciento cuarenta metros de lado rodeado por un pórtico de columnas en tres de sus lados. Estaba destinada al ejercicio físico y a la formación de los jóvenes pompeyanos organizados en un colectivo cívico conocido como la iuventus, inspirado directamente en modelos de entrenamiento militar y deportivo promovidos desde Roma.',
      'En el centro del recinto había una gran piscina rectangular, la natatio, con una profundidad que aumentaba gradualmente de un extremo a otro, pensada tanto para nadar como para pruebas de resistencia física. Alrededor de la piscina y del patio se plantaron hileras regulares de árboles, probablemente plátanos, cuyas huellas de raíces han permitido a los arqueólogos reconstruir con bastante exactitud el aspecto ajardinado del conjunto.',
      'Aquí los jóvenes practicaban lucha, carreras, lanzamiento de disco y jabalina, y en general todo tipo de disciplinas que formaban parte de la educación física de un ciudadano romano de buena familia. No era solo cuestión de deporte: formar parte de la iuventus era también una forma de entrenamiento cívico y social, una manera de hacer contactos que después resultarían útiles en la vida pública adulta.',
      'La escala descomunal de este espacio, comparado con cualquier otro edificio deportivo de la ciudad, da una idea de la importancia que Roma concedía a la formación física y moral de sus futuros ciudadanos. Caminar hoy por este patio vacío, rodeado únicamente de columnas y del recuerdo de los árboles desaparecidos, todavía transmite algo de esa vocación de grandeza.',
    ],
    lookFor: [
      'Las dimensiones del patio, de ciento cuarenta metros de lado, uno de los espacios más grandes de todo el yacimiento.',
      'Los restos de la piscina rectangular o natatio en el centro del recinto.',
      'Las hileras de huecos en el suelo que marcan la posición de los antiguos árboles plantados.',
      'El pórtico de columnas que recorre tres de los cuatro lados del patio.',
    ],
    anecdote: 'Los árboles de la palestra fueron replantados siguiendo exactamente las huellas de las raíces originales encontradas por los arqueólogos, así que la sombra que puedan encontrar aquí hoy cae, en teoría, en el mismo lugar exacto que hace dos mil años.',
    directionsToNext: 'Salid por el lado este de la palestra hacia la Piazza Anfiteatro: el Anfiteatro está justo enfrente, unos tres minutos de camino.',
    image: { src: 'palestra-grande', alt: 'Columnas de la Palestra Grande de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'columna',
    tips: [
      'Es un espacio muy abierto y sin apenas sombra al mediodía; buen momento para protegerse del sol antes del tramo final.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'anfiteatro',
    order: 22,
    name: 'Anfiteatro',
    latinName: 'Amphitheatrum',
    category: 'espectaculo',
    coords: [40.751264, 14.494969],
    minutes: 20,
    walkMinutesToNext: 5,
    intro: 'Terminamos el gran recorrido en el edificio de espectáculos más antiguo que se conserva en piedra de todo el mundo romano.',
    narration: [
      'Este anfiteatro se construyó hacia el año setenta antes de nuestra era, poco después de que Pompeya se convirtiera en colonia romana, y es el ejemplo más antiguo conocido de un anfiteatro construido enteramente en piedra desde el principio, sin fases previas en madera como ocurrió en otras ciudades, incluida la propia Roma. Podía albergar hasta veinte mil espectadores, una cifra que superaba con creces la población total de Pompeya, lo que demuestra que aquí venía gente de toda la región.',
      'A diferencia del Coliseo de Roma, este anfiteatro no tiene subterráneos bajo la arena. Gladiadores y animales entraban directamente desde el exterior por dos grandes rampas de acceso situadas en los extremos del eje mayor, una solución más sencilla pero perfectamente funcional para organizar combates y cacerías públicas ante un público entregado.',
      'El historiador Tácito relató un suceso ocurrido aquí en el año cincuenta y nueve: durante unos juegos de gladiadores, estalló una violenta pelea entre los pompeyanos y los habitantes de la vecina Nuceria, con numerosos heridos y muertos. Como castigo, el Senado romano prohibió celebrar espectáculos de gladiadores en Pompeya durante diez años, una de las primeras sanciones documentadas de la historia contra la violencia en un recinto deportivo.',
      'Sobre las gradas se instalaba en los días de más calor un enorme toldo llamado velarium, sujeto mediante mástiles de madera cuyos anclajes todavía pueden verse en la parte superior del graderío. Sentarse hoy en estas gradas de piedra, en silencio, permite imaginar sin demasiado esfuerzo el rugido de veinte mil personas coreando el nombre de su gladiador favorito.',
    ],
    lookFor: [
      'Las dos grandes rampas de acceso a la arena, situadas en los extremos del eje mayor del edificio.',
      'Los anclajes de piedra en lo alto del graderío, usados para sujetar los mástiles del velarium.',
      'La ausencia de subterráneos bajo la arena, a diferencia de anfiteatros posteriores como el Coliseo.',
      'La escala general del graderío, capaz de albergar a más gente que toda la población de la ciudad.',
    ],
    anecdote: 'La revuelta entre pompeyanos y habitantes de Nuceria, descrita por Tácito, se ha comparado a menudo con los enfrentamientos actuales entre aficiones rivales de fútbol: la rivalidad regional violenta, por lo visto, no es ningún invento moderno.',
    directionsToNext: 'Salid por la Piazza Anfiteatro y bajad por la Via di Nocera hacia el sur, en dirección a la antigua Porta di Nocera: la Necrópolis de Porta Nocera está fuera de las murallas, unos siete minutos de camino.',
    image: { src: 'anfiteatro', alt: 'Graderío del Anfiteatro de Pompeya', credit: 'Wikimedia Commons' },
    illus: 'gladiador',
    tips: [
      'Hay baños públicos y una zona de sombra junto a la Piazza Anfiteatro, última antes del tramo final de la ruta.',
      'Esta salida por Piazza Anfiteatro es también un punto habitual para terminar la visita y salir del recinto, si no van a continuar hacia la necrópolis.',
    ],
    accessibility: 'facil',
  },
  {
    id: 'necropolis-porta-nocera',
    order: 23,
    name: 'Necrópolis de Porta Nocera',
    category: 'necropolis',
    coords: [40.749237, 14.493755],
    minutes: 12,
    walkMinutesToNext: 0,
    intro: 'La ley romana prohibía enterrar a los muertos dentro de las murallas, así que la ciudad de los vivos y la de los muertos convivían, pared con pared, junto a cada puerta.',
    narration: [
      'Salimos por la Porta di Nocera para encontrarnos con una de las necrópolis mejor conservadas de todo el mundo romano. Como en cualquier ciudad del Imperio, enterrar a los muertos dentro del recinto amurallado estaba estrictamente prohibido por motivos religiosos e higiénicos, así que las tumbas se alineaban a ambos lados de los caminos de acceso a la ciudad, precisamente para que cualquiera que llegara viera primero los monumentos funerarios de quienes le habían precedido.',
      'Aquí conviven varios tipos de sepultura: desde sencillas columnas con inscripciones, llamadas columelas, hasta grandes tumbas en forma de altar o de banco semicircular, reservadas a las familias con más recursos. Las inscripciones nos hablan de sacerdotisas públicas, de comerciantes enriquecidos y de antiguos esclavos liberados que, en la muerte, buscaban el mismo reconocimiento social que en vida les había resultado más difícil de conseguir.',
      'En esta misma necrópolis se hallaron también varios calcos de víctimas de la erupción, personas que probablemente intentaban salir de la ciudad por esta puerta cuando la nube de gases y ceniza las alcanzó. La cercanía entre las tumbas de siglos anteriores y los cuerpos de las víctimas del año setenta y nueve añade una capa extra de significado a este lugar: la muerte antigua, ritualizada y monumental, y la muerte súbita de la catástrofe, conviven en el mismo espacio.',
      'Recorrer esta necrópolis es un buen cierre para la visita a la ciudad amurallada, porque reúne de golpe muchos de los temas que hemos ido tocando durante todo el día: la organización legal romana, las diferencias sociales expresadas incluso después de la muerte, y la memoria concreta, casi física, de la tragedia que selló para siempre el destino de Pompeya.',
    ],
    lookFor: [
      'Las columelas, sencillas columnas de piedra con inscripciones, como marcadores de tumbas modestas.',
      'Las grandes tumbas en forma de altar o de banco semicircular pertenecientes a familias acomodadas.',
      'Las inscripciones que mencionan oficios, cargos religiosos o la condición de liberto del difunto.',
      'La proximidad entre las tumbas antiguas y los puntos donde se hallaron víctimas de la erupción.',
    ],
    anecdote: 'Una de las tumbas más conocidas de esta necrópolis perteneció a una sacerdotisa pública llamada Eumáquia, la misma benefactora cuyo nombre lleva el gran edificio comercial que visitamos junto al foro.',
    directionsToNext: 'Aquí termina el recorrido principal por el recinto amurallado. Si deseáis añadir la Villa de los Misterios, consultad las indicaciones específicas en las notas prácticas de esta parada.',
    image: { src: 'necropolis-porta-nocera', alt: 'Tumbas de la Necrópolis de Porta Nocera en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'ceniza',
    tips: [
      'Es un buen punto para dar por terminada la visita si el grupo está cansado, volviendo hacia la Piazza Anfiteatro para salir del recinto.',
      'Para llegar a la Villa de los Misterios desde aquí hay que atravesar de nuevo casi toda la ciudad; resulta más práctico dejarla para el principio o el final del día entrando o saliendo por la Porta Marina o la Porta di Ercolano.',
    ],
    accessibility: 'medio',
  },
  {
    id: 'villa-misterios',
    order: 24,
    name: 'Villa de los Misterios',
    latinName: 'Villa Pompeiana in Suburbio Mysteriorum',
    category: 'villa',
    coords: [40.753694, 14.477444],
    minutes: 25,
    intro: 'Cerramos, o quizá abramos, la visita con la pintura más enigmática de todo el mundo romano: una iniciación pintada de tamaño real.',
    narration: [
      'La Villa de los Misterios es una gran residencia suburbana situada fuera de las murallas, en una colina con vistas al mar, en el extremo noroeste del yacimiento. Aunque comenzó siendo una lujosa villa de recreo, con el paso de los años parte de sus instalaciones se dedicaron también a la producción de vino, con un lagar y prensas conservados en una de las alas del edificio, mezclando ocio y negocio bajo el mismo techo.',
      'Su fama mundial se debe a un friso pictórico único, pintado hacia el año sesenta antes de nuestra era sobre fondo rojo pompeyano, que ocupa las paredes de una de las salas principales con figuras de tamaño casi natural. La escena parece representar el proceso de iniciación de una joven novia en los misterios del culto a Dioniso, el dios del vino y del éxtasis, aunque el significado exacto de cada escena sigue siendo objeto de debate entre los especialistas.',
      'En la composición aparecen músicos, sátiros, una figura femenina alada que parece azotar a la iniciada, y la propia pareja divina de Dioniso y Ariadna presidiendo la escena central. Es, sin exagerar, una de las obras de pintura antigua mejor conservadas de todo el mundo, tanto por la calidad técnica como por la intensidad casi teatral de las expresiones de cada personaje.',
      'La villa se excavó entre 1909 y 1910, ya con métodos arqueológicos mucho más cuidadosos que los de las primeras campañas del siglo dieciocho, lo que explica el extraordinario estado de conservación de sus pinturas. Termina aquí, o empieza, según el orden que hayan elegido para su visita, un recorrido que atraviesa toda la historia de Pompeya: desde el culto agrario más antiguo hasta el misterio religioso más elaborado, pasando por el foro, las casas, los baños, el teatro y la tragedia final de la erupción.',
    ],
    lookFor: [
      'El friso completo de la sala de los misterios, con sus figuras de tamaño casi natural sobre fondo rojo.',
      'La figura alada que parece fustigar a la joven iniciada, una de las escenas más comentadas del friso.',
      'Los restos del lagar y las prensas de vino en el ala rústica de la villa.',
      'La terraza con vistas al mar en la fachada que mira hacia el golfo.',
    ],
    anecdote: 'Casi ciento veinte años después de su descubrimiento, historiadores del arte y especialistas en religión romana siguen sin ponerse de acuerdo sobre el significado exacto de cada escena del friso: pocas obras de arte antiguas han generado tanta discusión académica ininterrumpida.',
    directionsToNext: undefined,
    image: { src: 'villa-misterios-fresco', alt: 'Friso pictórico de la Villa de los Misterios en Pompeya', credit: 'Wikimedia Commons' },
    illus: 'fresco',
    tips: [
      'La villa queda en el extremo noroeste del yacimiento, separada del recinto principal; se llega en unos quince minutos a pie desde la Porta Marina o rodeando por la Porta di Ercolano.',
      'Muchos visitantes prefieren visitarla a primera hora, nada más entrar por la Porta Marina, o al final del día justo antes de salir, en lugar de intentar volver hasta aquí desde la Necrópolis de Porta Nocera.',
      'Es una parada final excelente para quienes lleguen en coche o en autobús turístico, ya que tiene su propio acceso cercano fuera de las murallas.',
    ],
    accessibility: 'medio',
  },
];

export const ROUTE: Route = {
  id: 'clasica',
  name: 'Ruta clásica de Pompeya',
  description: 'El recorrido completo del día de visita, desde la Porta Marina hasta el Anfiteatro, con la Villa de los Misterios como parada final o inicial opcional. Sigue el orden caminable más lógico entre el foro, el barrio de las grandes domus, las termas, el teatro y la zona de los espectáculos, sin retrocesos innecesarios. Pensado para completarse en una sola jornada, con paradas de distinta duración según el interés y las colas de cada edificio.',
  totalHours: '5-6 h sin la Villa de los Misterios, hasta 7 h incluyéndola',
  distanceKm: 6.4,
  start: 'porta-marina',
  stops: STOPS,
  path: [
    [40.748509, 14.483085],
    [40.748509, 14.483085],
    [40.748576, 14.483355],
    [40.748698, 14.483781],
    [40.748766, 14.483998],
    [40.748765, 14.48403],
    [40.748753, 14.484035],
    [40.74868, 14.483913],
    [40.748652, 14.483845],
    [40.748425, 14.483872],
    [40.748652, 14.483845],
    [40.74868, 14.483913],
    [40.748753, 14.484035],
    [40.748765, 14.48403],
    [40.748881, 14.484394],
    [40.748839, 14.484415],
    [40.748811, 14.484429],
    [40.7488, 14.4845],
    [40.748811, 14.484429],
    [40.748839, 14.484415],
    [40.748881, 14.484394],
    [40.748935, 14.484565],
    [40.748978, 14.484534],
    [40.748999, 14.484518],
    [40.74921, 14.4844],
    [40.748999, 14.484518],
    [40.748978, 14.484534],
    [40.748935, 14.484565],
    [40.749006, 14.484783],
    [40.748857, 14.484866],
    [40.748768, 14.484916],
    [40.748898, 14.485324],
    [40.748904, 14.485342],
    [40.749102, 14.485232],
    [40.7493, 14.485121],
    [40.749537, 14.48499],
    [40.749447, 14.484825],
    [40.749537, 14.48499],
    [40.7493, 14.485121],
    [40.749102, 14.485232],
    [40.749147, 14.485418],
    [40.749165, 14.485323],
    [40.749147, 14.485418],
    [40.749102, 14.485232],
    [40.7493, 14.485121],
    [40.749537, 14.48499],
    [40.74979, 14.484849],
    [40.74981, 14.484744],
    [40.750116, 14.484567],
    [40.750137, 14.484556],
    [40.750162, 14.484543],
    [40.750047, 14.484289],
    [40.750004, 14.484202],
    [40.750159, 14.484006],
    [40.750342, 14.483785],
    [40.7504, 14.4841],
    [40.750342, 14.483785],
    [40.750406, 14.483702],
    [40.75042, 14.483689],
    [40.75045, 14.483666],
    [40.750507, 14.483803],
    [40.750663, 14.483706],
    [40.750672, 14.483814],
    [40.750663, 14.483706],
    [40.750507, 14.483803],
    [40.75068, 14.484186],
    [40.750711, 14.484237],
    [40.750719, 14.484243],
    [40.750727, 14.48425],
    [40.750733, 14.484256],
    [40.75074, 14.484266],
    [40.75088, 14.484593],
    [40.750943, 14.484727],
    [40.750957, 14.484716],
    [40.750976, 14.484701],
    [40.75102, 14.484671],
    [40.75104, 14.484656],
    [40.751027, 14.48462],
    [40.751111, 14.484565],
    [40.751108, 14.484557],
    [40.751195, 14.4845],
    [40.751222, 14.484571],
    [40.751263, 14.484545],
    [40.751267, 14.484553],
    [40.75125, 14.484583],
    [40.751267, 14.484553],
    [40.751272, 14.484559],
    [40.751279, 14.484562],
    [40.751286, 14.484562],
    [40.751292, 14.484559],
    [40.751326, 14.484646],
    [40.751387, 14.484606],
    [40.751392, 14.484621],
    [40.751411, 14.484609],
    [40.751475, 14.484567],
    [40.751499, 14.484632],
    [40.751762, 14.484474],
    [40.751736, 14.484398],
    [40.75177, 14.484379],
    [40.751786, 14.48437],
    [40.75184, 14.484488],
    [40.751982, 14.484798],
    [40.751996, 14.484788],
    [40.752021, 14.484771],
    [40.752004, 14.484727],
    [40.752086, 14.484671],
    [40.752048, 14.484561],
    [40.752083, 14.484583],
    [40.752048, 14.484561],
    [40.752086, 14.484671],
    [40.752004, 14.484727],
    [40.752021, 14.484771],
    [40.751996, 14.484788],
    [40.751982, 14.484798],
    [40.752013, 14.484867],
    [40.75191, 14.484937],
    [40.751827, 14.484986],
    [40.751671, 14.485083],
    [40.751461, 14.485212],
    [40.751257, 14.485329],
    [40.751236, 14.485343],
    [40.751284, 14.485447],
    [40.75126, 14.485461],
    [40.751101, 14.485559],
    [40.75105, 14.48558],
    [40.750975, 14.485588],
    [40.750906, 14.485587],
    [40.750712, 14.485561],
    [40.750635, 14.485558],
    [40.750479, 14.485534],
    [40.750391, 14.485547],
    [40.750446, 14.485816],
    [40.750467, 14.485939],
    [40.750479, 14.486015],
    [40.750489, 14.4861],
    [40.750493, 14.486147],
    [40.750497, 14.486195],
    [40.750508, 14.486348],
    [40.750515, 14.486422],
    [40.750519, 14.486454],
    [40.750527, 14.486497],
    [40.750533, 14.48652],
    [40.750527, 14.486524],
    [40.750522, 14.486529],
    [40.750485, 14.486574],
    [40.750456, 14.486616],
    [40.750375, 14.486719],
    [40.750301, 14.48686],
    [40.750294, 14.486879],
    [40.750286, 14.486859],
    [40.750263, 14.486811],
    [40.750248, 14.486792],
    [40.75025, 14.486778],
    [40.750248, 14.486792],
    [40.750234, 14.486797],
    [40.750239, 14.48682],
    [40.750251, 14.48688],
    [40.75026, 14.486924],
    [40.750196, 14.486984],
    [40.75013, 14.487041],
    [40.750066, 14.487083],
    [40.749996, 14.487112],
    [40.750002, 14.487143],
    [40.750036, 14.487305],
    [40.75004, 14.487314],
    [40.750116, 14.487491],
    [40.750125, 14.487513],
    [40.749907, 14.487697],
    [40.749921, 14.487616],
    [40.749907, 14.487697],
    [40.749892, 14.487709],
    [40.749877, 14.487722],
    [40.749846, 14.487646],
    [40.749801, 14.487684],
    [40.749754, 14.487724],
    [40.749788, 14.487811],
    [40.7498, 14.4878],
    [40.749788, 14.487811],
    [40.749852, 14.487956],
    [40.7499, 14.488025],
    [40.74995, 14.488098],
    [40.750142, 14.488511],
    [40.750261, 14.488776],
    [40.750287, 14.488834],
    [40.750361, 14.488997],
    [40.750311, 14.489139],
    [40.750361, 14.488997],
    [40.750546, 14.489412],
    [40.750414, 14.489552],
    [40.750086, 14.489932],
    [40.750031, 14.489996],
    [40.750006, 14.490025],
    [40.749903, 14.490144],
    [40.749722, 14.49],
    [40.749903, 14.490144],
    [40.749621, 14.490408],
    [40.749356, 14.489851],
    [40.749341, 14.489821],
    [40.749267, 14.489662],
    [40.749158, 14.489395],
    [40.749049, 14.48918],
    [40.749026, 14.489157],
    [40.749084, 14.489087],
    [40.749057, 14.489036],
    [40.748907, 14.488731],
    [40.748824, 14.488553],
    [40.74879, 14.48849],
    [40.748803, 14.488479],
    [40.748817, 14.488465],
    [40.748826, 14.488456],
    [40.748795, 14.488416],
    [40.748826, 14.488456],
    [40.748833, 14.488449],
    [40.748839, 14.48844],
    [40.748843, 14.488433],
    [40.748884, 14.488451],
    [40.748888, 14.488436],
    [40.74889, 14.48842],
    [40.74889, 14.488399],
    [40.748888, 14.48838],
    [40.749054, 14.488312],
    [40.7492, 14.4883],
    [40.749054, 14.488312],
    [40.749063, 14.488382],
    [40.749059, 14.488452],
    [40.749043, 14.488523],
    [40.749018, 14.488582],
    [40.748987, 14.488629],
    [40.74895, 14.488671],
    [40.748929, 14.488689],
    [40.748916, 14.4887],
    [40.748924, 14.488716],
    [40.749074, 14.489001],
    [40.749079, 14.48901],
    [40.749108, 14.489063],
    [40.749467, 14.488647],
    [40.749808, 14.489331],
    [40.749856, 14.489447],
    [40.749929, 14.489614],
    [40.75001, 14.489801],
    [40.750086, 14.489932],
    [40.750414, 14.489552],
    [40.750546, 14.489412],
    [40.750753, 14.489868],
    [40.75092, 14.490244],
    [40.751104, 14.490624],
    [40.751276, 14.491003],
    [40.751448, 14.491373],
    [40.75162, 14.491743],
    [40.7518, 14.49214],
    [40.751845, 14.492239],
    [40.751973, 14.492522],
    [40.752029, 14.492645],
    [40.751957, 14.492723],
    [40.752029, 14.492645],
    [40.751973, 14.492522],
    [40.751941, 14.492549],
    [40.75127, 14.493092],
    [40.75123, 14.493125],
    [40.751138, 14.492933],
    [40.75118, 14.492899],
    [40.751225, 14.492862],
    [40.751331, 14.492775],
    [40.75161, 14.492547],
    [40.751598, 14.492521],
    [40.751617, 14.492505],
    [40.75162, 14.492503],
    [40.75163, 14.492494],
    [40.751612, 14.492457],
    [40.751658, 14.492419],
    [40.7517, 14.4924],
    [40.751658, 14.492419],
    [40.751612, 14.492457],
    [40.75163, 14.492494],
    [40.75162, 14.492503],
    [40.751617, 14.492505],
    [40.751598, 14.492521],
    [40.75161, 14.492547],
    [40.751331, 14.492775],
    [40.751225, 14.492862],
    [40.75118, 14.492899],
    [40.751138, 14.492933],
    [40.751073, 14.492735],
    [40.750887, 14.492336],
    [40.75074, 14.492454],
    [40.750703, 14.492485],
    [40.750227, 14.492858],
    [40.750054, 14.492478],
    [40.749879, 14.492106],
    [40.749678, 14.492318],
    [40.749879, 14.492106],
    [40.750054, 14.492478],
    [40.750227, 14.492858],
    [40.750398, 14.493258],
    [40.750521, 14.493163],
    [40.750951, 14.492829],
    [40.750987, 14.492907],
    [40.751004, 14.492943],
    [40.751482, 14.493972],
    [40.751503, 14.494018],
    [40.751, 14.494428],
    [40.750977, 14.49438],
    [40.75081, 14.49395],
    [40.750977, 14.49438],
    [40.751, 14.494428],
    [40.751057, 14.494551],
    [40.750792, 14.494764],
    [40.750669, 14.494981],
    [40.750693, 14.495029],
    [40.750709, 14.495119],
    [40.750855, 14.495428],
    [40.750902, 14.495471],
    [40.75094, 14.495441],
    [40.750932, 14.495422],
    [40.751002, 14.495367],
    [40.750999, 14.495316],
    [40.751017, 14.495239],
    [40.751054, 14.495161],
    [40.751126, 14.495069],
    [40.75121, 14.494994],
    [40.751272, 14.494956],
    [40.751264, 14.494969],
    [40.751272, 14.494956],
    [40.75121, 14.494994],
    [40.751126, 14.495069],
    [40.751054, 14.495161],
    [40.751017, 14.495239],
    [40.750999, 14.495316],
    [40.751002, 14.495367],
    [40.750932, 14.495422],
    [40.75094, 14.495441],
    [40.750902, 14.495471],
    [40.750855, 14.495428],
    [40.750709, 14.495119],
    [40.750693, 14.495029],
    [40.750669, 14.494981],
    [40.750619, 14.494882],
    [40.750508, 14.494921],
    [40.75032, 14.495002],
    [40.750179, 14.495063],
    [40.750139, 14.49493],
    [40.749992, 14.494892],
    [40.749812, 14.49499],
    [40.749802, 14.49496],
    [40.749788, 14.494916],
    [40.749651, 14.494987],
    [40.749506, 14.494639],
    [40.749297, 14.494121],
    [40.749223, 14.493885],
    [40.749207, 14.493799],
    [40.749255, 14.493751],
    [40.749237, 14.493755]
  ],
};