import { chromium, devices } from 'playwright';
const base = 'https://rcarreira-drg.github.io/pompei-guide/#';
const out = '/tmp/claude-1000/-home-rodri-pompei-guide/17b5432f-d492-4198-98f5-51a7bd804e66/scratchpad/live';
import { mkdirSync } from 'node:fs'; mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'], geolocation: { latitude: 40.7492, longitude: 14.4848 }, permissions: ['geolocation'], locale: 'es-ES' });
const page = await ctx.newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message)); page.on('console', m => m.type() === 'error' && errs.push(m.text()));
const failed = []; page.on('response', r => { if (r.status() >= 400 && !/tile\.openstreetmap/.test(r.url())) failed.push(r.status() + ' ' + r.url()); });
await page.goto(base + '/', { waitUntil: 'networkidle' });
await page.screenshot({ path: `${out}/home.png` });
const sw = await page.evaluate(async () => { const r = await navigator.serviceWorker?.getRegistration(); return !!r; });
await page.goto(base + '/visita', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /activar ubicaci/i }).click().catch(() => {});
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/visita-geo.png`, fullPage: false });
const banner = await page.getByText(/ESTÁS EN/i).count();
await page.goto(base + '/visita/foro', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /visitada/i }).first().click();
await page.waitForTimeout(500);
const url = page.url();
const imgs = await page.evaluate(() => Array.from(document.images).map(i => ({ src: i.currentSrc, ok: i.complete && i.naturalWidth > 0 })));
console.log(JSON.stringify({ sw, banner, urlAfterMark: url, brokenImgs: imgs.filter(i => !i.ok).map(i => i.src), errs: errs.filter(e => !/tile/.test(e)), failed }, null, 1));
await browser.close();
